### ISSUE TITLE
Yii2 functional tests strange fail

### ISSUE THREAD

**Issue by Nemmo** [Codeception/Codeception#2605]
Hello everyone!

I am writing the next own functional test and it fails. Here is the code
```php
<?php
namespace tests\codeception\backend\partner;

use Codeception\Util\Debug;
use tests\codeception\backend\FunctionalTester;
use tests\codeception\backend\pages\LoginPage;
use yii\helpers\Url;

class LoyaltyCest
{
    public function _before(FunctionalTester $I)
    {
        $loginPage = LoginPage::openBy($I);
        $loginPage->loginAsPartner();
    }

    public function _after(FunctionalTester $I)
    {
    }

    public function actionConstruct(FunctionalTester $i)
    {
        $i->amGoingTo('submit empty loyalty program');
        $i->amOnPage(['partner/loyalty/index']);
    }

    public function actionIndex(FunctionalTester $i)
    {
        $i->amGoingTo('test all members list');
        $i->amOnPage(['partner/member/index']);
    }
}
```
The strange behaviour is that `actionConstruct` test fails, but the second `actionIndex` success.

And here is the console output:
```console
Codeception PHP Testing Framework v2.0.16
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

Tests\codeception\backend.functional Tests (2) -----------------------------------------------------------------------------------------------------------------------
Modules: Filesystem, Yii2, FixtureHelper
----------------------------------------------------------------------------------------------------------------------------------------------------------------------
Action construct (tests\codeception\backend\partner\LoyaltyCest::actionConstruct)
Scenario:
* I am on page "/index-test.php/identity/login/"

  [Response] 200
  [Page] https://localhost/index-test.php/identity/login/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I fill field "input[name="LoginForm[phone]"]","7071111111"
* I fill field "input[name="LoginForm[password]"]","123456"
* I click "#btnSignin"
  [Uri] https://localhost/index-test.php/identity/login/
  [Method] POST
  [Parameters] {"LoginForm":{"phone":"7071111111","password":"123456"},"keepSignin":"on"}
  [Headers] {"location":["https://localhost/index-test.php/partner/default/index/"],"content-type":["text/html; charset=UTF-8"]}
  [Response] 200
  [Page] https://localhost/index-test.php/partner/default/index/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I am going to submit empty loyalty program
* I am on page "partner/loyalty/index"
 ERROR

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Action index (tests\codeception\backend\partner\LoyaltyCest::actionIndex)
Scenario:
* I am on page "/index-test.php/identity/login/"

  [Response] 200
  [Page] https://localhost/index-test.php/identity/login/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I fill field "input[name="LoginForm[phone]"]","7071111111"
* I fill field "input[name="LoginForm[password]"]","123456"
* I click "#btnSignin"
  [Uri] https://localhost/index-test.php/identity/login/
  [Method] POST
  [Parameters] {"LoginForm":{"phone":"7071111111","password":"123456"},"keepSignin":"on"}
  [Headers] {"location":["https://localhost/index-test.php/partner/default/index/"],"content-type":["text/html; charset=UTF-8"]}
  [Response] 200
  [Page] https://localhost/index-test.php/partner/default/index/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
* I am going to test all members list
* I am on page "partner/member/index"
  [Response] 200
  [Page] https://localhost/index-test.php/partner/member/index/
  [Cookies] []
  [Headers] {"content-type":["text/html; charset=UTF-8"]}
 PASSED

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
----------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 11.46 seconds, Memory: 27.25Mb

There was 1 error:

---------
1) Failed to action construct in tests\codeception\backend\partner\LoyaltyCest::actionConstruct (C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\tests\codeception\backend\.\functional\partner/LoyaltyCest.php)
Can't be on page "partner/loyalty/index":
yii\base\ErrorException: Trying to get property of non-object

Scenario Steps:
6. I am on page "partner/loyalty/index"
5. I am going to submit empty loyalty program
4. I click "#btnSignin"
3. I fill field "input[name="LoginForm[password]"]","123456"
2. I fill field "input[name="LoginForm[phone]"]","7071111111"
1. I am on page "/index-test.php/identity/login/"


  [yii\base\ErrorException] Trying to get property of non-object

#0 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestCase.php(702): PHPUnit_Framework_TestResult->run(Object(Codeception\TestCase\Cest))
#1 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestSuite.php(738): PHPUnit_Framework_TestCase->run(Object(PHPUnit_Framework_TestResult))
#2 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\PHPUnit\Runner.php(100): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#3 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\SuiteManager.php(158): Codeception\PHPUnit\Runner->doEnhancedRun(Object(PHPUnit_Framework_TestSuite), Object(PHPUnit_Framework_TestResult), Array)
#4 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Codecept.php(175): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit_Framework_TestResult), Array)
#5 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Codecept.php(158): Codeception\Codecept->runSuite(Array, 'functional', 'partner/Loyalty...')
#6 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Command\Run.php(187): Codeception\Codecept->run('functional', 'partner/Loyalty...')
#7 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Command\Command.php(259): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php(841): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\codecept(27): Symfony\Component\Console\Application->run()
#12 {main}

FAILURES!
Tests: 2, Assertions: 0, Errors: 1.
```

**Comment by samdark** [comment]
@DavertMik trace looks like it's and error in Codeception itself, right?

**Comment by Naktibalda** [comment]
Can you tell where the error happens from that output?

@Nemmo Please run this test with `-vvv` flag to get more information.

**Comment by Nemmo** [comment]
The output I have attached is already run with ```-vvv``` flag. It happen, just happen when I try to test my app. And that is really very strange

**Comment by Naktibalda** [comment]
Try to catch exception and getFile() and getLine() from it.
If that doesn't work, use xdebug to find the line where the error happens.

**Comment by Nemmo** [comment]
OK, I will try to catch exception tomorrow, but unfortunately I don't know how to use xdebug while running the tests.

**Comment by DavertMik** [comment]
The stack trace does not provide a clue of what happened there. Codeception 2.1 shows better stack traces, could you try to update to it and run once again?

**Comment by Nemmo** [comment]
Yes, I can, but there is one problem - as I know, Yii2 does not support Codeception 2.1. 
@samdark Am I correct?

**Comment by DavertMik** [comment]
There were no major changes in Codeception 2.1 which could break Yii support. So you should probably try to upgrade... 2.1 is branch which is actively maintained so probably your issue may be fixed in latest 2.1 releases

**Comment by samdark** [comment]
@Nemmo I think it works well with it. If not, report.

**Comment by Nemmo** [comment]
Everything works, but ```build``` command shows some warnings. ```run -vvv``` command shows the next lines (looks like it is an error inside ```yii-codeception``` module):
```console
Codeception PHP Testing Framework v2.1.0                                                                                                                                               
Powered by PHPUnit 4.7.7 by Sebastian Bergmann and contributors.                                                                                                                       
                                                                                                                                                                                       
Tests\codeception\backend.functional Tests (2) -----------------------------------------------------------------------------------------------------------------------                 
Modules: Filesystem, Yii2, \tests\codeception\common\_support\FixtureHelper                                                                                                            
----------------------------------------------------------------------------------------------------------------------------------------------------------------------                 
Action construct (\partner\LoyaltyCest::actionConstruct)                                                                                                                               
Scenario:                                                                                                                                                                              
* yii\codeception\BasePage: open by                                                                                                                                                    
  I am on page "/index-test.php/identity/login/"                                                                                                                                       
                                                                                                                                                                                       
  [Response] 200                                                                                                                                                                       
  [Page] https://localhost/index-test.php/identity/login/                                                                                                                              
  [Cookies] []                                                                                                                                                                         
  [Headers] {"content-type":["text/html; charset=UTF-8"]}                                                                                                                              
* tests\codeception\backend\pages\LoginPage: login as partner                                                                                                                          
  I fill field "input[name="LoginForm[phone]"]","7071111111"                                                                                                                           
  I fill field "input[name="LoginForm[password]"]","123456"                                                                                                                            
  I click "#btnSignin"                                                                                                                                                                 
  [Uri] https://localhost/index-test.php/identity/login/                                                                                                                               
  [Method] POST                                                                                                                                                                        
  [Parameters] {"LoginForm":{"phone":"7071111111","password":"123456"},"keepSignin":"on"}                                                                                              
  [Headers] {"location":["https://localhost/index-test.php/partner/default/index/"],"content-type":["text/html; charset=UTF-8"]}                                                       
  [Response] 200                                                                                                                                                                       
  [Page] https://localhost/index-test.php/partner/default/index/                                                                                                                       
  [Cookies] []                                                                                                                                                                         
  [Headers] {"content-type":["text/html; charset=UTF-8"]}                                                                                                                              
* I am going to submit empty loyalty program                                                                                                                                           
* I am on page "partner/loyalty/index"                                                                                                                                                 
 ERROR                                                                                                                                                                                 
                                                                                                                                                                                       
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
Action index (\partner\LoyaltyCest::actionIndex)                                                                                                                                       
Scenario:                                                                                                                                                                              
* yii\codeception\BasePage: open by                                                                                                                                                    
  I am on page "/index-test.php/identity/login/"                                                                                                                                       
                                                                                                                                                                                       
  [Response] 200                                                                                                                                                                       
  [Page] https://localhost/index-test.php/identity/login/                                                                                                                              
  [Cookies] []                                                                                                                                                                         
  [Headers] {"content-type":["text/html; charset=UTF-8"]}                                                                                                                              
* tests\codeception\backend\pages\LoginPage: login as partner                                                                                                                          
  I fill field "input[name="LoginForm[phone]"]","7071111111"                                                                                                                           
  I fill field "input[name="LoginForm[password]"]","123456"                                                                                                                            
  I click "#btnSignin"                                                                                                                                                                 
  [Uri] https://localhost/index-test.php/identity/login/                                                                                                                               
  [Method] POST                                                                                                                                                                        
  [Parameters] {"LoginForm":{"phone":"7071111111","password":"123456"},"keepSignin":"on"}                                                                                              
  [Headers] {"location":["https://localhost/index-test.php/partner/default/index/"],"content-type":["text/html; charset=UTF-8"]}                                                       
  [Response] 200                                                                                                                                                                       
  [Page] https://localhost/index-test.php/partner/default/index/                                                                                                                       
  [Cookies] []                                                                                                                                                                         
  [Headers] {"content-type":["text/html; charset=UTF-8"]}                                                                                                                              
* I am going to test all members list                                                                                                                                                  
* I am on page "partner/member/index"                                                                                                                                                  
  [Response] 200                                                                                                                                                                       
  [Page] https://localhost/index-test.php/partner/member/index/                                                                                                                        
  [Cookies] []                                                                                                                                                                         
  [Headers] {"content-type":["text/html; charset=UTF-8"]}                                                                                                                              
 PASSED                                                                                                                                                                                
                                                                                                                                                                                       
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                 
----------------------------------------------------------------------------------------------------------------------------------------------------------------------                 
                                                                                                                                                                                       
                                                                                                                                                                                       
Time: 11.46 seconds, Memory: 27.75Mb                                                                                                                                                   
                                                                                                                                                                                       
There was 1 error:                                                                                                                                                                     
                                                                                                                                                                                       
---------                                                                                                                                                                              
1) Failed to action construct in tests\codeception\backend\partner\LoyaltyCest::actionConstruct (.\functional\partner/LoyaltyCest.php)                                                 
                                                                                                                                                                                       
                                                                                                                                                                                       
  [yii\base\ErrorException] Trying to get property of non-object                                                                                                                       
                                                                                                                                                                                       
                                                                                                                                                                                       
Scenario Steps:                                                                                                                                                                        
                                                                                                                                                                                       
 6. $I->amOnPage("partner/loyalty/index") at functional\partner\LoyaltyCest.php:24                                                                                                     
 5. // I am going to submit empty loyalty program                                                                                                                                      
 4. $I->click("#btnSignin") at _pages\LoginPage.php:23                                                                                                                                 
 3. $I->fillField("input[name="LoginForm[password]"]","123456") at _pages\LoginPage.php:22                                                                                             
 2. $I->fillField("input[name="LoginForm[phone]"]","7071111111") at _pages\LoginPage.php:21                                                                                            
 1. $I->amOnPage("/index-test.php/identity/login/") at ption\BasePage.php:77                                                                                                           
                                                                                                                                                                                       
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\backend\modules\partner\views\loyalty\index.php:30                                                                      
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\View.php:325                                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\View.php:247                                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\View.php:149                                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\Controller.php:371                                                                             
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\backend\modules\partner\controllers\LoyaltyController.php:58                                                            
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\InlineAction.php:55                                                                            
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\InlineAction.php:55                                                                            
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\Controller.php:151                                                                             
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\base\Module.php:455                                                                                 
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\yiisoft\yii2\web\Application.php:84                                                                              
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Lib\Connector\Yii2.php:87                                                
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\browser-kit\Client.php:317                                                                               
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Lib\InnerBrowser.php:105                                                 
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Module\Yii2.php:240                                                      
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Step.php:187                                                             
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Step.php:187                                                             
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\TestCase\Shared\Actor.php:96                                             
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Scenario.php:101                                                         
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\tests\codeception\backend\_support\_generated\FunctionalTesterActions.php:486                                           
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\tests\codeception\backend\functional\partner\LoyaltyCest.php:24                                                         
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Lib\Di.php:112                                                           
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Lib\Di.php:112                                                           
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\TestCase\Cest.php:131                                                    
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\TestCase\Cest.php:140                                                    
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\TestCase\Cest.php:68                                                     
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestCase.php:881                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestCase.php:881                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestCase.php:746                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestResult.php:601                                                                 
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestCase.php:702                                                                   
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\phpunit\phpunit\src\Framework\TestSuite.php:738                                                                  
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\PHPUnit\Runner.php:89                                                    
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\SuiteManager.php:149                                                     
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Codecept.php:200                                                         
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Codecept.php:172                                                         
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\src\Codeception\Command\Run.php:184                                                      
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Command\Command.php:259                                                                          
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php:841                                                                              
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php:192                                                                              
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\symfony\console\Application.php:123                                                                              
C:\Users\Alimzhan\Documents\OpenServer\domains\paydacard.local\vendor\codeception\codeception\codecept:28                                                                              
                                                                                                                                                                                       
                                                                                                                                                                                       
FAILURES!                                                                                                                                                                              
Tests: 2, Assertions: 0, Errors: 1.                                                                                                                                                    
```

**Comment by Naktibalda** [comment]
It looks like an error in \paydacard.local\backend\modules\partner\views\loyalty\index.php:30  to me.

**Comment by Nemmo** [comment]
@Naktibalda Oops, you are right! My bad, I have seen to the ```1. $I->amOnPage("/index-test.php/identity/login/") at ption\BasePage.php:77  ``` line. Sorry, everything is OK, that was my bad code..
