### ISSUE TITLE
Unable to collect coverage on 2.2.0RC

### ISSUE THREAD

**Issue by stevewest** [Codeception/Codeception#2997]
It is currently not possible to collect code coverage on `2.2.0-RC`, I've tested this locally too and any of the coverage options fail with the same message, info on our failing builds is below.

https://travis-ci.org/fuelphp/foundation/builds/123706138

```
$ vendor/bin/codecept run unit --coverage-xml
Codeception PHP Testing Framework v2.2.0-RC
Powered by PHPUnit 5.4-ged59ed9 by Sebastian Bergmann and contributors.
PHP Fatal error:  Uncaught Error: Class 'PHP_CodeCoverage' not found in /home/travis/build/fuelphp/foundation/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/Printer.php:36
Stack trace:
#0 /home/travis/build/fuelphp/foundation/vendor/codeception/codeception/src/Codeception/Codecept.php(156): Codeception\Coverage\Subscriber\Printer->__construct(Array)
#1 /home/travis/build/fuelphp/foundation/vendor/codeception/codeception/src/Codeception/Codecept.php(79): Codeception\Codecept->registerSubscribers()
#2 /home/travis/build/fuelphp/foundation/vendor/codeception/codeception/src/Codeception/Command/Run.php(185): Codeception\Codecept->__construct(Array)
#3 /home/travis/build/fuelphp/foundation/vendor/symfony/console/Command/Command.php(256): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /home/travis/build/fuelphp/foundation/vendor/symfony/console/Application.php(791): Symfony\Component\Console\Command\Command->run(Object in /home/travis/build/fuelphp/foundation/vendor/codeception/codeception/src/Codeception/Coverage/Subscriber/Printer.php on line 36
```

**Comment by Naktibalda** [comment]
Your problem could be that you are using the master branch of phpunit, it has dependency on php-code-coverage 4.0 which is not released yet.

**Comment by stevewest** [comment]
Thanks!
