### ISSUE TITLE
The ModuleConfig class doesn't exist in version 2.1 and up

### ISSUE THREAD

**Issue by TFarla** [Codeception/Codeception#3729]
#### What are you trying to achieve?
I want to test my Lumen application.
The ModuleConfig class has been renamed to ModuleConfigException since  Codeception 2.1.

#### What do you get instead?

> Provide console output if related. Use `-vvv` mode for more details.

```bash
vendor/bin/codecept run

FATAL ERROR. TESTS NOT FINISHED.
Uncaught Error: Class 'Codeception\Exception\ModuleConfig' not found in /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Module/Lumen.php:154
Stack trace:
#0 /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Module/Lumen.php(108): Codeception\Module\Lumen->checkBootstrapFileExists()
#1 /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/SuiteManager.php(81): Codeception\Module\Lumen->_initialize()
#2 /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Codecept.php(207): Codeception\SuiteManager->initialize()
#3 /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Codecept.php(178): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#4 /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Command/Run.php(359): Codeception\Codecept->run('functional')
#5 /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Comma
in /home/vagrant/Code/sms-campaigns/vendor/codeception/codeception/src/Codeception/Module/Lumen.php:154
```
> Provide test source code if related

### Details

* Codeception version: 2.2.6
* PHP Version: 7.0.8-2+deb.sury.org~xenial+1
* Operating System: Ubuntu 16.04 LTS (GNU/Linux 4.4.0-22-generic x86_64)
* Installation type: Composer
* List of installed packages (`composer show`)
```
behat/gherkin                      v4.4.5  Gherkin DSL parser for PHP 5.3
codeception/codeception            2.2.6   BDD-style testing framework
doctrine/inflector                 v1.1.0  Common String Manipulations with regard t...
doctrine/instantiator              1.0.5   A small, lightweight utility to instantia...
facebook/webdriver                 1.2.0   A PHP client for WebDriver
fzaninotto/faker                   v1.6.0  Faker is a PHP library that generates fak...
guzzlehttp/guzzle                  6.2.2   Guzzle is a PHP HTTP client library
guzzlehttp/promises                1.2.0   Guzzle promises library
guzzlehttp/psr7                    1.3.1   PSR-7 message implementation
illuminate/auth                    v5.3.16 The Illuminate Auth package.
illuminate/broadcasting            v5.3.16 The Illuminate Broadcasting package.
illuminate/bus                     v5.3.16 The Illuminate Bus package.
illuminate/cache                   v5.3.16 The Illuminate Cache package.
illuminate/config                  v5.3.16 The Illuminate Config package.
illuminate/console                 v5.3.16 The Illuminate Console package.
illuminate/container               v5.3.16 The Illuminate Container package.
illuminate/contracts               v5.3.16 The Illuminate Contracts package.
illuminate/database                v5.3.16 The Illuminate Database package.
illuminate/encryption              v5.3.16 The Illuminate Encryption package.
illuminate/events                  v5.3.16 The Illuminate Events package.
illuminate/filesystem              v5.3.16 The Illuminate Filesystem package.
illuminate/hashing                 v5.3.16 The Illuminate Hashing package.
illuminate/http                    v5.3.16 The Illuminate Http package.
illuminate/pagination              v5.3.16 The Illuminate Pagination package.
illuminate/pipeline                v5.3.16 The Illuminate Pipeline package.
illuminate/queue                   v5.3.16 The Illuminate Queue package.
illuminate/session                 v5.3.16 The Illuminate Session package.
illuminate/support                 v5.3.16 The Illuminate Support package.
illuminate/translation             v5.3.16 The Illuminate Translation package.
illuminate/validation              v5.3.16 The Illuminate Validation package.
illuminate/view                    v5.3.16 The Illuminate View package.
laravel/lumen-framework            v5.3.2  The Laravel Lumen Framework.
league/factory-muffin              v3.0.1  The goal of this package is to enable the...
league/factory-muffin-faker        v2.0.0  The goal of this package is to wrap faker...
monolog/monolog                    1.21.0  Sends your logs to files, sockets, inboxe...
mtdowling/cron-expression          v1.1.0  CRON for PHP: Calculate the next or previ...
myclabs/deep-copy                  1.5.5   Create deep copies (clones) of your objects
nesbot/carbon                      1.21.0  A simple API extension for DateTime.
nikic/fast-route                   v1.0.1  Fast request router for PHP
paragonie/random_compat            v2.0.4  PHP 5.x polyfill for random_bytes() and r...
phpdocumentor/reflection-common    1.0     Common reflection classes used by phpdocu...
phpdocumentor/reflection-docblock  3.1.1   With this component, a library can provid...
phpdocumentor/type-resolver        0.2
phpspec/prophecy                   v1.6.1  Highly opinionated mocking framework for ...
phpunit/php-code-coverage          4.0.2   Library that provides collection, process...
phpunit/php-file-iterator          1.4.1   FilterIterator implementation that filter...
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  1.0.8   Utility class for timing
phpunit/php-token-stream           1.4.8   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.6.2   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.0   Mock Object library for PHPUnit
psr/http-message                   1.0.1   Common interface for HTTP messages
psr/log                            1.0.2   Common interface for logging libraries
ramsey/uuid                        3.5.1   Formerly rhumsaa/uuid. A PHP 5.4+ library...
sebastian/code-unit-reverse-lookup 1.0.0   Looks up which function or method a line ...
sebastian/comparator               1.2.0   Provides the functionality to compare PHP...
sebastian/diff                     1.4.1   Diff implementation
sebastian/environment              1.3.8   Provides functionality to handle HHVM/PHP...
sebastian/exporter                 1.2.2   Provides the functionality to export PHP ...
sebastian/global-state             1.1.1   Snapshotting of global state
sebastian/object-enumerator        1.0.0   Traverses array structures and object gra...
sebastian/recursion-context        1.0.2   Provides functionality to recursively pro...
sebastian/resource-operations      1.0.0   Provides a list of PHP built-in functions...
sebastian/version                  2.0.0   Library that helps with managing the vers...
symfony/browser-kit                v3.1.6  Symfony BrowserKit Component
symfony/console                    v3.1.6  Symfony Console Component
symfony/css-selector               v3.1.6  Symfony CssSelector Component
symfony/debug                      v3.1.6  Symfony Debug Component
symfony/dom-crawler                v3.1.6  Symfony DomCrawler Component
symfony/event-dispatcher           v3.1.6  Symfony EventDispatcher Component
symfony/finder                     v3.1.6  Symfony Finder Component
symfony/http-foundation            v3.1.6  Symfony HttpFoundation Component
symfony/http-kernel                v3.1.6  Symfony HttpKernel Component
symfony/polyfill-mbstring          v1.2.0  Symfony polyfill for the Mbstring extension
symfony/process                    v3.1.6  Symfony Process Component
symfony/translation                v3.1.6  Symfony Translation Component
symfony/yaml                       v3.1.6  Symfony Yaml Component
vlucas/phpdotenv                   v2.4.0  Loads environment variables from `.env` t...
webmozart/assert                   1.1.0   Assertions to validate method input/outpu...
```
* Suite configuration:

```yml
# Codeception Test Suite Configuration
#
# Suite for functional (integration) tests
# Emulate web requests and make application process them
# Include one of framework modules (Symfony2, Yii2, Laravel5) to use it

class_name: FunctionalTester
modules:
    enabled:
        - Lumen:
            url: http://test.dev
        - \Helper\Functional
```

**Comment by Naktibalda** [comment]
@TFarla if you haven't figure it out yet, you got that error, because your `bootstrap_file` setting is pointing to non-existing file.

**Comment by janhenkgerritsen** [comment]
@Naktibalda You are right that he can fix the error by specifying a correct bootstrap file, but what he is saying is that the exception class should be `Codeception\Exception\ModuleConfigException` instead of `Codeception\Exception\ModuleConfig`.

**Comment by Naktibalda** [comment]
Why is it taking so long to fix it?

**Comment by janhenkgerritsen** [comment]
@Naktibalda because I am currently working on other things.

**Comment by janhenkgerritsen** [comment]
@TFarla thanks for reporting this issue!
