### ISSUE TITLE
Acceptance and web service tests won't work on Elementary OS

### ISSUE THREAD

**Issue by meseguer1998** [Codeception/Codeception#3758]
#### What are you trying to achieve?

Running an acceptance test

#### What do you get instead?

A fatal error

> Provide console output if related. Use `-vvv` mode for more details.

```bash
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

Acceptance Tests (1) ---------------------------------------------------------------
- CreateProjectCept: Perform actions and see resultPHP Fatal error:  Uncaught Error: Call to undefined function Codeception\Module\mb_strcut() in phar:///opt/lampp/htdocs/pg/codecept.phar/src/Codeception/Module/WebDriver.php:360
Stack trace:
#0 phar:///opt/lampp/htdocs/pg/codecept.phar/src/Codeception/Subscriber/Module.php(78): Codeception\Module\WebDriver->_failed(Object(Codeception\Test\Cept), Object(PHPUnit_Framework_AssertionFailedError))
#1 [internal function]: Codeception\Subscriber\Module->failed(Object(Codeception\Event\FailEvent), 'test.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 phar:///opt/lampp/htdocs/pg/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Codeception\Event\FailEvent), 'test.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 phar:///opt/lampp/htdocs/pg/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.error', Object(Codeception\Event\FailEvent))
#4 phar:///opt/la in phar:///opt/lampp/htdocs/pg/codecept.phar/src/Codeception/Module/WebDriver.php on line 360



FATAL ERROR. TESTS NOT FINISHED.
Uncaught Error: Call to undefined function Codeception\Module\mb_strcut() in phar:///opt/lampp/htdocs/pg/codecept.phar/src/Codeception/Module/WebDriver.php:360
Stack trace:
#0 phar:///opt/lampp/htdocs/pg/codecept.phar/src/Codeception/Subscriber/Module.php(78): Codeception\Module\WebDriver->_failed(Object(Codeception\Test\Cept), Object(PHPUnit_Framework_AssertionFailedError))
#1 [internal function]: Codeception\Subscriber\Module->failed(Object(Codeception\Event\FailEvent), 'test.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 phar:///opt/lampp/htdocs/pg/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php(174): call_user_func(Array, Object(Codeception\Event\FailEvent), 'test.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 phar:///opt/lampp/htdocs/pg/codecept.phar/vendor/symfony/event-dispatcher/EventDispatcher.php(43): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.error', Object(Codeception\Event\FailEvent))
#4 phar:///opt/la 
in phar:///opt/lampp/htdocs/pg/codecept.phar/src/Codeception/Module/WebDriver.php:360

# paste output here
```
> Provide test source code if related

```php
// paste test
`<?php 
$I = new AcceptanceTester($scenario);
$I->wantTo('perform actions and see result');
`
```
### Details

* Codeception version: 2.2.6 
* PHP Version: 5.6
* Operating System: Elementary OS
* Installation type: Phar 
* List of installed packages (`composer show`)
* Suite configuration: actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    support: tests/_support
    envs: tests/_envs
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
extensions:
    enabled:
        - Codeception\Extension\RunFailed
modules:
    config:
        Db:
            dsn: ''
            user: ''
            password: ''
            dump: tests/_data/dump.sql

```yml
# paste suite config here
class_name: AcceptanceTester
modules:
    enabled:
        - WebDriver:
            url: 
            browser: firefox            
        - \Helper\Acceptance
```

**NOTE: I can run this same test on Ubuntu, but for some reason it throws me that error on Elementary OS.

**Comment by Naktibalda** [comment]
You have to install mbstring extension for PHP.

**Comment by meseguer1998** [comment]
@Naktibalda Thank you, sir! :+1:
