### ISSUE TITLE
Actor class loaded twice. Cannot redeclare class

### ISSUE THREAD

**Issue by andriykonoz** [Codeception/Codeception#3763]
#### What are you trying to achieve?
I try to run unit-tests suite
#### What do you get instead?
Get error caused by re-declaration of `rest\tests\UnitTester` 
> Provide console output if related. Use `-vvv` mode for more details.

```bash
CategoryTest: ValidationPHP Fatal error:  Cannot redeclare class rest\tests\UnitTester in /data/rest/tests/_support/UnitTester.php on line 23
PHP Stack trace:
PHP   1. {main}() /data/vendor/codeception/codeception/codecept:0
PHP   2. Codeception\Application->run() /data/vendor/codeception/codeception/codecept:33
PHP   3. Symfony\Component\Console\Application->run() /data/vendor/codeception/codeception/src/Codeception/Application.php:103
PHP   4. Symfony\Component\Console\Application->doRun() /data/vendor/symfony/console/Application.php:118
PHP   5. Symfony\Component\Console\Application->doRunCommand() /data/vendor/symfony/console/Application.php:187
PHP   6. Symfony\Component\Console\Command\Command->run() /data/vendor/symfony/console/Application.php:820
PHP   7. Codeception\Command\Run->execute() /data/vendor/symfony/console/Command/Command.php:256
PHP   8. Codeception\Command\Run->runSuites() /data/vendor/codeception/codeception/src/Codeception/Command/Run.php:286
PHP   9. Codeception\Codecept->run() /data/vendor/codeception/codeception/src/Codeception/Command/Run.php:359
PHP  10. Codeception\Codecept->runSuite() /data/vendor/codeception/codeception/src/Codeception/Codecept.php:178
PHP  11. Codeception\SuiteManager->run() /data/vendor/codeception/codeception/src/Codeception/Codecept.php:209
PHP  12. Codeception\PHPUnit\Runner->doEnhancedRun() /data/vendor/codeception/codeception/src/Codeception/SuiteManager.php:162
PHP  13. PHPUnit_Framework_TestSuite->run() /data/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php:98
PHP  14. PHPUnit_Framework_TestCase->run() /data/vendor/phpunit/phpunit/src/Framework/TestSuite.php:753
PHP  15. PHPUnit_Framework_TestResult->run() /data/vendor/phpunit/phpunit/src/Framework/TestCase.php:909
PHP  16. PHPUnit_Framework_TestCase->runBare() /data/vendor/phpunit/phpunit/src/Framework/TestResult.php:701
PHP  17. rest\tests\unit\models\CategoryTest->setUp() /data/vendor/phpunit/phpunit/src/Framework/TestCase.php:950
PHP  18. Codeception\Test\Unit->setUp() /data/rest/tests/unit/models/CategoryTest.php:29
PHP  19. spl_autoload_call() /data/rest/tests/unit/models/CategoryTest.php:45
PHP  20. Codeception\Util\Autoload::load() /data/rest/tests/unit/models/CategoryTest.php:45
PHP  21. Codeception\Util\Autoload::load() /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php:113
PHP  22. Codeception\Util\Autoload::loadMappedFile() /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php:102
PHP  23. Codeception\Util\Autoload::requireFile() /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php:148
PHP  24. require() /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php:159
<pre>PHP Compile Error &#039;yii\base\ErrorException&#039; with message &#039;Cannot redeclare class rest\tests\UnitTester&#039; 

in /data/rest/tests/_support/UnitTester.php:23

Stack trace:
#0 /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php(148): Codeception\Util\Autoload::requireFile()
#1 /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php(102): Codeception\Util\Autoload::loadMappedFile()
#2 /data/vendor/codeception/codeception/src/Codeception/Util/Autoload.php(113): Codeception\Util\Autoload::load()
#3 /data/rest/tests/unit/models/CategoryTest.php(45): Codeception\Util\Autoload::load()
#4 /data/rest/tests/unit/models/CategoryTest.php(45): ::spl_autoload_call()
#5 /data/rest/tests/unit/models/CategoryTest.php(29): Codeception\Test\Unit-&gt;setUp()
#6 /data/vendor/phpunit/phpunit/src/Framework/TestCase.php(950): rest\tests\unit\models\CategoryTest-&gt;setUp()
#7 /data/vendor/phpunit/phpunit/src/Framework/TestResult.php(701): PHPUnit_Framework_TestCase-&gt;runBare()
#8 /data/vendor/phpunit/phpunit/src/Framework/TestCase.php(909): PHPUnit_Framework_TestResult-&gt;run()
#9 /data/vendor/phpunit/phpunit/src/Framework/TestSuite.php(753): PHPUnit_Framework_TestCase-&gt;run()
#10 /data/vendor/codeception/codeception/src/Codeception/PHPUnit/Runner.php(98): PHPUnit_Framework_TestSuite-&gt;run()
#11 /data/vendor/codeception/codeception/src/Codeception/SuiteManager.php(162): Codeception\PHPUnit\Runner-&gt;doEnhancedRun()
#12 /data/vendor/codeception/codeception/src/Codeception/Codecept.php(209): Codeception\SuiteManager-&gt;run()
#13 /data/vendor/codeception/codeception/src/Codeception/Codecept.php(178): Codeception\Codecept-&gt;runSuite()
#14 /data/vendor/codeception/codeception/src/Codeception/Command/Run.php(359): Codeception\Codecept-&gt;run()
#15 /data/vendor/codeception/codeception/src/Codeception/Command/Run.php(286): Codeception\Command\Run-&gt;runSuites()
#16 /data/vendor/symfony/console/Command/Command.php(256): Codeception\Command\Run-&gt;execute()
#17 /data/vendor/symfony/console/Application.php(820): Symfony\Component\Console\Command\Command-&gt;run()
#18 /data/vendor/symfony/console/Application.php(187): Symfony\Component\Console\Application-&gt;doRunCommand()
#19 /data/vendor/symfony/console/Application.php(118): Symfony\Component\Console\Application-&gt;doRun()
#20 /data/vendor/codeception/codeception/src/Codeception/Application.php(103): Symfony\Component\Console\Application-&gt;run()
#21 /data/vendor/codeception/codeception/codecept(33): Codeception\Application-&gt;run()

```
> Provide test source code if related

```php
<?php
namespace rest\tests\unit\models;

use rest\modules\category\models\Category;
use rest\tests\UnitTester;

class CategoryTest extends \Codeception\Test\Unit
{
    /**
     * @var UnitTester
     */
    protected $tester;

    // executed before each test
    protected function _before()
    {
    }

    // executed after each test
    protected function _after()
    {
    }


    public function testValidation()
    {
        $model = new Category();
        self::assertFalse($model->validate());
    }
}

```
### Details

* Codeception version: 2.2.6
* PHP Version: 5.6.28-1+deb.sury.org~xenial+1
* Operating System: Ubuntu 14.04
* Installation type: Composer
* List of installed packages (`composer show`)
```bash
behat/gherkin                         v4.4.5             Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap                 3.3.7.0            
bower-asset/jquery                    2.2.4.0            
bower-asset/jquery.inputmask          3.2.7.0            
bower-asset/punycode                  1.3.2.0            
bower-asset/typeahead.js              0.11.1.0           
bower-asset/yii2-pjax                 2.0.6.0            
cebe/markdown                         1.1.1              A super fast, highly extensible markdown parser for PHP
codeception/codeception               2.2.6              BDD-style testing framework
codeception/specify                   0.4.5              BDD code blocks for PHPUnit and Codeception
codeception/verify                    0.3.2              BDD assertion library for PHPUnit
codemix/yii2-localeurls               1.4.5              Automatic locale/language management for URLs.
doctrine/instantiator                 1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
ezyang/htmlpurifier                   v4.8.0             Standards compliant HTML filter written in PHP
facebook/webdriver                    1.2.0              A PHP client for WebDriver
fzaninotto/faker                      v1.6.0             Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                     6.2.2              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   1.2.0              Guzzle promises library
guzzlehttp/psr7                       1.3.1              PSR-7 message implementation
imagine/imagine                       v0.6.3             Image processing for PHP 5.3
lcobucci/jwt                          3.2.1              A simple library to work with JSON Web Token and JSON Web Signature
myclabs/deep-copy                     1.5.5              Create deep copies (clones) of your objects
nicolab/php-ftp-client                v1.3.0             A flexible FTP and SSL-FTP client for PHP. This lib provides helpers easy to use to manage the remote files.
ongr/elasticsearch-dsl                v2.2.0             Elasticsearch DSL library
php-amqplib/php-amqplib               v2.6.3             Formerly videlalvaro/php-amqplib.  This library is a pure PHP implementation of the AMQP protocol. It's been tested against RabbitMQ.
phpdocumentor/reflection-common       1.0                Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock     3.1.1              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver           0.2                
phpspec/php-diff                      v1.1.0             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                      v1.6.1             Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage             4.0.2              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator             1.4.1              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     1.0.8              Utility class for timing
phpunit/php-token-stream              1.4.9              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       5.6.3              The PHP Unit Testing framework.
phpunit/phpunit-mock-objects          3.4.0              Mock Object library for PHPUnit
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.0.2              Common interface for logging libraries
sebastian/code-unit-reverse-lookup    1.0.0              Looks up which function or method a line of code belongs to
sebastian/comparator                  1.2.1              Provides the functionality to compare PHP values for equality
sebastian/diff                        1.4.1              Diff implementation
sebastian/environment                 1.3.8              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                    1.2.2              Provides the functionality to export PHP variables for visualization
sebastian/global-state                1.1.1              Snapshotting of global state
sebastian/object-enumerator           1.0.1              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context           1.0.4              Provides functionality to recursively process PHP variables
sebastian/resource-operations         1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                     2.0.0              Library that helps with managing the version number of Git-hosted PHP projects
squizlabs/php_codesniffer             2.7.0              PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
swiftmailer/swiftmailer               v5.4.3             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v3.1.6             Symfony BrowserKit Component
symfony/console                       v3.1.6             Symfony Console Component
symfony/css-selector                  v3.1.6             Symfony CssSelector Component
symfony/debug                         v3.1.6             Symfony Debug Component
symfony/dom-crawler                   v3.1.6             Symfony DomCrawler Component
symfony/event-dispatcher              v3.1.6             Symfony EventDispatcher Component
symfony/finder                        v3.1.6             Symfony Finder Component
symfony/polyfill-mbstring             v1.3.0             Symfony polyfill for the Mbstring extension
symfony/serializer                    v3.1.6             Symfony Serializer Component
symfony/yaml                          v3.1.6             Symfony Yaml Component
twig/twig                             v1.27.0            Twig, the flexible, fast, and secure template language for PHP
webmozart/assert                      1.1.0              Assertions to validate method input/output with nice error messages.
yiisoft/yii2                          2.0.10             Yii PHP Framework Version 2
yiisoft/yii2-bootstrap                2.0.6              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer                 2.0.4              The composer plugin for Yii extension installer
yiisoft/yii2-debug                    2.0.6              The debugger extension for the Yii framework
yiisoft/yii2-elasticsearch            2.0.4              Elasticsearch integration and ActiveRecord for the Yii framework
yiisoft/yii2-faker                    2.0.3              Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                      2.0.5              The Gii extension for the Yii framework
yiisoft/yii2-httpclient               2.0.2              HTTP client extension for the Yii framework
yiisoft/yii2-imagine                  2.1.0              The Imagine integration for the Yii framework
yiisoft/yii2-mongodb                  2.1.2              MongoDb extension for the Yii framework
yiisoft/yii2-redis                    2.0.5              Redis Cache, Session and ActiveRecord for the Yii framework
yiisoft/yii2-swiftmailer              2.0.6              The SwiftMailer integration for the Yii framework

```
* Suite configuration:

```yml
class_name: UnitTester
modules:
    enabled:
        - Yii2
        - Asserts
```

**Comment by andriykonoz** [comment]
Maybe it would be helpful. I located places where class is loaded for first and for second time.
First time Codeception load Actor in `Codeception\Test\Loader\Gherkin` during adding steps to loader.
Second time it initialize `Actor` instance for class with tests. In second place this class must be already included, but again loader is triggered. Here error appear.

**Comment by DavertMik** [comment]
Thanks @andriykonoz I will try to look on it

**Comment by andriykonoz** [comment]
@DavertMik , I found a reason of this problem. My `codeception.yml` for this tests missing namespace param when classes in test folder was under namespace. This caused my problem. 
Sorry for wasting your time.

**Comment by DavertMik** [comment]
Ok, good to hear you fixed that. Probably we should have better config handling for this but I don't know how )
