### ISSUE TITLE
what is this mean ? what i do ?

### ISSUE THREAD

**Issue by nurafin** [Codeception/Codeception#4353]
```
Fatal error: Uncaught exception 'Doctrine\Common\Annotations\AnnotationException' with message '[Semantical Error] The annotation "@Symfony\Component\Validator\Constraints\NotBlank" in property Chamilo\CoreBundle\Entity\Course::$title does not exist, or could not be auto-loaded.' in C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php:54
Stack trace:
#0 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(708): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...') 
#1 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(641): Doctrine\Common\Annotations\DocParser->Annotation()
#2 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\DocParser.php(334): Doctrine\Common\Annotations\DocParser->Annotations()
#3 C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationReader.php(226): Do in C:\xampp\htdocs\chamilo\vendor\doctrine\annotations\lib\Doctrine\Common\Annotations\AnnotationException.php on line 54
```

**Comment by Naktibalda** [comment]
It has nothing to do with Codeception.

I found a relevant Symfony issue: https://github.com/symfony/symfony/issues/1402
