### ISSUE TITLE
Problem testing REST API using Codeception\Module\Yii2 in a yii2-app-advanced template via Vagrant

### ISSUE THREAD

**Issue by leoshtika** [Codeception/Codeception#4475]
#### What are you trying to achieve?
Test an REST API application using Codeception\Module\Yii2 in a yii2-app-advanced template via Vagrant

#### What do you get instead?
The API is working fine (viewed from my host machine: `http://localhost:4006/api/v1/activities`), but all api tests are failing because of **404 error**
The api application was created following @samdark [guide](https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/topic-adding-more-apps.md).

Here is the tree of the application

![101](https://user-images.githubusercontent.com/1560028/29871796-caf1585c-8d95-11e7-9348-72cc79c30699.png)

> codecept run -vvv inside vagrant

```bash
vagrant@vagrant-ubuntu-trusty-64:/vagrant/api$ codecept run -vvv
Codeception PHP Testing Framework v2.3.3
Powered by PHPUnit 6.2.1 by Sebastian Bergmann and contributors.

  Rebuilding ApiTester...

Api\tests.api Tests (1) ----------------------------------------------------------------------------------
Modules: REST, Yii2, \api\tests\Helper\Api
----------------------------------------------------
ActivityCest: Check activities unauthorized
Signature: api\tests\ActivityCest:checkActivitiesUnauthorized
Test: tests/api/ActivityCest.php:checkActivitiesUnauthorized
Scenario --
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=192.168.0.100;dbname=yii2_test'
 I send get "/activities"
  [Request] GET /api/v1/activities
  [Request Headers] []
  [yii\web\HttpException:404] 'yii\\web\\NotFoundHttpException: Page not found. in /vagrant/vendor/yiisoft/yii2/web/Request.php:195
  Stack trace:
  #0 /vagrant/vendor/yiisoft/yii2/web/Application.php(82): yii\\web\\Request->resolve()
  #1 /vagrant/vendor/codeception/base/src/Codeception/Lib/Connector/Yii2.php(143): yii\\web\\Application->handleRequest(Object(yii\\web\\Request))
  #2 /vagrant/vendor/symfony/browser-kit/Client.php(315): Codeception\\Lib\\Connector\\Yii2->doRequest(Object(Symfony\\Component\\BrowserKit\\Request))
  #3 /vagrant/vendor/codeception/base/src/Codeception/Lib/InnerBrowser.php(191): Symfony\\Component\\BrowserKit\\Client->request(\'GET\', \'http://localhos...\', Array, Array, Array, NULL, true)
  #4 /vagrant/vendor/codeception/base/src/Codeception/Module/Yii2.php(519): Codeception\\Lib\\InnerBrowser->clientRequest(\'GET\', \'/api/v1/activit...\', Array, Array, Array, NULL, true)
  #5 /vagrant/vendor/codeception/base/src/Codeception/Lib/InnerBrowser.php(123): Codeception\\Module\\Yii2->clientRequest(\'GET\', \'/api/v1/activit...\', Array, Array, Array, NULL, true)
  #6 /vagrant/vendor/codeception/base/src/Codeception/Module/REST.php(512): Codeception\\Lib\\InnerBrowser->_request(\'GET\', \'/api/v1/activit...\', Array, Array)
  #7 /vagrant/vendor/codeception/base/src/Codeception/Module/REST.php(377): Codeception\\Module\\REST->execute(\'GET\', \'/api/v1/activit...\', Array)
  #8 [internal function]: Codeception\\Module\\REST->sendGET(\'/activities\')
  #9 /vagrant/vendor/codeception/base/src/Codeception/Step.php(260): call_user_func_array(Array, Array)
  #10 /vagrant/vendor/codeception/base/src/Codeception/Scenario.php(72): Codeception\\Step->run(Object(Codeception\\Lib\\ModuleContainer))
  #11 /vagrant/api/tests/_support/_generated/ApiTesterActions.php(330): Codeception\\Scenario->runStep(Object(Codeception\\Step\\Action))
  #12 /vagrant/api/tests/api/ActivityCest.php(18): api\\tests\\ApiTester->sendGET(\'/activities\')
  #13 [internal function]: api\\tests\\ActivityCest->checkActivitiesUnauthorized(Object(api\\tests\\ApiTester))
  #14 /vagrant/vendor/codeception/base/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(api\\tests\\ActivityCest), Array)
  #15 /vagrant/vendor/codeception/base/src/Codeception/Test/Cest.php(136): Codeception\\Lib\\Di->injectDependencies(Object(api\\tests\\ActivityCest), \'checkActivities...\', Array)
  #16 /vagrant/vendor/codeception/base/src/Codeception/Test/Cest.php(148): Codeception\\Test\\Cest->invoke(\'checkActivities...\', Array)
  #17 /vagrant/vendor/codeception/base/src/Codeception/Test/Cest.php(82): Codeception\\Test\\Cest->executeTestMethod(Object(api\\tests\\ApiTester))
  #18 /vagrant/vendor/codeception/base/src/Codeception/Test/Test.php(87): Codeception\\Test\\Cest->test()
  #19 /vagrant/vendor/phpunit/phpunit/src/Framework/TestSuite.php(746): Codeception\\Test\\Test->run(Object(PHPUnit\\Framework\\TestResult))
  #20 /vagrant/vendor/codeception/base/src/Codeception/PHPUnit/Runner.php(106): PHPUnit\\Framework\\TestSuite->run(Object(PHPUnit\\Framework\\TestResult))
  #21 /vagrant/vendor/codeception/base/src/Codeception/SuiteManager.php(157): Codeception\\PHPUnit\\Runner->doEnhancedRun(Object(Codeception\\Suite), Object(PHPUnit\\Framework\\TestResult), Array)
  #22 /vagrant/vendor/codeception/base/src/Codeception/Codecept.php(184): Codeception\\SuiteManager->run(Object(Codeception\\PHPUnit\\Runner), Object(PHPUnit\\Framework\\TestResult), Array)
  #23 /vagrant/vendor/codeception/base/src/Codeception/Codecept.php(153): Codeception\\Codecept->runSuite(Array, \'api\', NULL)
  #24 /vagrant/vendor/codeception/base/src/Codeception/Command/Run.php(380): Codeception\\Codecept->run(\'api\')
  #25 /vagrant/vendor/codeception/base/src/Codeception/Command/Run.php(307): Codeception\\Command\\Run->runSuites(Array, Array)
  #26 /vagrant/vendor/symfony/console/Command/Command.php(264): Codeception\\Command\\Run->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #27 /vagrant/vendor/symfony/console/Application.php(869): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #28 /vagrant/vendor/symfony/console/Application.php(223): Symfony\\Component\\Console\\Application->doRunCommand(Object(Codeception\\Command\\Run), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #29 /vagrant/vendor/symfony/console/Application.php(130): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #30 /vagrant/vendor/codeception/base/src/Codeception/Application.php(103): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
  #31 /vagrant/vendor/codeception/base/codecept(36): Codeception\\Application->run()
  #32 {main}'
  [Page] /api/v1/activities
  [Response] 404
  [Request Cookies] []
  [Response Headers] {"content-type":["text/html; charset=UTF-8"]}
  [Response] <pre>Not Found: Page not found.</pre>
 I see response code is 401
 FAIL 

---------------------------------------------------------------------

Api\tests.unit Tests (0) ----------------------------------------
Modules: Yii2, Asserts
---------------------------------------------------------------------


Time: 375 ms, Memory: 12.00MB

There was 1 failure:

---------
1) ActivityCest: Check activities unauthorized
 Test  tests/api/ActivityCest.php:checkActivitiesUnauthorized
 Step  See response code is 401
 Fail  Expected HTTP Status Code: 401 (Unauthorized). Actual Status Code: 404 (Not Found)
Failed asserting that 404 matches expected 401.

Scenario Steps:

 2. $I->seeResponseCodeIs(401) at tests/api/ActivityCest.php:19
 1. $I->sendGET("/activities") at tests/api/ActivityCest.php:18

/vagrant/vendor/phpunit/phpunit/src/Framework/Assert.php:2116
/vagrant/vendor/phpunit/phpunit/src/Framework/Assert.php:541
/vagrant/vendor/codeception/base/src/Codeception/Util/Shared/Asserts.php:37
/vagrant/vendor/codeception/base/src/Codeception/Lib/InnerBrowser.php:1479
/vagrant/vendor/codeception/base/src/Codeception/Module/REST.php:1056
/vagrant/vendor/codeception/base/src/Codeception/Step.php:260
/vagrant/vendor/codeception/base/src/Codeception/Scenario.php:72
/vagrant/api/tests/_support/_generated/ApiTesterActions.php:1189
/vagrant/api/tests/api/ActivityCest.php:19
/vagrant/vendor/codeception/base/src/Codeception/Lib/Di.php:127
/vagrant/vendor/codeception/base/src/Codeception/Test/Cest.php:136
/vagrant/vendor/codeception/base/src/Codeception/Test/Cest.php:148
/vagrant/vendor/codeception/base/src/Codeception/Test/Cest.php:82
/vagrant/vendor/codeception/base/src/Codeception/Test/Test.php:87
/vagrant/vendor/phpunit/phpunit/src/Framework/TestSuite.php:746
/vagrant/vendor/codeception/base/src/Codeception/PHPUnit/Runner.php:106
/vagrant/vendor/codeception/base/src/Codeception/SuiteManager.php:157
/vagrant/vendor/codeception/base/src/Codeception/Codecept.php:184
/vagrant/vendor/codeception/base/src/Codeception/Codecept.php:153
/vagrant/vendor/codeception/base/src/Codeception/Command/Run.php:380
/vagrant/vendor/codeception/base/src/Codeception/Command/Run.php:307
/vagrant/vendor/symfony/console/Command/Command.php:264
/vagrant/vendor/symfony/console/Application.php:869
/vagrant/vendor/symfony/console/Application.php:223
/vagrant/vendor/symfony/console/Application.php:130
/vagrant/vendor/codeception/base/src/Codeception/Application.php:103
/vagrant/vendor/codeception/base/codecept:36


FAILURES!
Tests: 1, Assertions: 1, Failures: 1.

```
### Details

* Codeception version: **2.3.3**
* PHP Version: **7.0**
* Operating System: **Linux Ubuntu in both Host and Vagrant client**
* Installation type: **Composer**

```yml
# api/codeception.yml
namespace: api\tests
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    colors: true
    memory_limit: 1024M
modules:
    config:
        Yii2:
            configFile: 'config/test-local.php'
```
```yml
# api/tests/api.suite.yml
actor: ApiTester
modules:
    enabled:
        - REST:
            url: /api/v1
            depends: Yii2
            part: Json
        - \api\tests\Helper\Api
    config:
        - Yii2
```
```php
// api/config/main.php
<?php
$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-api',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'api\controllers',
    'modules' => [
        'v1' => [
            'basePath' => '@app/modules/v1',
            'class' => 'api\modules\v1\Module'
        ],
    ],
    'components' => [
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => false,
            'enableSession' => false,
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'request' => [
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ]
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => true,
            'showScriptName' => false,
            'rules' => [
                [
                    'class' => 'yii\rest\UrlRule',
                    'controller' => ['v1/activity'],
                    'extraPatterns' => [
                        'OPTIONS update' => 'options',
                        'POST update' => 'update',
                    ]
                ],
            ],
        ],
    ],
    'params' => $params,
];

```

```php
<?php
// api/config/test.php
return [
    'id' => 'app-api-tests',
];

```

Here is a simple tests
```php
<?php
namespace api\tests;
use api\tests\ApiTester;

class ActivityCest
{
    public function checkActivitiesUnauthorized(ApiTester $I)
    {
        $I->sendGET('/activities');
        $I->seeResponseCodeIs(401); // Unauthorized
    }
}
```

**Comment by samdark** [comment]
Could be general Vagrant thing.

**Comment by leoshtika** [comment]
@samdark thank you for your quick reply. 
I don't think that it is a Vagrant thing, because all the other tests (functional & unit) are running fine via Vagrant.

**Comment by leoshtika** [comment]
I just solved it. 
The problem was in the api application structure. I was not using the **web** folder. Now I moved index.php and index-test.php files in the web folder and worked like a charm.
