### ISSUE TITLE
Helper with same name in difference namespace

### ISSUE THREAD

**Issue by bscheshirwork** [Codeception/Codeception#4613]
#### What are you trying to achieve?
I add new helper to config.
I want use it both. 

I expect
generated Actor with namespaced functions from helper or some like this

#### What do you get instead?
`php-code/frontend/tests/_support/_generated/FunctionalTesterActions.php`
```php
<?php  //[STAMP] 186b16697d20cb45a0348f1079910c22
namespace frontend\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use Codeception\Module\Filesystem;
use bscheshirwork\Codeception\Module\DbYii2Config;
use Codeception\Module\Yii2;
use Codeception\Module\Asserts;
use common\tests\Helper\Functional;
use frontend\tests\Helper\Functional;

trait FunctionalTesterActions
{
...
```

php compilation error

> Provide console output if related. Use `-vvv` mode for more details.

```bash
root@abcae3432889:/var/www/html# codecept build

Included Configuration: common
Building Actor classes for suites: acceptance, functional, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
common\tests\AcceptanceTester includes modules: 
 -> FunctionalTesterActions.php generated successfully. 0 methods added
common\tests\FunctionalTester includes modules: 
 -> UnitTesterActions.php generated successfully. 0 methods added
common\tests\UnitTester includes modules: Yii2

Included Configuration: frontend
Building Actor classes for suites: acceptance, functional, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
frontend\tests\AcceptanceTester includes modules: WebDriver, \bscheshirwork\Codeception\Module\DbYii2Config, Yii2, Asserts, common\tests\Helper\Acceptance
 -> FunctionalTesterActions.php generated successfully. 0 methods added
frontend\tests\FunctionalTester includes modules: Filesystem, \bscheshirwork\Codeception\Module\DbYii2Config, Yii2, Asserts, common\tests\Helper\Functional, frontend\tests\Helper\Functional
 -> UnitTesterActions.php generated successfully. 0 methods added
frontend\tests\UnitTester includes modules: Yii2, Asserts

Included Configuration: backend
Building Actor classes for suites: acceptance, functional, unit
 -> AcceptanceTesterActions.php generated successfully. 0 methods added
backend\tests\AcceptanceTester includes modules: WebDriver, \bscheshirwork\Codeception\Module\DbYii2Config, Yii2, common\tests\Helper\Acceptance
 -> FunctionalTesterActions.php generated successfully. 0 methods added
backend\tests\FunctionalTester includes modules: \bscheshirwork\Codeception\Module\DbYii2Config, Yii2, common\tests\Helper\Functional
 -> UnitTesterActions.php generated successfully. 0 methods added
backend\tests\UnitTester includes modules: 
root@abcae3432889:/var/www/html# codecept run -c frontend/codeception.yml functional ContactFailCest -d
Codeception PHP Testing Framework v2.3.6
Powered by PHPUnit 6.2.4 by Sebastian Bergmann and contributors.

  [Db] Connected to yii2advanced
  [yii\base\ErrorException:64] unserialize('O:23:"yii\\base\\ErrorException":8:{s:10:"' . "\0" . '*' . "\0" . 'message";s:92:"Cannot use frontend\\tests\\Helper\\Functional as Functional because the name is already in use";s:17:"' . "\0" . 'Exception' . "\0" . 'string";s:0:"";s:7:"' . "\0" . '*' . "\0" . 'code";i:64;s:7:"' . "\0" . '*' . "\0" . 'file";s:76:"/var/www/html/frontend/tests/_support/_generated/FunctionalTesterActions.php";s:7:"' . "\0" . '*' . "\0" . 'line";i:13;s:16:"' . "\0" . 'Exception' . "\0" . 'trace";a:22:{i:0;a:7:{s:8:"function";s:14:"loadMappedFile";s:4:"type";s:2:"::";s:5:"class";s:25:"Codeception\\Util\\Autoload";s:4:"file";s:39:"/repo/src/Codeception/Util/Autoload.php";s:4:"line";i:102;s:6:"params";a:2:{s:6:"prefix";s:3:"???";s:14:"relative_class";s:3:"???";}s:4:"args";a:2:{s:6:"prefix";s:3:"???";s:14:"relative_class";s:3:"???";}}i:1;a:7:{s:8:"function";s:4:"load";s:4:"type";s:2:"::";s:5:"class";s:25:"Codeception\\Util\\Autoload";s:4:"file";s:58:"/var/www/html/frontend/tests/_support/FunctionalTester.php";s:4:"line";i:21;s:6:"params";a:1:{s:5:"class";s:3:"???";}s:4:"args";a:1:{s:5:"class";s:3:"???";}}i:2;a:6:{s:8:"function";s:17:"spl_autoload_call";s:4:"file";s:58:"/var/www/html/frontend/tests/_support/FunctionalTester.php";s:4:"line";i:21;s:6:"params";a:1:{i:4294967295;s:3:"???";}s:4:"type";s:2:"::";s:4:"args";a:1:{i:4294967295;s:3:"???";}}i:3;a:8:{s:4:"type";s:2:"->";s:5:"class";s:25:"Codeception\\Util\\Autoload";s:4:"file";s:39:"/repo/src/Codeception/Util/Autoload.php";s:4:"line";i:159;s:6:"params";a:0:{}s:16:"include_filename";s:58:"/var/www/html/frontend/tests/_support/FunctionalTester.php";s:8:"function";s:7:"unknown";s:4:"args";a:0:{}}i:4;a:7:{s:8:"function";s:11:"requireFile";s:4:"type";s:2:"::";s:5:"class";s:25:"Codeception\\Util\\Autoload";s:4:"file";s:39:"/repo/src/Codeception/Util/Autoload.php";s:4:"line";i:148;s:6:"params";a:1:{s:4:"file";s:3:"???";}s:4:"args";a:1:{s:4:"file";s:3:"???";}}i:5;a:7:{s:8:"function";s:14:"loadMappedFile";s:4:"type";s:2:"::";s:5:"class";s:25:"Codeception\\Util\\Autoload";s:4:"file";s:39:"/repo/src/Codeception/Util/Autoload.php";s:4:"line";i:102;s:6:"params";a:2:{s:6:"prefix";s:3:"???";s:14:"relative_class";s:3:"???";}s:4:"args";a:2:{s:6:"prefix";s:3:"???";s:14:"relative_class";s:3:"???";}}i:6;a:7:{s:8:"function";s:4:"load";s:4:"type";s:2:"::";s:5:"class";s:25:"Codeception\\Util\\Autoload";s:4:"file";s:45:"/repo/src/Codeception/Test/Loader/Gherkin.php";s:4:"line";i:85;s:6:"params";a:1:{s:5:"class";s:3:"???";}s:4:"args";a:1:{s:5:"class";s:3:"???";}}i:7;a:6:{s:8:"function";s:17:"spl_autoload_call";s:4:"file";s:45:"/repo/src/Codeception/Test/Loader/Gherkin.php";s:4:"line";i:85;s:6:"params";a:1:{i:4294967295;s:3:"???";}s:4:"type";s:2:"::";s:4:"args";a:1:{i:4294967295;s:3:"???";}}i:8;a:6:{s:8:"function";s:17:"get_class_methods";s:4:"file";s:45:"/repo/src/Codeception/Test/Loader/Gherkin.php";s:4:"line";i:85;s:6:"params";a:1:{i:4294967295;s:3:"???";}s:4:"type";s:2:"::";s:4:"args";a:1:{i:4294967295;s:3:"???";}}i:9;a:7:{s:8:"function";s:8:"addSteps";s:4:"type";s:2:"->";s:5:"class";s:31:"Codeception\\Test\\Loader\\Gherkin";s:4:"file";s:45:"/repo/src/Codeception/Test/Loader/Gherkin.php";s:4:"line";i:78;s:6:"params";a:2:{s:8:"contexts";s:3:"???";s:5:"group";s:3:"???";}s:4:"args";a:2:{s:8:"contexts";s:3:"???";s:5:"group";s:3:"???";}}i:10;a:7:{s:8:"function";s:17:"fetchGherkinSteps";s:4:"type";s:2:"->";s:5:"class";s:31:"Codeception\\Test\\Loader\\Gherkin";s:4:"file";s:45:"/repo/src/Codeception/Test/Loader/Gherkin.php";s:4:"line";i:55;s:6:"params";a:0:{}s:4:"args";a:0:{}}i:11;a:7:{s:8:"function";s:11:"__construct";s:4:"type";s:2:"->";s:5:"class";s:31:"Codeception\\Test\\Loader\\Gherkin";s:4:"file";s:37:"/repo/src/Codeception/Test/Loader.php";s:4:"line";i:54;s:6:"params";a:1:{s:8:"settings";s:3:"???";}s:4:"args";a:1:{s:8:"settings";s:3:"???";}}i:12;a:7:{s:8:"function";s:11:"__construct";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Test\\Loader";s:4:"file";s:38:"/repo/src/Codeception/SuiteManager.php";s:4:"line";i:94;s:6:"params";a:1:{s:13:"suiteSettings";s:3:"???";}s:4:"args";a:1:{s:13:"suiteSettings";s:3:"???";}}i:13;a:7:{s:8:"function";s:9:"loadTests";s:4:"type";s:2:"->";s:5:"class";s:24:"Codeception\\SuiteManager";s:4:"file";s:34:"/repo/src/Codeception/Codecept.php";s:4:"line";i:187;s:6:"params";a:1:{s:4:"path";s:3:"???";}s:4:"args";a:1:{s:4:"path";s:3:"???";}}i:14;a:7:{s:8:"function";s:8:"runSuite";s:4:"type";s:2:"->";s:5:"class";s:20:"Codeception\\Codecept";s:4:"file";s:34:"/repo/src/Codeception/Codecept.php";s:4:"line";i:157;s:6:"params";a:3:{s:8:"settings";s:3:"???";s:5:"suite";s:3:"???";s:4:"test";s:3:"???";}s:4:"args";a:3:{s:8:"settings";s:3:"???";s:5:"suite";s:3:"???";s:4:"test";s:3:"???";}}i:15;a:7:{s:8:"function";s:3:"run";s:4:"type";s:2:"->";s:5:"class";s:20:"Codeception\\Codecept";s:4:"file";s:37:"/repo/src/Codeception/Command/Run.php";s:4:"line";i:341;s:6:"params";a:3:{s:5:"suite";s:3:"???";s:4:"test";s:3:"???";s:6:"config";s:3:"???";}s:4:"args";a:3:{s:5:"suite";s:3:"???";s:4:"test";s:3:"???";s:6:"config";s:3:"???";}}i:16;a:7:{s:8:"function";s:7:"execute";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Command\\Run";s:4:"file";s:48:"/repo/vendor/symfony/console/Command/Command.php";s:4:"line";i:262;s:6:"params";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}s:4:"args";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}}i:17;a:7:{s:8:"function";s:3:"run";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Command\\Run";s:4:"file";s:44:"/repo/vendor/symfony/console/Application.php";s:4:"line";i:888;s:6:"params";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}s:4:"args";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}}i:18;a:7:{s:8:"function";s:12:"doRunCommand";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Application";s:4:"file";s:44:"/repo/vendor/symfony/console/Application.php";s:4:"line";i:224;s:6:"params";a:3:{s:7:"command";s:3:"???";s:5:"input";s:3:"???";s:6:"output";s:3:"???";}s:4:"args";a:3:{s:7:"command";s:3:"???";s:5:"input";s:3:"???";s:6:"output";s:3:"???";}}i:19;a:7:{s:8:"function";s:5:"doRun";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Application";s:4:"file";s:44:"/repo/vendor/symfony/console/Application.php";s:4:"line";i:125;s:6:"params";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}s:4:"args";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}}i:20;a:7:{s:8:"function";s:3:"run";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Application";s:4:"file";s:37:"/repo/src/Codeception/Application.php";s:4:"line";i:103;s:6:"params";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}s:4:"args";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}}i:21;a:7:{s:8:"function";s:3:"run";s:4:"type";s:2:"->";s:5:"class";s:23:"Codeception\\Application";s:4:"file";s:14:"/repo/codecept";s:4:"line";i:36;s:6:"params";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}s:4:"args";a:2:{s:5:"input";s:3:"???";s:6:"output";s:3:"???";}}}s:19:"' . "\0" . 'Exception' . "\0" . 'previous";N;s:11:"' . "\0" . '*' . "\0" . 'severity";i:64;}')
<pre>PHP Compile Error &#039;yii\base\ErrorException&#039; with message &#039;Cannot use frontend\tests\Helper\Functional as Functional because the name is already in use&#039; 

in /var/www/html/frontend/tests/_support/_generated/FunctionalTesterActions.php:13

Stack trace:
#0 /repo/src/Codeception/Util/Autoload.php(102): Codeception\Util\Autoload::loadMappedFile(&#039;???&#039;, &#039;???&#039;)
#1 /var/www/html/frontend/tests/_support/FunctionalTester.php(21): Codeception\Util\Autoload::load(&#039;???&#039;)
#2 /var/www/html/frontend/tests/_support/FunctionalTester.php(21): ::spl_autoload_call(&#039;???&#039;)
#3 /repo/src/Codeception/Util/Autoload.php(159): Codeception\Util\Autoload-&gt;unknown()
#4 /repo/src/Codeception/Util/Autoload.php(148): Codeception\Util\Autoload::requireFile(&#039;???&#039;)
#5 /repo/src/Codeception/Util/Autoload.php(102): Codeception\Util\Autoload::loadMappedFile(&#039;???&#039;, &#039;???&#039;)
#6 /repo/src/Codeception/Test/Loader/Gherkin.php(85): Codeception\Util\Autoload::load(&#039;???&#039;)
#7 /repo/src/Codeception/Test/Loader/Gherkin.php(85): ::spl_autoload_call(&#039;???&#039;)
#8 /repo/src/Codeception/Test/Loader/Gherkin.php(85): ::get_class_methods(&#039;???&#039;)
#9 /repo/src/Codeception/Test/Loader/Gherkin.php(78): Codeception\Test\Loader\Gherkin-&gt;addSteps(&#039;???&#039;, &#039;???&#039;)
#10 /repo/src/Codeception/Test/Loader/Gherkin.php(55): Codeception\Test\Loader\Gherkin-&gt;fetchGherkinSteps()
#11 /repo/src/Codeception/Test/Loader.php(54): Codeception\Test\Loader\Gherkin-&gt;__construct(&#039;???&#039;)
#12 /repo/src/Codeception/SuiteManager.php(94): Codeception\Test\Loader-&gt;__construct(&#039;???&#039;)
#13 /repo/src/Codeception/Codecept.php(187): Codeception\SuiteManager-&gt;loadTests(&#039;???&#039;)
#14 /repo/src/Codeception/Codecept.php(157): Codeception\Codecept-&gt;runSuite(&#039;???&#039;, &#039;???&#039;, &#039;???&#039;)
#15 /repo/src/Codeception/Command/Run.php(341): Codeception\Codecept-&gt;run(&#039;???&#039;, &#039;???&#039;, &#039;???&#039;)
#16 /repo/vendor/symfony/console/Command/Command.php(262): Codeception\Command\Run-&gt;execute(&#039;???&#039;, &#039;???&#039;)
#17 /repo/vendor/symfony/console/Application.php(888): Codeception\Command\Run-&gt;run(&#039;???&#039;, &#039;???&#039;)
#18 /repo/vendor/symfony/console/Application.php(224): Codeception\Application-&gt;doRunCommand(&#039;???&#039;, &#039;???&#039;, &#039;???&#039;)
#19 /repo/vendor/symfony/console/Application.php(125): Codeception\Application-&gt;doRun(&#039;???&#039;, &#039;???&#039;)
#20 /repo/src/Codeception/Application.php(103): Codeception\Application-&gt;run(&#039;???&#039;, &#039;???&#039;)
#21 /repo/codecept(36): Codeception\Application-&gt;run(&#039;???&#039;, &#039;???&#039;)
#22 {main}</pre>root@abcae3432889:/var/www/html# 

```
### Details

* Codeception version:  https://github.com/Codeception/Codeception/commit/c6e90017eb216ee0a0d03143db6a1a0d0cd5a759
* PHP Version:7.1.11
* Operating System:debian
* Installation type: Composer in docker [docker-compose.yml](https://github.com/bscheshirwork/docker-yii2-app-advanced-rbac/blob/master/docker-codeception-run/docker-compose.yml)
* List of installed packages (`composer show`)
* Suite configuration:

`php-code/frontend/tests/functional.suite.yml` see last string
```yml
class_name: FunctionalTester
modules:
    enabled:
        - Filesystem
        - \bscheshirwork\Codeception\Module\DbYii2Config:
            dump: ../common/tests/_data/dump.sql #relative path from "codeception.yml"
            populate: true
            cleanup: true
        - Yii2
        - Asserts
        - common\tests\Helper\Functional
        - frontend\tests\Helper\Functional
```

**Comment by bscheshirwork** [comment]
Why do we need "use" at all? 

My IDE don't find any usage in file for all of this... All of PHPdoc contain full path

**Comment by bscheshirwork** [comment]
https://github.com/Codeception/Codeception/blob/c6e90017eb216ee0a0d03143db6a1a0d0cd5a759/src/Codeception/Lib/Generator/Actions.php#L73-L76

**Comment by bscheshirwork** [comment]
So... I prepare PR

don't see evil :cake:
