### ISSUE TITLE
codeception functional tests: Class SebastianBergmann\Timer\Timer not found

### ISSUE THREAD

**Issue by macklus** [Codeception/Codeception#4872]
#### What are you trying to achieve?

Run functional tests from Yii Framework

#### What do you get instead?

Error:
```
- LoginCest: Ensure that login works<pre>Exception &#039;Error&#039; with message &#039;Class &#039;SebastianBergmann\Timer\Timer&#039; not found&#039; 

in framework/vendor/codeception/base/src/Codeception/Test/Test.php:87

Stack trace:
#0 framework/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): Codeception\Test\Test-&gt;run(Object(PHPUnit\Framework\TestResult))
#1 framework/vendor/codeception/phpunit-wrapper/src/Runner.php(106): PHPUnit\Framework\TestSuite-&gt;run(Object(PHPUnit\Framework\TestResult))
#2 framework/vendor/codeception/base/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner-&gt;doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#3 framework/vendor/codeception/base/src/Codeception/Codecept.php(189): Codeception\SuiteManager-&gt;run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#4 framework/vendor/codeception/base/src/Codeception/Codecept.php(158): Codeception\Codecept-&gt;runSuite(Array, &#039;acceptance&#039;, NULL)
#5 framework/vendor/codeception/base/src/Codeception/Command/Run.php(466): Codeception\Codecept-&gt;run(&#039;acceptance&#039;)
#6 framework/vendor/codeception/base/src/Codeception/Command/Run.php(361): Codeception\Command\Run-&gt;runSuites(Array, Array)
#7 framework/vendor/symfony/console/Command/Command.php(252): Codeception\Command\Run-&gt;execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 framework/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 framework/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application-&gt;doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 framework/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application-&gt;doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 framework/vendor/codeception/base/src/Codeception/Application.php(108): Symfony\Component\Console\Application-&gt;run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 framework/vendor/codeception/codeception/package/bin(36): Codeception\Application-&gt;run()
#13 framework/vendor/codeception/base/autoload.php(12): require(&#039;/home/erp/web/e...&#039;)
#14 framework/vendor/codeception/base/codecept(7): require_once(&#039;/home/erp/web/e...&#039;)
#15 {main}</pre>PHP Fatal error:  Uncaught RuntimeException: Command Did Not Finish Properly in framework/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php:101
Stack trace:
#0 [internal function]: Codeception\Subscriber\ErrorHandler->shutdownHandler()
#1 {main}
  thrown in framework/vendor/codeception/base/src/Codeception/Subscriber/ErrorHandler.php on line 101
```

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# paste output here
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: 2.4.0
* PHP Version: 7.2.3
* Operating System: CentOS Linux release 7.4.1708 (Core)
* Installation type: Phar || Composer composer
* List of installed packages (`composer show`)
```
ass/xmlsecurity                     v1.1.1              The XmlSecurity library is written in PHP for working with XML Encryption and Signatures
behat/gherkin                       dev-master e66888c  Gherkin DSL parser for PHP 5.3
besimple/soap-client                0.2.x-dev 50f186f   Build and consume SOAP Client based web services
besimple/soap-common                0.2.x-dev 08aa78c   Build and consume SOAP Common based web services
bower-asset/bootstrap               v3.3.7              The most popular front-end framework for developing responsive, mobile first projects on the web.
bower-asset/bootstrap3-dialog       v1.35.4             Make use of Bootstrap Modal more monkey-friendly. http://nakupanda.github.io/bootstrap3-dialog/
bower-asset/datatables              dev-master 6733264 
bower-asset/datatables-bootstrap3   dev-master 45802ec  Plugin for Datatables Bootstrap3 UI Compatibility
bower-asset/datatables-tabletools   dev-master 45b5b56 
bower-asset/inputmask               3.3.11              Inputmask is a javascript library which creates an input mask.  Inputmask can run against vanilla javascript, jQuery and jqlite.
bower-asset/jquery                  3.2.1              
bower-asset/jquery-ui               1.12.1             
bower-asset/punycode                v1.3.2             
bower-asset/typeahead.js            v0.11.1            
bower-asset/yii2-pjax               dev-master c39f239 
c006/yii2-paypal-ipn                v1.0.0              This is a simple PayPal IPN listener, no other files required.
cebe/markdown                       dev-master af7bae1  A super fast, highly extensible markdown parser for PHP
codeception/base                    2.4.x-dev b8f173d   BDD-style testing framework
codeception/codeception             dev-master 326449b  BDD-style testing framework
codeception/phpunit-wrapper         6.0.x-dev 7481881   PHPUnit classes used by Codeception
codeception/specify                 0.4.6               BDD code blocks for PHPUnit and Codeception
codeception/stub                    1.0.2               Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                  0.3.3               BDD assertion library for PHPUnit
codeonyii/yii2-at-least-validator   dev-master 1de020a  Validates at least one (or more) attributes.
components/jquery                   1.12.x-dev 5dd7297  jQuery JavaScript Library
components/underscore               1.8.3               JavaScript's functional programming helper library.
container-interop/container-interop 1.2.0               Promoting the interoperability of container objects (DIC, SL, etc.)
creocoder/yii2-flysystem            dev-master 9f8d01f  The flysystem extension for the Yii framework
dantart/yii2-mailqueue              dev-master b10811c  Email queue component for yii2 that works with yii2-swiftmailer.
datatables/datatables               1.10.16             DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon the foundations of progressive enhancement, which will add advan...
dektrium/yii2-user                  0.9.13              Flexible user registration and authentication module for Yii2
denisogr/yii2-cronjobs              dev-master 95ba91e  cronjobs
digitv/kint                         dev-master 83d283c  Add kint support
doctrine/instantiator               dev-master 870a62d  A small, lightweight utility to instantiate objects in PHP without invoking their constructors
ezyang/htmlpurifier                 v4.10.0             Standards compliant HTML filter written in PHP
fabpot/goutte                       dev-master 395f61d  A simple PHP Web Scraper
facebook/webdriver                  1.5.x-dev bc08cfa   A PHP client for Selenium WebDriver
fedemotta/yii2-widget-datatables    dev-master 0fc4fe0  DataTables widget for Yii2
fzaninotto/faker                    dev-master 5dce115  Faker is a PHP library that generates fake data for you.
guzzlehttp/guzzle                   dev-master ba1bce3  Guzzle is a PHP HTTP client library
guzzlehttp/promises                 dev-master 0940c91  Guzzle promises library
guzzlehttp/psr7                     dev-master 649e354  PSR-7 message implementation that also provides common utility methods
h4cc/wkhtmltopdf-amd64              0.12.4              Convert html to pdf using webkit (qtwebkit). Static linked linux binary for amd64 systems.
intervention/httpauth               2.0.3               HTTP authentication (Basic & Digest) including ServiceProviders for easy Laravel integration
kartik-v/bootstrap-fileinput        dev-master 440e67a  An enhanced HTML 5 file input for Bootstrap 3.x with features for file preview for many file types, multiple selection, ajax uploads, and more.
kartik-v/bootstrap-popover-x        dev-master 2a809af  Bootstrap Popover Extended - Popover with modal behavior, styling enhancements and more.
kartik-v/bootstrap-star-rating      dev-master 19120d9  A simple yet powerful JQuery star rating plugin for Bootstrap.
kartik-v/dependent-dropdown         dev-master 1349e7f  A multi level dependent dropdown JQuery plugin that allows nested dependencies.
kartik-v/yii2-date-range            dev-master 70fd959  An advanced Yii 2 date range picker input for based on bootstrap-daterangepicker plugin.
kartik-v/yii2-dialog                dev-master f75a411  An asset bundle for bootstrap3-dialog for Yii 2.0 framework.
kartik-v/yii2-dynagrid              dev-master 109b96e  Turbo charge the Yii 2 GridView with personalized columns, page size, and themes.
kartik-v/yii2-editable              dev-master e07d786  An enhanced editable widget for Yii 2.0 that allows easy editing of displayed data with numerous configuration possibilities.
kartik-v/yii2-grid                  dev-master d52f509  Yii 2 GridView on steroids. Various enhancements and utilities for the Yii 2.0 GridView widget.
kartik-v/yii2-krajee-base           dev-master 2f38bde  Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-money                 dev-master e783ca6  An advanced money mask input for Yii 2.0 based on jquery maskmoney plugin styled for Bootstrap 3.
kartik-v/yii2-popover-x             v1.3.4              An extended bootstrap 3.0 popover widget which combines both the bootstrap popover and modal features and includes various new styling enhancements.
kartik-v/yii2-sortable              v1.2.0              Create sortable lists and grids using HTML5 drag and drop API for Yii 2.0.
kartik-v/yii2-widget-activeform     dev-master 578de8c  Enhanced Yii2 active-form and active-field with full bootstrap styling support (sub repo split from yii2-widgets).
kartik-v/yii2-widget-affix          dev-master 7f3266b  A scrollspy and affixed enhanced navigation to highlight page sections (sub repo split from yii2-widgets)
kartik-v/yii2-widget-alert          dev-master 604670a  A widget to generate alert based notifications using bootstrap-alert plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-colorinput     dev-master 86a6eba  An enhanced Yii 2 widget encapsulating the HTML 5 color input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-datepicker     dev-master eb7e829  Enhanced Yii2 wrapper for the bootstrap datepicker plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-datetimepicker dev-master 36f8327  Enhanced Yii2 wrapper for the bootstrap datetimepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-depdrop        dev-master aacc064  Widget that enables setting up dependent dropdowns with nested dependencies (sub repo split from yii2-widgets)
kartik-v/yii2-widget-fileinput      dev-master c549564  An enhanced FileInput widget for Bootstrap 3.x with file preview, multiple selection, and more features (sub repo split from yii2-widgets)
kartik-v/yii2-widget-growl          dev-master c79abaa  A widget to generate growl based notifications using bootstrap-growl plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rangeinput     dev-master 78f03bc  An enhanced Yii 2 widget encapsulating the HTML 5 range input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rating         dev-master 5d02266  A Yii2 widget for the simple yet powerful bootstrap-star-rating plugin with fractional rating support (sub repo split from yii2-widgets)
kartik-v/yii2-widget-select2        dev-master d08a5b3  Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-sidenav        dev-master 54186e7  An enhanced side navigation menu styled for bootstrap (sub repo split from yii2-widgets)
kartik-v/yii2-widget-spinner        dev-master ab8087f  A widget to render animated CSS3 loading spinners with VML fallback for IE (sub repo split from yii2-widgets)
kartik-v/yii2-widget-switchinput    dev-master 10afe2a  A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle switchinputes (sub repo split from yii2-widgets)
kartik-v/yii2-widget-timepicker     dev-master d8d12fa  Enhanced Yii2 wrapper for the bootstrap timepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-touchspin      dev-master ba819f8  A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle touchspines (sub repo split from yii2-widgets)
kartik-v/yii2-widget-typeahead      dev-master 5b459d9  Enhanced Yii2 wrapper for the Twitter Typeahead plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widgets               3.4.0.x-dev f435d5e Collection of useful widgets for Yii Framework 2.0 extending functionalities for Bootstrap
kint-php/kint                       2.2                 Kint - debugging tool for PHP developers
kriswallsmith/assetic               dev-master e911c43  Asset Management for PHP
league/flysystem                    dev-master 1ce7cc1  Filesystem abstraction: Many filesystems, one API.
league/flysystem-replicate-adapter  dev-master 864e804  Flysystem adapter for Replica's
macklus/yii2-freshdesk              1.0.0               Simple Yii2 module to extend Freshdesk API
macklus/yii2-geoselect              dev-master 0b67dec  Ajax widget to display country, province and location selects
macklus/yii2-holded                 1.0.5               Yii Framework extension for https://www.holded.com
macklus/yii2-payments               1.0.3               Simple payment environment for Yii2. It includes Transfer, Paypal and Credit Card systems
miradnan/yii2-bootstrap-calendar    dev-master 3c41cad  Enhanced Yii2 wrapper for the Bootstrap Calendar
moment/moment                       2.21.0              Parse, validate, manipulate, and display dates in JavaScript.
monolog/monolog                     1.x-dev fd8c787     Sends your logs to files, sockets, inboxes, databases and various web services
mozarcik/yii-datepicker             1.4.1               Yii extension wrapper for bootstrap-datepicker
mpclarkson/freshdesk-php-sdk        dev-master 9247ef4  PHP SDK for the Freshdesk API (v2)
mrclay/jsmin-php                    2.3.2               Provides a modified port of Douglas Crockford's jsmin.c, which removes unnecessary whitespace from JavaScript files.
mrclay/minify                       dev-master 258e495  Minify is a PHP5 app that helps you follow several rules for client-side performance. It combines multiple CSS or Javascript files, removes unnecessary whitespace a...
mrclay/props-dic                    2.2.0               Props is a simple DI container that allows retrieving values via custom property and method names
myclabs/deep-copy                   1.x-dev 9f80720     Create deep copies (clones) of your objects
natxet/CssMin                       dev-master d5d9f4c  Minifying CSS
nineinchnick/edatatables            1.10.6              Grid widget for the Yii Framework, wrapper for the DataTables jQuery plugin
paragonie/random_compat             v2.0.11             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
perminder-klair/yii2-dropzone       dev-master 41e8145  DropzoneJs Extention for Yii2
phar-io/manifest                    dev-master 014fead  Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                     1.0.1               Library for handling version information and constraints
phpdocumentor/reflection-common     dev-master 8133918  Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock   dev-master 1826097  With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is embedded in a DocBlock.
phpdocumentor/type-resolver         dev-master 69bf1b1 
phpoffice/phpexcel                  1.8.x-dev c269793   PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpspec/php-diff                    dev-master 0464787  A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                    dev-master dfd6be4  Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage           5.3.x-dev 982ce79   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator           1.4.x-dev 730b01b   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template           1.2.1               Simple template engine.
phpunit/php-timer                   1.0.9               Utility class for timing
phpunit/php-token-stream            2.0.x-dev 13eb9ab   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                     6.2.x-dev ff3a76a   The PHP Unit Testing framework.
phpunit/phpunit-mock-objects        4.0.x-dev 11c3bde   Mock Object library for PHPUnit
pimple/pimple                       dev-master 9aaff1c  Pimple, a simple Dependency Injection Container
psr/container                       dev-master 2cc4a01  Common Container Interface (PHP FIG PSR-11)
psr/http-message                    dev-master f6561bf  Common interface for HTTP messages
psr/log                             dev-master 4ebe3a8  Common interface for logging libraries
ramsey/uuid                         dev-master 6262886  Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
robloach/component-installer        dev-master 4d8cb31  Allows installation of Components via Composer.
sebastian/code-unit-reverse-lookup  dev-master 3488be0  Looks up which function or method a line of code belongs to
sebastian/comparator                2.0.0               Provides the functionality to compare PHP values for equality
sebastian/diff                      1.4.x-dev 7f066a2   Diff implementation
sebastian/environment               dev-master 93ade88  Provides functionality to handle HHVM/PHP environments
sebastian/exporter                  dev-master 573f8b7  Provides the functionality to export PHP variables for visualization
sebastian/global-state              dev-master a27e666  Snapshotting of global state
sebastian/object-enumerator         dev-master a496797  Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector          dev-master ff75508  Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context         dev-master 0f7f5eb  Provides functionality to recursively process PHP variables
sebastian/resource-operations       dev-master fadc83f  Provides a list of PHP built-in functions that operate on resources
sebastian/version                   2.0.1               Library that helps with managing the version number of Git-hosted PHP projects
seostats/seostats                   dev-master bd3117f  SEOstats is a powerful open source PHP library to request a bunch of SEO relevant metrics for any website.
serhioromano/bootstrap-calendar     0.2.4               Bootstrap full view calendar.
skeeks/yii2-assets-auto-compress    dev-master 8d3df2f  Automatically compile and merge files js + css + html in yii2 project
squizlabs/php_codesniffer           dev-master 084fc69  PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
stecman/symfony-console-completion  0.7.0               Automatic BASH completion for Symfony Console Component based applications.
swiftmailer/swiftmailer             5.x-dev 7ffc1ea     Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                 3.4.x-dev 490f277   Symfony BrowserKit Component
symfony/console                     3.4.x-dev 067339e   Symfony Console Component
symfony/css-selector                3.4.x-dev 544655f   Symfony CssSelector Component
symfony/debug                       dev-master 2489851  Symfony Debug Component
symfony/dom-crawler                 3.4.x-dev 2bb5d31   Symfony DomCrawler Component
symfony/event-dispatcher            3.4.x-dev 5899068   Symfony EventDispatcher Component
symfony/finder                      3.4.x-dev a479817   Symfony Finder Component
symfony/polyfill-mbstring           dev-master 78be803  Symfony polyfill for the Mbstring extension
symfony/process                     3.4.x-dev cc4aea2   Symfony Process Component
symfony/yaml                        3.4.x-dev 6af4263   Symfony Yaml Component
tedivm/jshrink                      dev-master 68ce379  Javascript Minifier built in PHP
theseer/tokenizer                   1.1.0               A small library for converting tokenized PHP source code into XML and potentially other formats
tubalmartin/cssmin                  v4.1.1              A PHP port of the YUI CSS compressor
twbs/bootstrap                      dev-master 2c2ac33  The most popular front-end framework for developing responsive, mobile first projects on the web.
understeam/yii2-slack               v0.3.0              Yii2 slack client based on GuzzleHttp library
vladkukushkin/yii2-faq              dev-master c5179bd  Yii2 FAQ module
vlucas/phpdotenv                    dev-master 90b2f41  Loads environment variables from `.env` to `getenv()`, `$_ENV` and `$_SERVER` automagically.
vova07/yii2-imperavi-widget         dev-master 45eec82  The imperavi redactor widget for Yii 2 framework.
webmozart/assert                    dev-master 0df1908  Assertions to validate method input/output with nice error messages.
yii2tech/ar-softdelete              dev-master 9a5a741  Provides support for ActiveRecord soft delete in Yii2
yii2tech/html2pdf                   dev-master 997aaf2  Provides support for HTML to PDF and PHP to PDF conversion
yiisoft/yii2                        dev-master 9c1f8c5  Yii PHP Framework Version 2
yiisoft/yii2-authclient             2.1.5               External authentication via OAuth and OpenID for the Yii framework
yiisoft/yii2-bootstrap              dev-master 80f7a16  The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer               dev-master 248f706  The composer plugin for Yii extension installer
yiisoft/yii2-debug                  dev-master f49234b  The debugger extension for the Yii framework
yiisoft/yii2-faker                  dev-master 1cb3bb3  Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                    dev-master 20046a8  The Gii extension for the Yii framework
yiisoft/yii2-httpclient             dev-master 232d0ec  HTTP client extension for the Yii framework
yiisoft/yii2-jui                    dev-master 48b6746  The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer            2.0.7               The SwiftMailer integration for the Yii framework
```
* Suite configuration:

```yml
# Codeception Test Suite Configuration

# suite for functional (integration) tests.
# emulate web requests and make application process them.
# (tip: better to use with frameworks).

# RUN `build` COMMAND AFTER ADDING/REMOVING MODULES.
#basic/web/index.php
class_name: FunctionalTester
modules:
    enabled:
      - Filesystem
      - Yii2
```

**Comment by Naktibalda** [comment]
Why do you use so many dev dependencies?

You aren't using Codeception 2.4.0, but master branch instead `codeception/codeception             dev-master 326449b`
Also you are using 6.2 branch of phpunit - `phpunit/phpunit                     6.2.x-dev ff3a76a`

**Comment by macklus** [comment]
Hi!
This dependences are because i use Yii framework, wich send me here to report

Question here are: wich versions should i have to made It work?

**Comment by macklus** [comment]
Closing this.

After review all package versions, and ensure it works on "minimum-stability": "stable", everything works ok

thanks!
