### ISSUE TITLE
"Call to a member function getDb() on null" running tests with database 

### ISSUE THREAD

**Issue by vffkiva** [Codeception/Codeception#5064]
#### What are you trying to achieve?
Trying to run simple Unit test, asserting some test data from the database.

#### What do you get instead?
If the data not exist in the database, got an error: 
"PHP Fatal error:  Call to a member function getDb() on null in /var/www-gac2/vendor/yiisoft/yii2/db/ActiveRecord.php on line 135"

#### Reviewed issues
The following links/issues has been reviewed before, but did not help:
https://github.com/Codeception/Codeception/issues/3705
https://github.com/Codeception/Codeception/issues/4922
https://github.com/Codeception/Codeception/issues/4969
https://github.com/Codeception/Codeception/commit/b574ef21a011621dd57b6446a770255566204853#diff-94abe3ee46e86aa1477f9565b6d2f9f5

> Provide console output if related. Use `-vvv` mode for more details.

```bash
root@gac-stage:/var/www-gac2# vendor/bin/codecept run api v1/functional/DebugCest:test123 -vvv
Codeception PHP Testing Framework v2.4.3
Powered by PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Api Tests (1) ------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Modules: Yii2, REST, PhpBrowser, Asserts
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DebugCest: Test123
Signature: app\tests\api\v1\functional\DebugCest:test123
Test: tests/api/v1/functional/DebugCest.php:test123
Scenario --
  Destroying application
  Starting application
  [Fixtures] Loading fixtures
  [Fixtures] Done
  [yii\db\Connection::open] 'Opening DB connection: mysql:host=6eb8ea24df15492cfcc622cdb40f8662f036871b.rackspaceclouddb.com;dbname=getacopywriter_test'
 I assert not empty "app\\api\\modules\\v1\\models\\Client"
 I assert contains "Rembo1","Rembo"
 FAIL

  [Transaction] Rolling back 0 transactions
  Destroying application
  Suite done, restoring $_SERVER to original
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


Time: 538 ms, Memory: 18.00MB

There was 1 failure:

---------
1) DebugCest: Test123
 Test  tests/api/v1/functional/DebugCest.php:test123
 Step  Assert contains "Rembo1","Rembo"
 Fail  Failed asserting that 'Rembo' contains "Rembo1".

Scenario Steps:

 2. $I->assertContains("Rembo1","Rembo") at tests/api/v1/functional/DebugCest.php:17
PHP Fatal error:  Call to a member function getDb() on null in /var/www-gac2/vendor/yiisoft/yii2/db/ActiveRecord.php on line 135



FATAL ERROR. TESTS NOT FINISHED.
Call to a member function getDb() on null
in /var/www-gac2/vendor/yiisoft/yii2/db/ActiveRecord.php:135
PHP Fatal error:  Call to a member function has() on null in /var/www-gac2/vendor/yiisoft/yii2/web/ErrorHandler.php on line 91
```
> Provide test source code if related

```php
<?php
namespace app\tests\api\v1\functional;
use app\api\modules\v1\models\Client;

class DebugCest {
    public function _before(\ApiTester $I) {}

    public function _after(\ApiTester $I) {}

    public function test123(\ApiTester $I) {
    $client = Client::find()->where(['id' => 1])->one();
    $I->assertNotEmpty($client);
    $I->assertContains('Rembo1', $client->last_name); //Rembo1 is not exists in the database
    }
}
```
### Details

* Codeception version: 2.4.3
* PHP Version: 5.6.36
* Operating System: Ubuntu 14.04 (trusty)
* Installation type: Composer 
* List of installed packages (`composer show`)
```php
2amigos/yii2-arrayquery-component  1.0.3              Yii2 component that allows for searching/filtering the elements of an array.
behat/gherkin                      v4.5.1             Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap              v3.3.7
bower-asset/inputmask              3.3.11
bower-asset/jquery                 3.2.1
bower-asset/jquery-ui              1.12.1
bower-asset/punycode               v1.3.2
bower-asset/typeahead.js           v0.11.1
bower-asset/yii2-pjax              2.0.7.1
cebe/markdown                      1.1.2              A super fast, highly extensible markdown parser for PHP
clue/stream-filter                 v1.4.0             A simple and modern approach to stream filtering in PHP
codeception/base                   2.4.3              BDD-style testing framework
codeception/phpunit-wrapper        6.0.10             PHPUnit classes used by Codeception
codeception/specify                0.4.6              BDD code blocks for PHPUnit and Codeception
codeception/stub                   2.0.1              Flexible Stub wrapper for PHPUnit's Mock Builder
codeception/verify                 0.3.3              BDD assertion library for PHPUnit
doctrine/instantiator              1.0.5              A small, lightweight utility to instantiate objects in PHP without invoking their constructors
ezyang/htmlpurifier                v4.10.0            Standards compliant HTML filter written in PHP
fzaninotto/faker                   v1.7.1             Faker is a PHP library that generates fake data for you.
guzzle/guzzle                      v3.9.3             PHP HTTP client. This library is deprecated in favor of https://packagist.org/packages/guzzlehttp/guzzle
guzzlehttp/guzzle                  6.3.3              Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1             Guzzle promises library
guzzlehttp/psr7                    1.4.2              PSR-7 message implementation that also provides common utility methods
linslin/yii2-curl                  1.2.1              Easy and nice cURL extension with RESTful support for Yii2
mailgun/mailgun-php                2.5.0              The Mailgun SDK provides methods for all API functions.
mikemccabe/json-patch-php          0.1.0              Produce and apply json-patch objects
mpdf/mpdf                          v6.1.4             A PHP class to generate PDF files from HTML with Unicode/UTF-8 and CJK support
myclabs/deep-copy                  1.7.0              Create deep copies (clones) of your objects
php-http/client-common             1.7.0              Common HTTP Client implementations and tools for HTTPlug
php-http/curl-client               v1.7.1             cURL client for PHP-HTTP
php-http/discovery                 1.4.0              Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                   v1.1.0             HTTPlug, the HTTP client abstraction for PHP
php-http/message                   1.6.0              HTTP Message related tools
php-http/message-factory           v1.0.2             Factory interfaces for PSR-7 HTTP Message
php-http/multipart-stream-builder  1.0.0              A builder class that help you create a multipart stream
php-http/promise                   v1.0.0             Promise used for asynchronous HTTP requests
phpdocumentor/reflection-common    1.0.1              Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  3.3.2              With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is ...
phpdocumentor/type-resolver        0.4.0
phpspec/php-diff                   v1.1.0             A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                   1.7.6              Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          4.0.8              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          1.4.5              FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1              Simple template engine.
phpunit/php-timer                  1.0.9              Utility class for timing
phpunit/php-token-stream           1.4.12             Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    5.7.27             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects       3.4.4              Mock Object library for PHPUnit
psr/http-message                   1.0.1              Common interface for HTTP messages
psr/log                            1.0.2              Common interface for logging libraries
rackspace/php-opencloud            dev-master 062bf8b PHP SDK for Rackspace/OpenStack APIs
sebastian/code-unit-reverse-lookup 1.0.1              Looks up which function or method a line of code belongs to
sebastian/comparator               1.2.4              Provides the functionality to compare PHP values for equality
sebastian/diff                     1.4.3              Diff implementation
sebastian/environment              2.0.0              Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 2.0.0              Provides the functionality to export PHP variables for visualization
sebastian/global-state             1.1.1              Snapshotting of global state
sebastian/object-enumerator        2.0.1              Traverses array structures and object graphs to enumerate all referenced objects
sebastian/recursion-context        2.0.0              Provides functionality to recursively process PHP variables
sebastian/resource-operations      1.0.0              Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1              Library that helps with managing the version number of Git-hosted PHP projects
segmentio/analytics-php            100                Segment Analytics PHP Library
setasign/fpdi                      1.6.2              FPDI is a collection of PHP classes facilitating developers to read pages from existing PDF documents and use them as templ...
swiftmailer/swiftmailer            v5.4.9             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                v3.4.12            Symfony BrowserKit Component
symfony/console                    v3.4.12            Symfony Console Component
symfony/css-selector               v3.4.12            Symfony CssSelector Component
symfony/debug                      v3.4.12            Symfony Debug Component
symfony/dom-crawler                v3.4.12            Symfony DomCrawler Component
symfony/event-dispatcher           v2.8.42            Symfony EventDispatcher Component
symfony/finder                     v3.4.12            Symfony Finder Component
symfony/options-resolver           v3.4.12            Symfony OptionsResolver Component
symfony/polyfill-ctype             v1.8.0             Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.8.0             Symfony polyfill for the Mbstring extension
symfony/yaml                       v3.4.12            Symfony Yaml Component
webmozart/assert                   1.3.0              Assertions to validate method input/output with nice error messages.
yii2mod/yii2-rbac                  2.0                RBAC management module for Yii2
yiisoft/yii2                       2.0.15.1           Yii PHP Framework Version 2
yiisoft/yii2-bootstrap             2.0.8              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer              2.0.6              The composer plugin for Yii extension installer
yiisoft/yii2-debug                 2.0.13             The debugger extension for the Yii framework
yiisoft/yii2-faker                 2.0.4              Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                   2.0.7              The Gii extension for the Yii framework
yiisoft/yii2-jui                   2.0.7              The Jquery UI extension for the Yii framework
yiisoft/yii2-swiftmailer           2.0.7              The SwiftMailer integration for the Yii framework
root@gac-stage:/var/www-gac2#

```

* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - Yii2:
            configFile: 'config/api_test_plain.php'
            cleanup: false
        - REST:
            url: https://1.2.3.4/index_test.php
            depends: PhpBrowser
            part: Json
        - Asserts
```
> config/api_test_plain.php

```php
<?php
$db_test =  [
    'class' => 'yii\db\Connection',
    'dsn' => 'mysql:host=1.2.3.4;dbname=db_test',
    'username' => 'user',
    'password' => '12345678',
    'charset' => 'utf8',
];

$config = [
    'id' => 'api_test',
    'name' => 'API ',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'components' => [
        'session' => [
            'savePath' => '/var/www-gac2/runtime/sessions_api/'
        ],

		'user' => [
		    'class' => 'app\components\User',
		    'identityClass' => 'app\api\modules\v1\models\ApiUser',
			'enableAutoLogin' => false,
			'enableSession' => true,
        ],
        'authManager' => [
            'class' => 'yii\rbac\DbManager',
        ],
		'request' => [
            'parsers' => [
                'application/json' => 'yii\web\JsonParser',
            ],
			'enableCookieValidation' => false,
        ],
        'log' => [
            'traceLevel' => 3,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning', 'info'],
                    'logFile' => '@app/runtime/logs/api.log',
					'logVars' => ['_GET','_POST', '_FILES'],
					'except' => [
						'yii\web\HttpException:400',
					],
				],
                [
                    'class' => 'yii\log\FileTarget',
                    'logFile' => '@app/runtime/logs/error.log',
                    'categories' => ['api_error'],
					'logVars'	=> [],
					'except' => ['yii\*'],
					'maxFileSize' => 20480,
                    'maxLogFiles' => 10,
				],
                [
                    'class' => 'yii\log\FileTarget',
                    'logFile' => '@app/runtime/logs/email.log',
                    'categories' => ['api_email'],
					'logVars'	=> [],
					'maxFileSize' => 20480,
                    'maxLogFiles' => 10,
				],
                [
                    'class' => 'yii\log\FileTarget',
                    'logFile' => '@app/runtime/logs/client.log',
                    'categories' => ['api_client'],
					'logVars'	=> [],
					'maxFileSize' => 20480,
                    'maxLogFiles' => 10,
				]
            ],
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => true,
            'showScriptName' => false,
            'rules' => [
				[
				    'class' => 'yii\rest\UrlRule',
				    'prefix' => '<pubkey:\w+>',
				    'controller' => [
				        'v1/formats', 'v1/industries', 'v1/copystyles', 'v1/copyvoices', 'v1/contenttypes',
				        'v1/formattings', 'v1/targetaudiences', 'v1/localizations'
				    ]
				],


                //Administrative tools
                //Import client, copywriter and admins to api_users table
                'GET import_users' => 'gac/import/users',
                'GET import_users_rbac' => 'gac/import/users-with-rbac',

                '<pubkey:\w+>/v1/check' => 'v1/tools/check',

                'GET <pubkey:\w+>/v1/formatsbad' => 'v1/formats/index-bad',

                'GET <pubkey:\w+>/v1/formats/<code:[\w\-]+>' => 'v1/formats/viewbycode',
                'GET <pubkey:\w+>/v1/industries/<code:[\w\-]+>' => 'v1/industries/viewbycode',
                'GET <pubkey:\w+>/v1/copystyles/<code:[\w\-]+>' => 'v1/copystyles/viewbycode',
                'GET <pubkey:\w+>/v1/copyvoices/<code:[\w\-]+>' => 'v1/copyvoices/viewbycode',
                'GET <pubkey:\w+>/v1/contenttypes/<code:[\w\-]+>' => 'v1/contenttypes/viewbycode',
                'GET <pubkey:\w+>/v1/formattings/<code:[\w\-]+>' => 'v1/formattings/viewbycode',
                'GET <pubkey:\w+>/v1/targetaudiences/<code:[\w\-]+>' => 'v1/targetaudiences/viewbycode',
                'GET <pubkey:\w+>/v1/localizations/<code:[\w\-]+>' => 'v1/localizations/viewbycode',


                'GET <pubkey:\w+>/v1/project_tags' => 'v1/clienttags/tags',
                'POST <pubkey:\w+>/v1/project_tag' => 'v1/clienttags/create-tag',
                'GET <pubkey:\w+>/v1/project_owners' => 'v1/clienttags/owners',
                'POST <pubkey:\w+>/v1/project_owner' => 'v1/clienttags/create-owner',

				'GET <pubkey:\w+>/v1/myteam' => 'v1/clients/my-team',
				'GET <pubkey:\w+>/v1/copywriters' => 'v1/clients/copywriters',
				'GET <pubkey:\w+>/v1/copywriters/<total:\w+>' => 'v1/clients/copywriters',
				'GET <pubkey:\w+>/v1/balance' => 'v1/clients/balance',
				'GET <pubkey:\w+>/v1/transactions' => 'v1/clients/transactions',
				'GET <pubkey:\w+>/v1/invoice/<invoice_id:\d+>' => 'v1/clients/invoice',


                'POST <pubkey:\w+>/v1/projects' => 'v1/projects/create',                    //project create
                'POST <pubkey:\w+>/v1/projects/<id:\d+>' => 'v1/projects/update',           //project update
                'GET <pubkey:\w+>/v1/projects/<id:\d+>/duplicate' => 'v1/projects/duplicate',   //project duplicate
                'GET <pubkey:\w+>/v1/projects' => 'v1/projects/index',                          //project list
                'GET <pubkey:\w+>/v1/projects/total' => 'v1/projects/total',                          //project total
                'GET <pubkey:\w+>/v1/projects/total-per-status' => 'v1/projects/total-per-status',      //project total by status
                'GET <pubkey:\w+>/v1/projects/<id:\d+>' => 'v1/projects/view',                  //project view
                'DELETE <pubkey:\w+>/v1/projects/<id:\d+>' => 'v1/projects/delete',             //project delete
                'PUT <pubkey:\w+>/v1/projects/<id:\d+>/extend' => 'v1/projects/extendue',       //project extend due
                'GET <pubkey:\w+>/v1/projects/<id:\d+>/revisions' => 'v1/revision/index',       //revision list
                'GET <pubkey:\w+>/v1/projects/<id:\d+>/revisions/<latest:\w+>' => 'v1/revision/index',          //revision list (last)
                'PUT <pubkey:\w+>/v1/projects/<id:\d+>/request_revision' => 'v1/projects/requestrevision',      //revision request review
                'PUT <pubkey:\w+>/v1/projects/<id:\d+>/approve' => 'v1/projects/approveproject',                //approve project
                'PUT <pubkey:\w+>/v1/projects/<id:\d+>/pay' => 'v1/projects/pay',                //pay for the project

                'GET <pubkey:\w+>/v1/projects/<id:\d+>/pitches' => 'v1/pitch/index',           //pitches list
                'GET <pubkey:\w+>/v1/projects/<id:\d+>/pitches/<latest:\w+>' => 'v1/pitch/index',               //pitches list

                //'PUT <pubkey:\w+>/v1/projects/<id:\d+>/pitches/<pitch_id:\d+>/award' => 'v1/pitch/award',       //pitches award
                'PUT <pubkey:\w+>/v1/projects/pitches/<pitch_id:\d+>/award' => 'v1/pitch/award',       //pitches award
                'PUT <pubkey:\w+>/v1/projects/pitches/<pitch_id:\d+>/reject' => 'v1/pitch/reject',       //pitches reject
                'POST <pubkey:\w+>/v1/projects/pitches/<pitch_id:\d+>/send_message' => 'v1/pitch/add-message',       //pitches reject

                'POST <pubkey:\w+>/v1/message_support' => 'v1/tools/messagesupport',

                'GET documentation' => 'app/documentation/index.html',

                'GET <pubkey:\w+>/v1/opencloud' => 'v1/upload/opencloud',
                'GET <token:\w+>/v1/rbac/<action:\w*>' => 'v1/rbac/<action>',
                '<pubkey:\w+>/v1/test/<action:\w*>' => 'v1/test/<action>',
				[
				    'class' => 'yii\rest\UrlRule',
				    'controller' => 'v1/clients',
				    'prefix' => '<pubkey:\w+>',
				],
            ],
        ],
		'response' => array(
			'format' =>  \yii\web\Response::FORMAT_JSON,
			'class' => \yii\web\Response::className(),

			'on beforeSend' => function($event){
			$response = $event->sender;
			$responseData = [
			'success' 	=> 1,
			'total'     => 0,
			'error'		=> [
				'name'		=> '',
				'status'	=> '',
				'message'	=> '',
				],
			'response' => [''],
			];

            $message = $status = '';
			    if(isset($response->data['message'])) $message = $response->data['message'];
			    if(isset($response->data['status'])) $status = $response->data['status'];


			//Override message and status, if exception handler passed with json string in the error field
			    if(isset($response->data['message'])) $statusOverride = json_decode($response->data['message'], true);
				if(isset($statusOverride) && $statusOverride !== null){
				$message = $statusOverride['error'];
				$status = $statusOverride['status'];
				}

				if($response->data !== null && ($exception = Yii::$app->getErrorHandler()->exception) !== null){
				$responseData['success'] = 0;
					if(isset($response->data['name']))$responseData['error']['name'] = $response->data['name'];
					//if(isset($response->data['code']))$responseData['error']['code'] = $response->data['code'];
					if(isset($response->data['status']))$responseData['error']['status'] = $status;
					if(isset($response->data['message']))$responseData['error']['message'] = $message;

				$response->data = $responseData;
				Yii::info($message.' [pubkey: "'.Yii::$app->request->get('pubkey').'" user id: "'.Yii::$app->params['user']['id'].'", type: "'.Yii::$app->params['user']['type'].'")', 'api_error');
				}
				else {
				$responseData['response'] = $response->data;
                    if(is_array($response->data)) $responseData['total'] = count($response->data);
				$response->data = $responseData;
				}
			},
		),

	'db' => $db_test,

	'opencloud' => [
        'class' => 'app\api\modules\v1\components\Opencloud',
        'params' => [
            'container' => 'api-files',
            'container_http' => 'https://3.4.5.6',
            'region' => 'ORD',
            'api_username' => 'user',
            'api_key' => '1234',
            ]
        ],
    'segmentio' => [
        'class' => 'app\api\modules\v1\components\Segmentio',
        'params' => [
            'write_key' => '12345678',
            'read_key' => 'qwertyuioi',
            'intercom' => '5678901234',
        ],
    ],
    'dynamicDbConnection' => [
        'class' => 'app\components\DynamicDbConnection'
        ],
   'mailer' => [
        'class' => '\app\api\modules\v1\components\mailer\Mailer',
        'domain' => 'e.mydomain.com',
        'apiKey' => '1234455555',
        ]
	],
    'modules' => [
	    'debug' => [
        'class' => 'yii\debug\Module',
            'allowedIPs' => ['*'],
        ],
		'v1' => ['class' => 'app\api\modules\v1\Module'],
		'gac' => ['class' => 'app\modules\gac\Module'],
		'gii' => ['class' => 'yii\gii\Module']
    ],

];

return $config;
```

**Comment by vffkiva** [comment]
Dear all,
Just to let you know. I have commented out one row within the file vendor/codeception/base/src/Codeception/Module/Yii2.php and it seems to solve my issue:
```
public function _after(TestInterface $test)
    {
        $_SESSION = [];
        $_FILES = [];
        $_GET = [];
        $_POST = [];
        $_COOKIE = [];
        $_REQUEST = [];

        $this->rollbackTransactions();

        if ($this->config['cleanup']) {
            foreach ($this->loadedFixtures as $fixture) {
                $fixture->unloadFixtures();
            }
            $this->loadedFixtures = [];
        }

        if ($this->client !== null && $this->client->getApplication()->has('session', true)) {
            $this->client->getApplication()->session->close();
        }

        //$this->client->resetApplication(); //Commented out row
        parent::_after($test);
    }
```

However, I suppose it is a not a good idea to perform manual changes within vendor folder.

**Comment by mikkelcp1** [comment]
Thanks. This fix also fixes my problem seen today.

Yii::$app is null, when it tries to serialize the app\models\User (ActiveRecord) argument passed into step amLoggedInAs for printing after Scenario Steps. Might be best to stringify arguments before "Destroying application".

```
class SiteCest
{
    public function openChangeLog(\FunctionalTester $I)
    {
        $I->amLoggedInAs(\app\models\User::findByEmail('e@e.ca'));
        $I->amOnRoute('site/changelog');
        $I->see('ChangelogIM_NOT_HERE_FAIL'); //This will fail.
    }
}
```


```
 I see "ChangelogIM_NOT_HERE_FAIL"
 FAIL

  [Transaction] Rolling back 1 transactions
  [Database] Transaction cancelled; all changes reverted.
  Destroying application
  Suite done, restoring $_SERVER to original
--------------------------------------------------------------------------------
1) SiteCest: Open change log
 Test  tests\functional\SiteCest.php:openChangeLog
 Step  See "ChangelogIM_NOT_HERE_FAIL"
 Fail  Failed asserting that  on page /site/changelog
-->  Changelog ... 
[Content too long to display. See complete response in 'C:\xampp-7\htdocs\www-master\tests/bamboo\' directory]
--> contains "ChangelogIM_NOT_HERE_FAIL".

Scenario Steps:

 3. $I->see("ChangelogIM_NOT_HERE_FAIL") at tests\functional\SiteCest.php:10
 2. $I->amOnRoute("site/changelog") at tests\functional\SiteCest.php:9
An Error occurred while handling another error:
Error: Call to a member function has() on null in C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\web\ErrorHandler.php:91
Stack trace:
#0 C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\base\ErrorHandler.php(111): yii\web\ErrorHandler->renderException(Object(Error))
#1 [internal function]: yii\base\ErrorHandler->handleException(Object(Error))
#2 {main}
Previous exception:
Error: Call to a member function getDb() on null in C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\db\ActiveRecord.php:135
Stack trace:
#0 C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\db\ActiveRecord.php(382): yii\db\ActiveRecord::getDb()
#1 C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\db\ActiveRecord.php(418): yii\db\ActiveRecord::getTableSchema()
#2 C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\db\BaseActiveRecord.php(492): yii\db\ActiveRecord->attributes()
#3 C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\db\BaseActiveRecord.php(289): yii\db\BaseActiveRecord->hasAttribute('__mocked')
#4 C:\xampp-7\htdocs\www-master\vendor\yiisoft\yii2\db\BaseActiveRecord.php(335): yii\db\BaseActiveRecord->__get('__mocked')
#5 C:\xampp-7\htdocs\www-master\vendor\codeception\codeception\src\Codeception\Step.php(176): yii\db\BaseActiveRecord->__isset('__mocked')
#6 C:\xampp-7\htdocs\www-master\vendor\codeception\codeception\src\Codeception\Step.php(164): Codeception\Step->getClassName(Object(app\models\User))
#7 C:\xampp-7\htdocs\www-master\vendor\codeception\codeception\src\Codeception\Step.php(103): Codeception\Step->stringifyArgument(Object(app\models\User))
#8 C:\xampp-7\htdocs\www-master\vendor\codeception\codeception\src\Codeception\Step.php(235): Codeception\Step->getArgumentsAsString(200)
#9 C:\xampp-7\htdocs\www-master\vendor\codeception\codeception\src\Codeception\Step.php(208): Codeception\Step->getHumanizedArguments()
```

**Comment by miolae** [comment]
The same issue, but commentnig of `resetApplication` didn't help.

The only output is:
```
$ php vendor/bin/codecept run --debug
Codeception PHP Testing Framework v2.4.4
Powered by PHPUnit 7.1.5 by Sebastian Bergmann and contributors.
PHP Fatal error:  Uncaught Error: Call to a member function getDb() on null in /home/miolae/dev/yii2-billing/vendor/yiisoft/yii2/db/ActiveRecord.php:135
Stack trace:
#0 /home/miolae/dev/yii2-billing/vendor/yiisoft/yii2/db/ActiveRecord.php(382): yii\db\ActiveRecord::getDb()
#1 /home/miolae/dev/yii2-billing/vendor/yiisoft/yii2/db/ActiveRecord.php(408): yii\db\ActiveRecord::getTableSchema()
#2 /home/miolae/dev/yii2-billing/vendor/yiisoft/yii2/db/ActiveRecord.php(178): yii\db\ActiveRecord::primaryKey()
#3 /home/miolae/dev/yii2-billing/vendor/yiisoft/yii2/db/BaseActiveRecord.php(112): yii\db\ActiveRecord::findByCondition(Array)
#4 /home/miolae/dev/yii2-billing/tests/unit/models/InvoiceCest.php(30): yii\db\BaseActiveRecord::findOne(Array)
#5 [internal function]: models\InvoiceCest->validateProvider()
#6 /home/miolae/dev/yii2-billing/vendor/codeception/codeception/src/Codeception/Util/ReflectionHelper.php(47): ReflectionMethod->invokeArgs(Object(models\InvoiceCest), Array)
#7 /home/miolae/dev/yii2-billing/vendor/codeception/codecepti in /home/miolae/dev/yii2-billing/vendor/yiisoft/yii2/db/ActiveRecord.php on line 135
```

**Comment by miolae** [comment]
I just tryed Codeception v2.3.9 with PHPUnit v6.5.9. Result is the same.

**Comment by miolae** [comment]
I've found my problem. I'm trying to use Yii2 Codeception module in data provider class. Can I do smthng like this without errors?

My data provider: 

```php
    public function validateProvider(): array
    {
        $accountFirstId = Account::findOne(['title' => 'first test'])->id;
        $accountSecondId = Account::findOne(['title' => 'second test'])->id;
        return [
            'has no accounts' => [
                'result'     => false,
                'attributes' => [
                    'account_id_from' => 0,
                    'account_id_to'   => 0,
                    'amount'          => 1,
                ],
            ],
            'has no account from' => [
                'result'     => false,
                'attributes' => [
                    'account_id_from' => 0,
                    'account_id_to'   => $accountSecondId,
                    'amount'          => 1,
                ],
            ],
            'has no account to' => [
                'result'     => false,
                'attributes' => [
                    'account_id_from' => $accountFirstId,
                    'account_id_to'   => 0,
                    'amount'          => 1,
                ],
            ],
            'has equal accounts' => [
                'result'     => false,
                'attributes' => [
                    'account_id_from' => $accountFirstId,
                    'account_id_to'   => $accountFirstId,
                    'amount'          => 1,
                ],
            ],
        ];
    }
```

**Comment by SamMousa** [comment]
@vffkiva would it be possible for you to set up a minimal test case and create a PR [here](https://github.com/codeception/yii2-tests)?

The idea is you create a minimal application (config.php, codeception.yml, tests) and this application is tested against every future change. 
That way I can get started and hopefully resolve your issue!

**Comment by miolae** [comment]
Hi all!

Was there a PR?

**Comment by SamMousa** [comment]
There were several since the original issue.

**Comment by mm-shopbox** [comment]
Moving yii2 module in config file to the end solved that for me 
`
class_name: UnitTester
modules:
    enabled:
        - DataFactory:
           factories: codeception/_support/factories
           depends: Yii2
        - Yii2:
           configFile: ../config/tests/unit.php
           part: [fixtures, orm, email]
           cleanup: false
`

**Comment by wajdijurry** [comment]
@mm-shopbox Thanks for your suggestion. That's solved my problem.
