### ISSUE TITLE
[Error] Call to undefined function Codeception\Test\codecept_relative_path()  using composer global require

### ISSUE THREAD

**Issue by RdeWilde** [Codeception/Codeception#5143]
#### What are you trying to achieve?
Start the codeception tests from script, installed globally thru composer

Running codeception from cli `codecept run api` works fine

#### What do you get instead?
I get this error ` [Error] Call to undefined function Codeception\Test\codecept_relative_path()  ` seems like the autoload file isn't called, which Composer autoloader should handle. This may be related to the fact that Codeception is installed globally thru composer using `composer global require codeception/codeception`

> Provide console output if related. Use `-vvv` mode for more details.
I run it from deployer, which source script is included below
```bash                                                                                                             
 [Error] Call to undefined function Codeception\Test\codecept_relative_path()                                           
                                                                                                                        

 #0 /home/robert/.composer/vendor/codeception/codeception/src/Codeception/Lib/GroupManager.php(91):                     
 Codeception\Test\Descriptor::getTestFileName(Object(Codeception\Test\Cest))                                            
 #1 /home/robert/.composer/vendor/codeception/codeception/src/Codeception/SuiteManager.php(125):                        
 Codeception\Lib\GroupManager->groupsForTest(Object(Codeception\Test\Cest))                                             
 #2 /home/robert/.composer/vendor/codeception/codeception/src/Codeception/SuiteManager.php(103):                        
 Codeception\SuiteManager->addToSuite(Object(Codeception\Test\Cest))                                                    
 #3 /home/robert/.composer/vendor/codeception/codeception/src/Codeception/Codecept.php(187):                            
 Codeception\SuiteManager->loadTests(NULL)                                                                              
 #4 /home/robert/.composer/vendor/codeception/codeception/src/Codeception/Codecept.php(157):                            
 Codeception\Codecept->runSuite(Array, 'api', NULL)                                                                     
 #5 /home/robert/PhpstormProjects/DEV API nieuwe server/deploy.php(191): Codeception\Codecept->run('api')               
 #6 [internal function]: Deployer\Deployer::Deployer\{closure}()                                                        
 #7 /home/robert/.composer/vendor/deployer/deployer/src/Task/Task.php(105): call_user_func(Object(Closure))             
 #8 /home/robert/.composer/vendor/deployer/deployer/src/Executor/SeriesExecutor.php(63):                                
 Deployer\Task\Task->run(Object(Deployer\Task\Context))                                                                 
 #9 /home/robert/.composer/vendor/deployer/deployer/src/Console/TaskCommand.php(142):                                   
 Deployer\Executor\SeriesExecutor->run(Array, Array)                                                                    
 #10 /home/robert/.composer/vendor/symfony/console/Command/Command.php(252):                                            
 Deployer\Console\TaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput),                               
 Object(Deployer\Console\Output\OutputWatcher))                                                                         
 #11 /home/robert/.composer/vendor/symfony/console/Application.php(946):                                                
 Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput),                      
 Object(Deployer\Console\Output\OutputWatcher))                                                                         
 #12 /home/robert/.composer/vendor/deployer/deployer/src/Console/Application.php(133):                                  
 Symfony\Component\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand),                              
 Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))                      
 #13 /home/robert/.composer/vendor/symfony/console/Application.php(248):                                                
 Deployer\Console\Application->doRunCommand(Object(Deployer\Console\TaskCommand),                                       
 Object(Symfony\Component\Console\Input\ArgvInput), Object(Deployer\Console\Output\OutputWatcher))                      
 #14 /home/robert/.composer/vendor/symfony/console/Application.php(148):                                                
 Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput),                        
 Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                
 #15 /home/robert/.composer/vendor/deployer/deployer/src/Deployer.php(331):                                             
 Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput),                          
 Object(Symfony\Component\Console\Output\ConsoleOutput))                                                                
 #16 /home/robert/.composer/vendor/deployer/deployer/bin/dep(120): Deployer\Deployer::run('master',                     
 '/home/robert/Ph...')                                                                                                  
 #17 {main}   
```
> Provide test source code if related

```php
	$Codecept = new \Codeception\Codecept(array(
		'steps' => true,
		'verbosity' => 3,
		// some other options (see Codeception docs/sources)
	));

	$Codecept->run('api');
```
### Details

* Codeception version: 2.4.2
* PHP Version: 7.1.2
* Operating System: Linux
* Installation type: Composer
* List of installed packages (`composer show`): a lot, but does not include codeception itself, does include `yiisoft/yii2-codeception           dev-master 086c8c2 The Codeception integration for the Yii framework`
* Suite configuration: api

```yml
class_name: ApiTester
modules:

    enabled:
        - \Helper\Api
        - PhpBrowser
        - REST:
            depends: PhpBrowser
    config:
        PhpBrowser:
            url: https://dev.api.host.tld/
            auth: ['user', 'pass']
```

How do I get the autoloader file included thru composer without stating a explicit require to my global composer lib dir?

**Comment by Naktibalda** [comment]
It looks like there is nothing else you can do on your side.

On Codeception side it looks like Codeception wasn't made to be used as a library.
All those functions should be moved from autoload.php to another file (shim.php is a good candidate).
And that file should be added to composer.json autoload/files section:
```json
    "autoload": {
        "files": ["shim.php"]
    }
```

**Comment by Naktibalda** [comment]
Function file will be loaded by composer in Codeception 5.0: https://github.com/Codeception/Codeception/pull/6067
