### ISSUE TITLE
Acceptance tests on Chrome are not working

### ISSUE THREAD

**Issue by tasselchof** [Codeception/Codeception#5200]
#### What are you trying to achieve?

Execute test using Chrome (Firefox tests are ok, selenium is running)

#### What do you get instead?

```bash
Directory Format: record_5baa8083b94bc_{testname} ----
LanguageChangeCept: Change system language
Signature: LanguageChangeCept
Test: codeception/Acceptance/LanguageChangeCept.php
Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/home/dev/domains/alpha.dev/module/Users/../../codeception/_output/' dir
 ERROR 

PHP Fatal error:  Uncaught Error: Call to a member function takeScreenshot() on null in /home/dev/domains/alpha.dev/vendor/codeception/codeception/ext/Recorder.php:344
Stack trace:
#0 /home/dev/domains/alpha.dev/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Codeception\Extension\Recorder->persist(Object(Codeception\Event\FailEvent), 'test.error', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#1 /home/dev/domains/alpha.dev/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'test.error', Object(Codeception\Event\FailEvent))
#2 /home/dev/domains/alpha.dev/vendor/codeception/phpunit-wrapper/src/Listener.php(133): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('test.error', Object(Codeception\Event\FailEvent))
#3 /home/dev/domains/alpha.dev/vendor/codeception/phpunit-wrapper/src/Listener.php(50): Codeception\PHPUnit\Listener->fire('test.error', Object(Codeception\Event\Fa in /home/dev/domains/alpha.dev/vendor/codeception/codeception/ext/Recorder.php on line 344

Fatal error: Uncaught Error: Call to a member function takeScreenshot() on null in /home/dev/domains/alpha.dev/vendor/codeception/codeception/ext/Recorder.php on line 344

Error: Call to a member function takeScreenshot() on null in /home/dev/domains/alpha.dev/vendor/codeception/codeception/ext/Recorder.php on line 344

Call Stack:
    0.0005     375272   1. {main}() /home/dev/domains/alpha.dev/vendor/codeception/codeception/codecept:0
    0.2336    8020704   2. Codeception\Application->run() /home/dev/domains/alpha.dev/vendor/codeception/codeception/codecept:43
    0.2336    8020704   3. Codeception\Application->run() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/Application.php:108
    0.2841    8171504   4. Codeception\Application->doRun() /home/dev/domains/alpha.dev/vendor/symfony/console/Application.php:145
    0.2843    8171504   5. Codeception\Application->doRunCommand() /home/dev/domains/alpha.dev/vendor/symfony/console/Application.php:262
    0.2843    8171504   6. Codeception\Command\Run->run() /home/dev/domains/alpha.dev/vendor/symfony/console/Application.php:886
    0.2861    8178928   7. Codeception\Command\Run->execute() /home/dev/domains/alpha.dev/vendor/symfony/console/Command/Command.php:251
    0.3511    9228168   8. Codeception\Command\Run->runSuites() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/Command/Run.php:387
    0.3511    9228168   9. Codeception\Codecept->run() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/Command/Run.php:492
    0.3641    9256312  10. Codeception\Codecept->runSuite() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/Codecept.php:158
    0.5966   11618112  11. Codeception\SuiteManager->run() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/Codecept.php:191
    0.6002   11698784  12. Codeception\PHPUnit\Runner->doEnhancedRun() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/SuiteManager.php:157
    0.6004   11707488  13. Codeception\Suite->run() /home/dev/domains/alpha.dev/vendor/codeception/phpunit-wrapper/src/Runner.php:114
    0.6005   11707680  14. Codeception\Test\Cept->run() /home/dev/domains/alpha.dev/vendor/phpunit/phpunit/src/Framework/TestSuite.php:750
    0.6005   11707680  15. PHPUnit\Framework\TestResult->startTest() /home/dev/domains/alpha.dev/vendor/codeception/codeception/src/Codeception/Test/Test.php:75
    0.6005   11707680  16. Codeception\PHPUnit\Listener->startTest() /home/dev/domains/alpha.dev/vendor/phpunit/phpunit/src/Framework/TestResult.php:395
   74.9500   11969840  17. PHPUnit\Framework\TestResult->addError() /home/dev/domains/alpha.dev/vendor/codeception/phpunit-wrapper/src/Listener.php:108
   74.9504   11983440  18. Codeception\PHPUnit\Listener->addError() /home/dev/domains/alpha.dev/vendor/phpunit/phpunit/src/Framework/TestResult.php:288
   74.9505   11987056  19. Codeception\PHPUnit\Listener->fire() /home/dev/domains/alpha.dev/vendor/codeception/phpunit-wrapper/src/Listener.php:50
   74.9505   11987056  20. Symfony\Component\EventDispatcher\EventDispatcher->dispatch() /home/dev/domains/alpha.dev/vendor/codeception/phpunit-wrapper/src/Listener.php:133
   74.9505   11987432  21. Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() /home/dev/domains/alpha.dev/vendor/symfony/event-dispatcher/EventDispatcher.php:44
   74.9513   11988128  22. Codeception\Extension\Recorder->persist() /home/dev/domains/alpha.dev/vendor/symfony/event-dispatcher/EventDispatcher.php:212




FATAL ERROR. TESTS NOT FINISHED.
```
> Provide test source code if related

```php
// paste test
```
### Details

* Codeception version: last
* PHP Version: 7.1
* Operating System: CentOS
* Installation type: Composer
* Suite configuration:

```yml
class_name: UsersAcceptanceTester
coverage:
  include:
  - src/*
  exclude:
  - view/*
  - data/*
  - language/*
extensions:
  enabled:
  - Codeception\Extension\RunFailed
  - Codeception\Extension\Recorder
modules:
  error_level: "E_ALL"
  enabled:
  - WebDriver:
      url: 'http://tests.dev'
      browser: chrome
      window_size: 1024x900
      capabilities:
        acceptInsecureCerts: true
        enableVerboseLogging: true
  - Filesystem
  - Asserts
  config:
    Codeception\Extension\Recorder:
      delete_successful: true
```

**Comment by tasselchof** [comment]
Selenium log:
```bash
[root@srv selenium]# xvfb-run java -jar ./selenium-server-standalone.jar
21:44:09.010 INFO [GridLauncherV3.launch] - Selenium build info: version: '3.14.0', revision: 'aacccce0'
21:44:09.012 INFO [GridLauncherV3$1.launch] - Launching a standalone Selenium Server on port 4444
2018-09-25 21:44:09.117:INFO::main: Logging initialized @436ms to org.seleniumhq.jetty9.util.log.StdErrLog
21:44:09.325 INFO [SeleniumServer.boot] - Selenium Server is up and running on port 4444
21:44:10.996 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "browserName": "chrome",
  "enableVerboseLogging": true
}
21:44:10.998 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver (v2.4.226074) on port 29651
[0.324][WARNING]: PAC support disabled because there is no system implementation
```

**Comment by Naktibalda** [comment]
Does it work without Recorder extension?

**Comment by tasselchof** [comment]
Commented Recorder extension.

```bash
21:58:50.636 INFO [ActiveSessionFactory.apply] - Capabilities are: {
  "acceptInsecureCerts": true,
  "browserName": "chrome",
  "enableVerboseLogging": true
}
21:58:50.636 INFO [ActiveSessionFactory.lambda$apply$11] - Matched factory org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.chrome.ChromeDriverService)
Starting ChromeDriver (v2.4.226074) on port 24200
[0.017][WARNING]: PAC support disabled because there is no system implementation
```

This is log of Selenium and test itself:

```bash
LanguageChangeCept: Change system language
Signature: LanguageChangeCept
Test: codeception/Acceptance/LanguageChangeCept.php
Scenario --
  WebDriver::debugWebDriverLogs method has been called when webDriver is not set
  WebDriver::_saveScreenshot method has been called when webDriver is not set
  WebDriver::_savePageSource method has been called when webDriver is not set
  Screenshot and page source were saved into '/home/dev/domains/alpha.dev/module/Users/../../codeception/_output/' dir
 ERROR 
```

And content of fail file is:
```bash
[root@srv alpha.orderadmin.ru]# cat /home/dev/domains/alpha.dev/module/Users/../../codeception/_output/LanguageChangeCept.fail.html
<html><head></head><body></body></html>
```

**Comment by tasselchof** [comment]
Exception itself is:

```bash
1) LanguageChangeCept: Change system language
 Test  codeception/Acceptance/LanguageChangeCept.php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
  [Facebook\WebDriver\Exception\UnknownServerException] chrome not reachable
  (Driver info: chromedriver=2.4.226074,platform=Linux 3.10.0-427.36.1.lve1.4.47.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 74.30 seconds
Build info: version: '3.14.0', revision: 'aacccce0', time: '2018-08-02T20:13:22.693Z'
System info: host: 'srv.reworker', ip: '0.0.0.0', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-427.36.1.lve1.4.47.el7.x86_64', java.version: '1.8.0_131'
Driver info: driver.version: unknown  
```

**Comment by Naktibalda** [comment]
Have you actually got Chrome browser installed?

**Comment by tasselchof** [comment]
Yep, via yum.

**Comment by tasselchof** [comment]
I updated chrome driver to latest version, reinstalled chrome and now error changed:

```bash
[Facebook\WebDriver\Exception\UnknownServerException] unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 3.10.0-427.36.1.lve1.4.47.el7.x86_64 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 110 milliseconds
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'srv', ip: '0.0.0.0', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-427.36.1.lve1.4.47.el7.x86_64', java.version: '1.8.0_181'
Driver info: driver.version: unknown  
```

**Comment by tasselchof** [comment]
Added "no-sandbox" parameter to chromeOptions section:

```bash
class_name: UsersAcceptanceTester
coverage:
  include:
  - src/*
  exclude:
  - view/*
  - data/*
  - language/*
extensions:
  enabled:
  - Codeception\Extension\RunFailed
#  - Codeception\Extension\Recorder
modules:
  error_level: "E_ALL"
  enabled:
  - WebDriver:
      url: "http://tests.dev"
      browser: chrome
      window_size: 1024x900
      capabilities:
        acceptInsecureCerts: true
        enableVerboseLogging: true
        chromeOptions:
          args: ["disable-dev-shm-usage", "no-sandbox", "disable-infobars", "headless", "disable-gpu"]
  - Filesystem
  - Asserts
#  config:
#    Codeception\Extension\Recorder:
#      delete_successful: true
```

And it helped.
