### ISSUE TITLE
WebDriver - AttachFile() does not work on safari browser

### ISSUE THREAD

**Issue by matvey88** [Codeception/Codeception#5336]
#### In my tests, i trying attach file on browser safari, but its not work. I have error in console  

>I try

``` $I->attachFile('input[type="file"]', 'test_file.docx'); ```

> when test fail, i see in console 
```bash
[Facebook\WebDriver\Exception\UnrecognizedExceptionException]
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'ma.local', ip: 'fe80:0:0:0:109f:854e:356e:54af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.0.2, javascriptEnabled: true, platform: MAC, platformName: MAC, setWindowRect: true}
Session ID: BF750CB9-D926-4E11-89F3-1D5F54696341
```
> full log 
```bash
  I attach file "input[type="file"]","test_file.docx"
14:01:33.821 INFO - Executing: [find elements: By.xpath: .//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')][(((./@name = 'input[type="file"]') or ./@id = //label[contains(normalize-space(string(.)), 'input[type="file"]')]/@for) or ./@placeholder = 'input[type="file"]')] | .//label[contains(normalize-space(string(.)), 'input[type="file"]')]//.//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')]])
14:01:33.828 INFO - Done: [find elements: By.xpath: .//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')][(((./@name = 'input[type="file"]') or ./@id = //label[contains(normalize-space(string(.)), 'input[type="file"]')]/@for) or ./@placeholder = 'input[type="file"]')] | .//label[contains(normalize-space(string(.)), 'input[type="file"]')]//.//*[self::input | self::textarea | self::select][not(./@type = 'submit' or ./@type = 'image' or ./@type = 'hidden')]]
14:01:33.829 INFO - Executing: [find elements: By.xpath: .//*[self::input | self::textarea | self::select][@name = 'input[type="file"]']])
14:01:33.836 INFO - Done: [find elements: By.xpath: .//*[self::input | self::textarea | self::select][@name = 'input[type="file"]']]
14:01:33.840 INFO - Executing: [find elements: By.cssSelector: input[type="file"]])
14:01:33.846 INFO - Done: [find elements: By.cssSelector: input[type="file"]]
14:01:33.858 INFO - Executing: org.openqa.selenium.remote.server.handler.UploadFile@587b7d2b)
14:01:33.876 INFO - Done: org.openqa.selenium.remote.server.handler.UploadFile@587b7d2b
14:01:33.879 INFO - Executing: [send keys: 130 [[SafariDriver: Safari on MAC (BF750CB9-D926-4E11-89F3-1D5F54696341)] -> css selector: input[type="file"]], [/var/folders/f9/_qdjyz0d159fq3kcwk1t28sh0000gp/T/1547207977398-0/upload5120104429452934009file/test_file.docx]])
14:01:34.123 WARN - Exception thrown
org.openqa.selenium.ElementNotInteractableException:
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'ma.local', ip: 'fe80:0:0:0:109f:854e:356e:54af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.0.2, javascriptEnabled: true, platform: MAC, platformName: MAC, setWindowRect: true}
Session ID: BF750CB9-D926-4E11-89F3-1D5F54696341
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
	at org.openqa.selenium.remote.RemoteWebElement.sendKeys(RemoteWebElement.java:100)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement$1.invoke(EventFiringWebDriver.java:375)
	at com.sun.proxy.$Proxy7.sendKeys(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver$EventFiringWebElement.sendKeys(EventFiringWebDriver.java:398)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.remote.server.KnownElements$1.invoke(KnownElements.java:64)
	at com.sun.proxy.$Proxy8.sendKeys(Unknown Source)
	at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:50)
	at org.openqa.selenium.remote.server.handler.SendKeys.call(SendKeys.java:29)
	at org.openqa.selenium.remote.server.handler.WebDriverHandler.handle(WebDriverHandler.java:41)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:191)
	at org.openqa.selenium.remote.server.DriverServlet.lambda$handleRequest$0(DriverServlet.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:01:34.124 WARN - Exception:
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'ma.local', ip: 'fe80:0:0:0:109f:854e:356e:54af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.0.2, javascriptEnabled: true, platform: MAC, platformName: MAC, setWindowRect: true}
Session ID: BF750CB9-D926-4E11-89F3-1D5F54696341
14:01:34.144 INFO - Executing: [fetching available log types])
14:01:34.148 WARN - Exception thrown
org.openqa.selenium.UnsupportedCommandException: The command 'GET /session/BF750CB9-D926-4E11-89F3-1D5F54696341/log/types' was not found.
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'ma.local', ip: 'fe80:0:0:0:109f:854e:356e:54af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.0.2, javascriptEnabled: true, platform: MAC, platformName: MAC, setWindowRect: true}
Session ID: BF750CB9-D926-4E11-89F3-1D5F54696341
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
	at org.openqa.selenium.remote.RemoteExecuteMethod.execute(RemoteExecuteMethod.java:33)
	at org.openqa.selenium.remote.RemoteLogs.getAvailableLogTypes(RemoteLogs.java:103)
	at org.openqa.selenium.remote.server.handler.GetAvailableLogTypesHandler.call(GetAvailableLogTypesHandler.java:37)
	at org.openqa.selenium.remote.server.handler.GetAvailableLogTypesHandler.call(GetAvailableLogTypesHandler.java:28)
	at org.openqa.selenium.remote.server.handler.WebDriverHandler.handle(WebDriverHandler.java:41)
	at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:112)
	at org.openqa.selenium.remote.server.JsonHttpCommandHandler.handleRequest(JsonHttpCommandHandler.java:191)
	at org.openqa.selenium.remote.server.DriverServlet.lambda$handleRequest$0(DriverServlet.java:261)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:01:34.149 WARN - Exception: The command 'GET /session/BF750CB9-D926-4E11-89F3-1D5F54696341/log/types' was not found.
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: 'ma.local', ip: 'fe80:0:0:0:109f:854e:356e:54af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_144'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.0.2, javascriptEnabled: true, platform: MAC, platformName: MAC, setWindowRect: true}
Session ID: BF750CB9-D926-4E11-89F3-1D5F54696341
  Unable to retrieve Selenium logs : The command 'GET /session/BF750CB9-D926-4E11-89F3-1D5F54696341/log/types' was not found.
  Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
  System info: host: 'ma.local', ip: 'fe80:0:0:0:109f:854e:356e:54af%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.2', java.version: '1.8.0_144'
  Driver info: org.openqa.selenium.safari.SafariDriver
  Capabilities {acceptInsecureCerts: false, browserName: Safari, browserVersion: 12.0.2, javascriptEnabled: true, platform: MAC, platformName: MAC, setWindowRect: true}
  Session ID: BF750CB9-D926-4E11-89F3-1D5F54696341
14:01:34.158 INFO - Executing: [take screenshot])
14:01:34.302 INFO - Done: [take screenshot]
14:01:34.318 INFO - Executing: [get page source])
14:01:34.343 INFO - Done: [get page source]
```
### Details
* Selenium version: 3.8.1
* Codeception version: 2.5.2
* PHP Version: 7.1.9
* Operating System: mac OS Mojave 10.14.2 (18C54)
* List of installed packages 
```bash
behat/gherkin                      v4.5.1  Gherkin DSL parser for PHP 5.3
codeception/codeception            2.5.2   BDD-style testing framework
codeception/phpunit-wrapper        7.6.0   PHPUnit classes used by Codeception
codeception/stub                   2.0.4   Flexible Stub wrapper for PHPUnit's Mock Builder
doctrine/instantiator              1.1.0   A small, lightweight utility to instantiate objects in PHP without invoking their constructors
facebook/webdriver                 1.6.0   A PHP client for Selenium WebDriver
guzzlehttp/guzzle                  6.3.3   Guzzle is a PHP HTTP client library
guzzlehttp/promises                v1.3.1  Guzzle promises library
guzzlehttp/psr7                    1.5.2   PSR-7 message implementation that also provides common utility methods
myclabs/deep-copy                  1.8.1   Create deep copies (clones) of your objects
phar-io/manifest                   1.0.3   Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                    2.0.1   Library for handling version information and constraints
phpdocumentor/reflection-common    1.0.1   Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock  4.3.0   With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that i...
phpdocumentor/type-resolver        0.4.0
phpspec/prophecy                   1.8.0   Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage          6.1.4   Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator          2.0.2   FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template          1.2.1   Simple template engine.
phpunit/php-timer                  2.0.0   Utility class for timing
phpunit/php-token-stream           3.0.1   Wrapper around PHP's tokenizer extension.
phpunit/phpunit                    7.5.1   The PHP Unit Testing framework.
psr/http-message                   1.0.1   Common interface for HTTP messages
ralouphie/getallheaders            2.0.5   A polyfill for getallheaders.
sebastian/code-unit-reverse-lookup 1.0.1   Looks up which function or method a line of code belongs to
sebastian/comparator               3.0.2   Provides the functionality to compare PHP values for equality
sebastian/diff                     3.0.1   Diff implementation
sebastian/environment              4.0.1   Provides functionality to handle HHVM/PHP environments
sebastian/exporter                 3.1.0   Provides the functionality to export PHP variables for visualization
sebastian/global-state             2.0.0   Snapshotting of global state
sebastian/object-enumerator        3.0.3   Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector         1.1.1   Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context        3.0.0   Provides functionality to recursively process PHP variables
sebastian/resource-operations      2.0.1   Provides a list of PHP built-in functions that operate on resources
sebastian/version                  2.0.1   Library that helps with managing the version number of Git-hosted PHP projects
symfony/browser-kit                v4.2.2  Symfony BrowserKit Component
symfony/console                    v4.2.2  Symfony Console Component
symfony/contracts                  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/css-selector               v4.2.2  Symfony CssSelector Component
symfony/dom-crawler                v4.2.2  Symfony DomCrawler Component
symfony/event-dispatcher           v4.2.2  Symfony EventDispatcher Component
symfony/finder                     v4.2.2  Symfony Finder Component
symfony/polyfill-ctype             v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-mbstring          v1.10.0 Symfony polyfill for the Mbstring extension
symfony/process                    v4.2.2  Symfony Process Component
symfony/yaml                       v4.2.2  Symfony Yaml Component
theseer/tokenizer                  1.1.0   A small library for converting tokenized PHP source code into XML and potentially other formats
webmozart/assert                   1.4.0   Assertions to validate method input/output with nice error messages.
```
* Suite configuration:

```yml
config:
                WebDriver:
                    browser: 'safari'
                    window_size: 'maximize'
                    clear_cookies: 'true'
                    wait: '10'
                    capabilities:  
                      platform: 'MAC'
                      unexpectedAlertBehaviour: 'accept'
                      handlesAlerts: 'true'
```
Can someone help me please 🙏

**Comment by Naktibalda** [comment]
Internet agrees with you https://stackoverflow.com/questions/29483701/how-to-upload-a-file-in-safaridriver-safari-using-selenium-webdriver

**Comment by matvey88** [comment]
it's sad
