### ISSUE TITLE
Integration with Codeception Unit Tests - failing due to empty test name passed to the reportportal

### ISSUE THREAD

**Issue by mlukjanska25f** [Codeception/Codeception#5761]
#### What are you trying to achieve?

I was trying out the integration of the codeception (https://github.com/reportportal/agent-php-Codeception) with the reportportal, and the posting to reportportal fails because the test name/description are being passed empty on the post request.

#### What do you get instead?

When running the codeception test I am getting an error - see below

Not sure if the problem is in some changes of codeception that the code to extract test data is not valid anymore or something else: https://github.com/reportportal/agent-php-Codeception/blob/8d21e833de68f9acd22cb129936c427f61604807/src/agentPHPCodeception.php#L153

```bash
<pre>Exception &#039;TypeError&#039; with message &#039;Argument 1 passed to ReportPortalBasic\Service\ReportPortalHTTPService::finishItem() must be of the type string, null given, called in /vendor/reportportal/codeception/src/agentPHPCodeception.php on line 228&#039; 
in /vendor/reportportal/basic/src/service/ReportPortalHTTPService.php:498
Stack trace:
#0 /vendor/reportportal/codeception/src/agentPHPCodeception.php(228): ReportPortalBasic\Service\ReportPortalHTTPService::finishItem(NULL, &#039;STOPPED&#039;, &#039;&#039;)
#1 /vendor/symfony/event-dispatcher/EventDispatcher.php(264): agentPHPCodeception-&gt;afterTestError(Object(Codeception\Event\FailEvent), &#039;test.error&#039;, Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, &#039;test.error&#039;, Object(Codeception\Event\FailEvent))
```
> Super simple test just for testing purposes

```php
<?php

class PassTest extends \Codeception\Test\Unit
{
    /**
     * @var \UnitTester
     */
    protected $tester;

    protected function _before()
    {
    }

    protected function _after()
    {
    }

// tests
    public function testMe()
    {
        $this->assertTrue(1===1);

    }
}
```
### Details

* Codeception version: Codeception PHP Testing Framework v3.1.2
Powered by PHPUnit 8.4.3 by Sebastian Bergmann and contributors.
* Operating System: MacOS
* Installation type: Composer
* List of installed packages (see below)
* Suite configuration:
* Reportportal versions: Current version: Analysis Service: 4.3.0; API Service: 4.3.0; Index Service: 4.2.0; Jira Service: 4.3.0; Rally Service: 4.3.0; Authorization Service: 4.2.0; Service UI: 4.3.0;

```yml
actor: Tester
paths:
    tests: tests
    log: tests/_output
    data: tests/_data
    helpers: tests/_support
settings:
    bootstrap: _bootstrap.php
    memory_limit: -1
    colors: true
    shuffle: true
modules:
    config:
        Yii2:
            configFile: 'config/test.php'
extensions:
    enabled:
        - Codeception\Extension\RunFailed
        - agentPHPCodeception
    config:
        agentPHPCodeception:
            UUID: <UUID>
            host: http://<IP>:8080
            projectName: <projectNam>
            timeZone: .000+00:00
            launchName: launchDataHijack
            launchDescription: testing
```

* composer show:

```bash
amphp/amp                                  v2.4.0              A non-blocking concurrency framework for PHP applications.
amphp/artax                                v3.0.14             Asynchronous parallel HTTP/1.1 client built on the Amp concurrency framework
amphp/byte-stream                          v1.7.1              A stream abstraction to make working with non-blocking I/O simple.
amphp/cache                                v1.2.1              A promise-aware caching API for Amp.
amphp/dns                                  v0.9.15             Async DNS resolution for Amp.
amphp/file                                 v0.3.5              Allows non-blocking access to the filesystem for Amp.
amphp/parallel                             v1.2.0              Parallel processing component for Amp.
amphp/parser                               v1.0.0              A generator parser to make streaming parsers simple.
amphp/process                              v1.1.0              Asynchronous process manager.
amphp/socket                               v0.10.13            Async socket connection / server tools for Amp.
amphp/sync                                 v1.3.0              Mutex, Semaphore, and other synchronization tools for Amp.
amphp/uri                                  v0.1.4              Uri Parser and Resolver.
amphp/windows-registry                     v0.3.2              Windows Registry Reader.
auth0/auth0-php                            5.6.0               Auth0 PHP SDK.
aws/aws-sdk-php                            3.121.1             AWS SDK for PHP - Use Amazon Web Services in your PHP project
beberlei/assert                            v2.9.9              Thin assertion library for input validation in business models.
behat/gherkin                              v4.6.0              Gherkin DSL parser for PHP 5.3
bower-asset/bootstrap                      v3.4.1             
bower-asset/codemirror                     5.49.2             
bower-asset/inputmask                      3.3.11              Inputmask is a javascript library which creates an input mask.  Inputmask can run against vanilla javascript, jQuery and jqlite.
bower-asset/jquery                         3.4.1              
bower-asset/jquery-ui                      1.12.1             
bower-asset/punycode                       v1.3.2             
bower-asset/yii2-pjax                      2.0.7.1            
bramus/ansi-php                            3.0.2               ANSI Control Functions and ANSI Control Sequences (Colors, Erasing, etc.) for PHP CLI Apps
bramus/monolog-colored-line-formatter      3.0.1               Colored Line Formatter for Monolog
cakebake/yii2-less.php                     dev-master 722cd97  This is a Yii2 wrapper extension for PHP port of the official LESS processor http://lesscss.org.
calcinai/xero-php                          dev-master 66f8d5c  A client implementation of the Xero API, with a cleaner OAuth interface and ORM-like abstraction.
cebe/markdown                              1.2.1               A super fast, highly extensible markdown parser for PHP
cetver/yii2-language-url-manager           1.0.2               Parses and creates URLs containing languages for the Yii framework 2.0
clue/stream-filter                         v1.4.1              A simple and modern approach to stream filtering in PHP
codacy/coverage                            1.4.2               Sends PHP test coverage information to Codacy.
codeception/base                           3.1.2               BDD-style testing framework
codeception/codeception                    3.1.2               BDD-style testing framework
codeception/phpunit-wrapper                8.0.4               PHPUnit classes used by Codeception
codeception/stub                           3.5.0               Flexible Stub wrapper for PHPUnit's Mock Builder
codemix/yii2-excelexport                   2.7.2               A utility to quickly create Excel files from query results or raw data
composer/ca-bundle                         1.2.4               Lets you find a path to the system CA bundle, and includes a fallback to the Mozilla CA bundle.
conquer/codemirror                         2.0.1               Yii2 codemirror widget
conquer/helpers                            2.0.13              Yii2 helpers
cozumel/yii2-image-cropper                 1.0.0               A simple wrapper for the imgAreaSelect jquery plugin
daverandom/libdns                          v2.0.1              DNS protocol implementation written in pure PHP
doctrine/instantiator                      1.3.0               A small, lightweight utility to instantiate objects in PHP without invoking their constructors
doctrine/lexer                             1.2.0               PHP Doctrine Lexer parser library that can be used in Top-Down, Recursive Descent Parsers.
egulias/email-validator                    2.1.11              A library for validating emails against several RFCs
ezyang/htmlpurifier                        v4.12.0             Standards compliant HTML filter written in PHP
facebook/webdriver                         1.7.1               A PHP client for Selenium WebDriver
fadion/fixerio                             2.0.0               Wrapper for Fixer.io
firebase/php-jwt                           v5.0.0              A simple library to encode and decode JSON Web Tokens (JWT) in PHP. Should conform to the current spec.
fortawesome/font-awesome                   5.11.2              The iconic font, CSS, and SVG framework
froala/wysiwyg-editor                      v3.0.4              A beautiful jQuery WYSIWYG HTML rich text editor. High performance and modern design make it easy to use for developers and lo...
froala/yii2-froala-editor                  3.0.4               A beautiful WYSIWYG HTML text editor based on HTML5 technology. Cross browser, with mobile support, high performance and Retin...
fzaninotto/faker                           v1.9.0              Faker is a PHP library that generates fake data for you.
gitonomy/gitlib                            v1.1.0              Library for accessing git
gregwar/cache                              v1.0.12             A lightweight file-system cache system
gregwar/image                              v2.0.25             Image handling
guzzlehttp/guzzle                          6.4.1               Guzzle is a PHP HTTP client library
guzzlehttp/promises                        v1.3.1              Guzzle promises library
guzzlehttp/psr7                            1.6.1               PSR-7 message implementation that also provides common utility methods
hisamu/php-xbase                           1.0.6               A simple parser for *.dbf, *.fpt files using PHP
hoa/consistency                            1.17.05.02          The Hoa\Consistency library.
hoa/console                                3.17.05.02          The Hoa\Console library.
hoa/event                                  1.17.01.13          The Hoa\Event library.
hoa/exception                              1.17.01.16          The Hoa\Exception library.
hoa/file                                   1.17.07.11          The Hoa\File library.
hoa/iterator                               2.17.01.10          The Hoa\Iterator library.
hoa/protocol                               1.17.01.14          The Hoa\Protocol library.
hoa/stream                                 1.17.02.21          The Hoa\Stream library.
hoa/ustring                                4.17.01.16          The Hoa\Ustring library.
http-interop/http-factory-guzzle           1.0.0               An HTTP Factory using Guzzle PSR7
ibericode/vat                              1.2.1               PHP library for dealing with VAT in Europe
imagine/imagine                            1.2.2               Image processing for PHP 5.3
ircmaxell/security-lib                     v1.1.0              A Base Security Library
jakub-onderka/php-parallel-lint            v1.0.0              This tool check syntax of PHP files about 20x faster than serial check.
jean85/pretty-package-versions             1.2                 A wrapper for ocramius/package-versions to get pretty versions strings
karriere/json-decoder                      v2.2.1              JsonDecoder implementation that allows you to convert your JSON data into PHP class objects
kartik-v/bootstrap-fileinput               v4.5.3              An enhanced HTML 5 file input for Bootstrap 3.x with features for file preview for many file types, multiple selection, ajax u...
kartik-v/bootstrap-star-rating             v4.0.6              A simple yet powerful JQuery star rating plugin for Bootstrap.
kartik-v/dependent-dropdown                v1.4.9              A multi level dependent dropdown JQuery plugin that allows nested dependencies.
kartik-v/php-date-formatter                v1.3.5              A Javascript datetime formatting and manipulation library using PHP date-time formats.
kartik-v/yii2-datecontrol                  dev-master bf6a5fc  Date control module allowing separation of formats for View and Model for Yii Framework 2.0
kartik-v/yii2-dialog                       v1.0.4              An asset bundle for bootstrap3-dialog for Yii 2.0 framework.
kartik-v/yii2-grid                         dev-master e889dd7  Yii 2 GridView on steroids. Various enhancements and utilities for the Yii 2.0 GridView widget.
kartik-v/yii2-krajee-base                  v1.9.9              Base library and foundation components for all Yii2 Krajee extensions.
kartik-v/yii2-slider                       dev-master ef1df56  An advanced slider input for Yii Framework 2 for both touch enabled and desktop devices based on bootstrap-slider.
kartik-v/yii2-sortable                     v1.2.1              Create sortable lists and grids using HTML5 drag and drop API for Yii 2.0.
kartik-v/yii2-widget-activeform            v1.5.8              Enhanced Yii2 active-form and active-field with full bootstrap styling support (sub repo split from yii2-widgets).
kartik-v/yii2-widget-affix                 v1.0.0              A scrollspy and affixed enhanced navigation to highlight page sections (sub repo split from yii2-widgets)
kartik-v/yii2-widget-alert                 v1.1.1              A widget to generate alert based notifications using bootstrap-alert plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-colorinput            v1.0.5              An enhanced Yii 2 widget encapsulating the HTML 5 color input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-datepicker            v1.4.6              Enhanced Yii2 wrapper for the bootstrap datepicker plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-datetimepicker        v1.4.7              Enhanced Yii2 wrapper for the bootstrap datetimepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-depdrop               v1.0.4              Widget that enables setting up dependent dropdowns with nested dependencies (sub repo split from yii2-widgets)
kartik-v/yii2-widget-fileinput             v1.0.4              An enhanced FileInput widget for Bootstrap 3.x with file preview, multiple selection, and more features (sub repo split from y...
kartik-v/yii2-widget-growl                 v1.1.1              A widget to generate growl based notifications using bootstrap-growl plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rangeinput            v1.0.2              An enhanced Yii 2 widget encapsulating the HTML 5 range input (sub repo split from yii2-widgets)
kartik-v/yii2-widget-rating                v1.0.4              A Yii2 widget for the simple yet powerful bootstrap-star-rating plugin with fractional rating support (sub repo split from yii...
kartik-v/yii2-widget-select2               dev-master b8cdb76  Enhanced Yii2 wrapper for the Select2 jQuery plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widget-sidenav               v1.0.0              An enhanced side navigation menu styled for bootstrap (sub repo split from yii2-widgets)
kartik-v/yii2-widget-spinner               v1.0.0              A widget to render animated CSS3 loading spinners with VML fallback for IE (sub repo split from yii2-widgets)
kartik-v/yii2-widget-switchinput           v1.3.1              A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle switchinputes (sub repo split from ...
kartik-v/yii2-widget-timepicker            v1.0.3              Enhanced Yii2 wrapper for the bootstrap timepicker plugin (sub repo split from yii2-widgets)
kartik-v/yii2-widget-touchspin             v1.2.3              A Yii2 wrapper widget for the Bootstrap Switch plugin to use checkboxes & radios as toggle touchspines (sub repo split from yi...
kartik-v/yii2-widget-typeahead             v1.0.2              Enhanced Yii2 wrapper for the Twitter Typeahead plugin (sub repo split from yii2-widgets).
kartik-v/yii2-widgets                      v3.4.1              Collection of useful widgets for Yii Framework 2.0 extending functionalities for Bootstrap
kelunik/certificate                        v1.1.2              Access certificate details and transform between different formats.
kriswallsmith/buzz                         1.0.1               Lightweight HTTP client
league/csv                                 9.4.1               Csv data manipulation made easy in PHP
league/flysystem                           1.0.57              Filesystem abstraction: Many filesystems, one API.
league/flysystem-aws-s3-v3                 1.0.23              Flysystem adapter for the AWS S3 SDK v3.x
league/iso3166                             2.1.4               ISO 3166-1 PHP Library
league/oauth2-client                       2.4.1               OAuth 2.0 Client Library
mailgun/mailgun-php                        2.8.1               The Mailgun SDK provides methods for all API functions.
mandrill/mandrill                          1.0.55              API client library for the Mandrill email as a service platform
mikehaertl/php-tmpfile                     1.1.1               A convenience class for temporary files
mollie/mollie-api-php                      v2.12.0             Mollie API client library for PHP. Mollie is a European Payment Service provider and offers international payment methods such...
mongosoft/yii2-mongodate-behavior          0.2.0               MongoDate behavior for Yii 2
monolog/monolog                            1.25.2              Sends your logs to files, sockets, inboxes, databases and various web services
mpclarkson/freshdesk-php-sdk               0.3.1               PHP SDK for the Freshdesk API (v2)
mtdowling/cron-expression                  v1.2.1              CRON for PHP: Calculate the next or previous run date and determine if a CRON expression is due
mtdowling/jmespath.php                     2.4.0               Declaratively specify how to extract elements from a JSON document
mve-it-solutions/yii2-google-code-prettify 0.0.1               Yii2 Code syntax highlighter using Google Code Prettify
myclabs/deep-copy                          1.9.3               Create deep copies (clones) of your objects
myclabs/php-enum                           1.7.2               PHP Enum implementation
nategood/httpful                           0.2.20              A Readable, Chainable, REST friendly, PHP HTTP Client
nette/utils                                v3.0.2              🛠 Nette Utils: lightweight utilities for string & array manipulation, image handling, safe JSON encoding/decoding, validati...
nickcv/yii2-encrypter                      1.1.0               Openssl Encrypter for Yii2
notamedia/yii2-sentry                      1.4.1               Yii2 logger for Sentry
nyholm/psr7                                1.2.1               A fast PHP7 implementation of PSR-7
ocramius/package-versions                  1.4.2               Composer plugin that provides efficient querying for installed package versions (no runtime IO)
opis/closure                               3.4.1               A library that can be used to serialize closures (anonymous functions) and arbitrary objects.
oyejorge/less.php                          v1.7.0.14           PHP port of the Javascript version of LESS http://lesscss.org (Originally maintained by Josh Schmidt)
paragonie/constant_time_encoding           v2.3.0              Constant-time Implementations of RFC 4648 Encoding (Base-64, Base-32, Base-16)
paragonie/random-lib                       v2.0.0              A Library For Generating Secure Random Numbers
paragonie/random_compat                    v2.0.18             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
paragonie/sodium_compat                    v1.12.1             Pure PHP implementation of libsodium; uses the PHP extension if it exists
pelago/emogrifier                          v3.0.0              Converts CSS styles into inline style attributes in your HTML code
phar-io/manifest                           1.0.3               Component for reading phar.io manifest information from a PHP Archive (PHAR)
phar-io/version                            2.0.1               Library for handling version information and constraints
php-http/client-common                     1.10.0              Common HTTP Client implementations and tools for HTTPlug
php-http/curl-client                       v1.7.1              cURL client for PHP-HTTP
php-http/discovery                         1.7.0               Finds installed HTTPlug implementations and PSR-7 message factories
php-http/httplug                           v1.1.0              HTTPlug, the HTTP client abstraction for PHP
php-http/message                           1.8.0               HTTP Message related tools
php-http/message-factory                   v1.0.2              Factory interfaces for PSR-7 HTTP Message
php-http/multipart-stream-builder          1.1.0               A builder class that help you create a multipart stream
php-http/promise                           v1.0.0              Promise used for asynchronous HTTP requests
php-vcr/php-vcr                            1.4.4               Record your test suite's HTTP interactions and replay them during future test runs for fast, deterministic, accurate tests.
phpdocumentor/reflection-common            2.0.0               Common reflection classes used by phpdocumentor to reflect the code structure
phpdocumentor/reflection-docblock          4.3.2               With this component, a library can provide support for annotations via DocBlocks or otherwise retrieve information that is emb...
phpdocumentor/type-resolver                1.0.1               A PSR-5 based resolver of Class names, Types and Structural Element Names
phploc/phploc                              5.0.0               A tool for quickly measuring the size of a PHP project.
phpmailer/phpmailer                        v6.1.3              PHPMailer is a full-featured email creation and transfer class for PHP
phpoffice/phpexcel                         1.8.2               PHPExcel - OpenXML - Read, Create and Write Spreadsheet documents in PHP - Spreadsheet engine
phpspec/php-diff                           v1.1.0              A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/prophecy                           1.9.0               Highly opinionated mocking framework for PHP 5.3+
phpunit/php-code-coverage                  7.0.10              Library that provides collection, processing, and rendering functionality for PHP code coverage information.
phpunit/php-file-iterator                  2.0.2               FilterIterator implementation that filters files based on a list of suffixes.
phpunit/php-text-template                  1.2.1               Simple template engine.
phpunit/php-timer                          2.1.2               Utility class for timing
phpunit/php-token-stream                   3.1.1               Wrapper around PHP's tokenizer extension.
phpunit/phpunit                            8.4.3               The PHP Unit Testing framework.
picqer/api-client                          v0.13.3             A PHP Client for the Picqer API
picqer/exact-php-client                    v3.22.0             A PHP Client for the Exact API
picqer/moneybird-php-client                v0.12.0             A PHP Client for the Moneybird V2 API
pragmarx/google2fa                         v4.0.2              A One Time Password Authentication package, compatible with Google Authenticator.
psr/container                              1.0.0               Common Container Interface (PHP FIG PSR-11)
psr/http-client                            1.0.0               Common interface for HTTP clients
psr/http-factory                           1.0.1               Common interfaces for PSR-7 HTTP message factories
psr/http-message                           1.0.1               Common interface for HTTP messages
psr/log                                    1.1.2               Common interface for logging libraries
psr/simple-cache                           1.0.1               Common interfaces for simple caching
ralouphie/getallheaders                    3.0.3               A polyfill for getallheaders.
ramsey/uuid                                3.8.0               Formerly rhumsaa/uuid. A PHP 5.4+ library for generating RFC 4122 version 1, 3, 4, and 5 universally unique identifiers (UUID).
reportportal/basic                         1.0.x-dev b68c2e1   Basic classes for Report Portal collaboration
reportportal/codeception                   1.0.x-dev 0151bac   Specific classes to integrate Codeception-based test framework with Report Portal (http://reportportal.io/).
rmrevin/yii2-fontawesome                   3.4.0               Asset Bundle for Yii2 with Font Awesome
sebastian/code-unit-reverse-lookup         1.0.1               Looks up which function or method a line of code belongs to
sebastian/comparator                       3.0.2               Provides the functionality to compare PHP values for equality
sebastian/diff                             3.0.2               Diff implementation
sebastian/environment                      4.2.3               Provides functionality to handle HHVM/PHP environments
sebastian/exporter                         3.1.2               Provides the functionality to export PHP variables for visualization
sebastian/finder-facade                    1.2.2               FinderFacade is a convenience wrapper for Symfony's Finder component.
sebastian/global-state                     3.0.0               Snapshotting of global state
sebastian/object-enumerator                3.0.3               Traverses array structures and object graphs to enumerate all referenced objects
sebastian/object-reflector                 1.1.1               Allows reflection of object attributes, including inherited and non-public ones
sebastian/recursion-context                3.0.0               Provides functionality to recursively process PHP variables
sebastian/resource-operations              2.0.1               Provides a list of PHP built-in functions that operate on resources
sebastian/type                             1.1.3               Collection of value objects that represent the types of the PHP type system
sebastian/version                          2.0.1               Library that helps with managing the version number of Git-hosted PHP projects
select2/select2                            4.0.12              Select2 is a jQuery based replacement for select boxes.
sentry/sdk                                 2.0.4               This is a metapackage shipping sentry/sentry with a recommended http client.
sentry/sentry                              2.2.4               A PHP SDK for Sentry (http://sentry.io)
servo/fluidxml                             1.21                Concise and fluent XML manipulation library
spatie/async                               1.0.4               Asynchronous and parallel PHP with the PCNTL extension
squizlabs/php_codesniffer                  3.5.2               PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
swiftmailer/swiftmailer                    v6.2.3              Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                        v4.4.0              Symfony BrowserKit Component
symfony/console                            v4.4.0              Symfony Console Component
symfony/css-selector                       v4.4.0              Symfony CssSelector Component
symfony/dom-crawler                        v4.4.0              Symfony DomCrawler Component
symfony/event-dispatcher                   v4.4.0              Symfony EventDispatcher Component
symfony/event-dispatcher-contracts         v1.1.7              Generic abstractions related to dispatching event
symfony/finder                             v4.4.0              Symfony Finder Component
symfony/inflector                          v5.0.0              Symfony Inflector Component
symfony/options-resolver                   v4.4.0              Symfony OptionsResolver Component
symfony/polyfill-ctype                     v1.12.0             Symfony polyfill for ctype functions
symfony/polyfill-iconv                     v1.12.0             Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn                  v1.12.0             Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring                  v1.12.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                     v1.12.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php72                     v1.12.0             Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73                     v1.12.0             Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-util                      v1.12.0             Symfony utilities for portability of PHP codes
symfony/process                            v4.4.0              Symfony Process Component
symfony/property-access                    v5.0.0              Symfony PropertyAccess Component
symfony/service-contracts                  v2.0.0              Generic abstractions related to writing services
symfony/stopwatch                          v4.4.0              Symfony Stopwatch Component
symfony/var-dumper                         v4.4.0              Symfony mechanism for exploring and dumping PHP variables
symfony/workflow                           v4.4.0              Symfony Workflow Component
symfony/yaml                               v4.4.0              Symfony Yaml Component
theiconic/name-parser                      v1.2.11             PHP library for parsing a string containing a full name into its parts
theseer/fdomdocument                       1.6.6               The classes contained within this repository extend the standard DOM to use exceptions at all occasions of errors instead of P...
theseer/tokenizer                          1.1.3               A small library for converting tokenized PHP source code into XML and potentially other formats
tpmanc/yii2-imagick                        1.3.1               Yii 2 class for working with Imagick
vxm/yii2-async                             1.0.3               Provide an easy way to run code asynchronously for Yii2 application
webmozart/assert                           1.5.0               Assertions to validate method input/output with nice error messages.
yiisoft/yii2                               2.0.30              Yii PHP Framework Version 2
yiisoft/yii2-authclient                    2.2.6               External authentication via OAuth and OpenID for the Yii framework
yiisoft/yii2-bootstrap                     2.0.10              The Twitter Bootstrap extension for the Yii framework
yiisoft/yii2-composer                      2.0.8               The composer plugin for Yii extension installer
yiisoft/yii2-debug                         2.1.12              The debugger extension for the Yii framework
yiisoft/yii2-faker                         2.0.4               Fixture generator. The Faker integration for the Yii framework.
yiisoft/yii2-gii                           2.1.3               The Gii extension for the Yii framework
yiisoft/yii2-httpclient                    2.0.12              HTTP client extension for the Yii framework
yiisoft/yii2-imagine                       2.2.0               The Imagine integration for the Yii framework
yiisoft/yii2-jui                           2.0.7               The Jquery UI extension for the Yii framework
yiisoft/yii2-mongodb                       2.1.9               MongoDB extension for the Yii framework
yiisoft/yii2-redis                         2.0.11              Redis Cache, Session and ActiveRecord for the Yii framework
yiisoft/yii2-swiftmailer                   2.1.2               The SwiftMailer integration for the Yii framework
zendframework/zend-diactoros               2.2.1               PSR HTTP Message implementations

```

**Comment by Naktibalda** [comment]
This is clearly an issue of agent-php-codeception library.
I haven't heard about it before, it would be betters to raise an issue with maintainer of that library or in some report portal community channel. (It is strange that issues page is disabled in https://github.com/reportportal/agent-php-Codeception)

**Comment by mlukjanska25f** [comment]
Thanks!

Raised an issue there, too: https://github.com/reportportal/reportportal/issues/757

**Comment by mlukjanska25f** [comment]
It looks like the issue is with the **UnitTester** - in the following case the highlighted call does not return the name of the unit test that is being run.

```php
    public function beforeTest(TestEvent $e)
    {
        $this->stepCounter = 0;
        $testName = **$e->getTest()->getMetadata()->getName();**
        ...
    }
```

The Acceptance tests though are working as expected and this method returns the test name and hence is correctly posted to the Report portal.

So it seems that the events data and methods for UnitTester and Acceptance tests are different.
Shall I refer to PHPUnit then if I want to integrate UnitTests with Reportpotal (ie build similar agent)?

**Comment by Naktibalda** [comment]
Metadata is a feature of Codeception,
Test formats are implemented in https://github.com/Codeception/Codeception/tree/4.0/src/Codeception/Test
Other test formats setName in constructor, Unit format has no constructor, but inherits it from PHPUnit\Framework\TestCase.

I think that you could use this method instead: https://github.com/Codeception/Codeception/blob/4.0/src/Codeception/Test/Descriptor.php#L16-L24
