### ISSUE TITLE
Exception: Argument 2 passed to EventDispatcher::dispatch() must be an instance of Event or null, string given

### ISSUE THREAD

**Issue by davidsneighbour** [Codeception/Codeception#5796]
#### What are you trying to achieve?

- following the Quick Start documentation
- run vendor/bin/codecept run --steps

#### What do you get instead?

```bash
❯ vendor/bin/codecept run --steps -vvv
Codeception PHP Testing Framework v4.0.0
Powered by PHPUnit 8.5.0 by Sebastian Bergmann and contributors.
Running with seed: 

PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, string given, called in /home/patrick/Projects/BooKa/app/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php on line 20 and defined in /home/patrick/Projects/BooKa/app/vendor/symfony/event-dispatcher/EventDispatcher.php:37
Stack trace:
#0 /home/patrick/Projects/BooKa/app/vendor/codeception/codeception/src/Codeception/Event/DispatcherWrapper.php(20): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#1 /home/patrick/Projects/BooKa/app/vendor/codeception/codeception/src/Codeception/SuiteManager.php(81): Codeception\SuiteManager->dispatch()
#2 /home/patrick/Projects/BooKa/app/vendor/codeception/codeception/src/Codeception/Codecept.php(191): Codeception\SuiteManager->initialize()
#3 /home/patrick/Projects/BooKa/app/vendor/codeception/codeception/src/Codeception/Codecept.php(162): Codeception\Codecept->runSu in /home/patrick/Projects/BooKa/app/vendor/symfony/event-dispatcher/EventDispatcher.php on line 37

```

### Details

* Codeception version: latest 3 and also version 4, newly installed
* PHP Version: 7.4
* Operating System: Ubuntu 1910
* Installation type: Composer
* Suite configuration: default that was created by init.
* List of installed packages (`composer show`)

```
❯ composer show
adodb/adodb-php                       v5.20.15           ADOdb is a PHP database abstraction lay...
amphp/amp                             v2.4.0             A non-blocking concurrency framework fo...
amphp/byte-stream                     v1.7.1             A stream abstraction to make working wi...
bacon/bacon-qr-code                   1.0.3              BaconQrCode is a QR code generator for ...
behat/gherkin                         v4.6.0             Gherkin DSL parser for PHP 5.3
bgalati/monolog-sentry-handler        1.2.1              Sentry handler for php SDK
clue/stream-filter                    v1.4.1             A simple and modern approach to stream ...
codacy/coverage                       1.4.2              Sends PHP test coverage information to ...
codeception/codeception               4.0.0              BDD-style testing framework
codeception/lib-asserts               1.10.1             Assertion methods used by Codeception c...
codeception/lib-innerbrowser          1.2.3              Parent library for all Codeception fram...
codeception/module-asserts            1.1.1              Codeception module containing various a...
codeception/module-db                 1.0.1              WebDriver module for Codeception
codeception/module-phpbrowser         1.0.0              Codeception module for testing web appl...
codeception/module-rest               1.0.0              REST module for Codeception
codeception/module-webdriver          1.0.0              WebDriver module for Codeception
codeception/phpunit-wrapper           8.1.0              PHPUnit classes used by Codeception
codeception/stub                      3.6.0              Flexible Stub wrapper for PHPUnit's Moc...
composer/ca-bundle                    1.2.5              Lets you find a path to the system CA b...
composer/semver                       1.5.0              Semver library that offers utilities, v...
composer/xdebug-handler               1.4.0              Restarts a process without Xdebug.
davidsneighbour/dropbox-php-sdk       v0.2.4             Dropbox PHP API V2 SDK (Unofficial, for...
doctrine/annotations                  v1.8.0             Docblock Annotations Parser
doctrine/cache                        1.10.0             PHP Doctrine Cache library is a popular...
doctrine/collections                  1.6.4              PHP Doctrine Collections library that a...
doctrine/common                       v2.11.0            PHP Doctrine Common project is a librar...
doctrine/dbal                         v2.10.0            Powerful PHP database abstraction layer...
doctrine/event-manager                1.1.0              The Doctrine Event Manager is a simple ...
doctrine/inflector                    1.3.1              Common String Manipulations with regard...
doctrine/instantiator                 1.3.0              A small, lightweight utility to instant...
doctrine/lexer                        1.2.0              PHP Doctrine Lexer parser library that ...
doctrine/orm                          v2.7.0             Object-Relational-Mapper for PHP
doctrine/persistence                  1.3.3              The Doctrine Persistence project is a s...
doctrine/reflection                   v1.0.0             Doctrine Reflection component
edsonmedina/php_testability           dev-master d970a12 Analyses and reports testability issues...
egeniq/monolog-gdpr                   1.0.0              Some Monolog processors that will help ...
egulias/email-validator               2.1.12             A library for validating emails against...
endroid/qr-code                       2.5.1              Endroid QR Code
fabian-tomischka/php-avatar-generator dev-master 2fb20d0 Easily create user avatars based on pro...
facebook/webdriver                    1.7.1              A PHP client for Selenium WebDriver
felixfbecker/advanced-json-rpc        v3.0.4             A more advanced JSONRPC implementation
felixfbecker/language-server-protocol v1.4.0             PHP classes for the Language Server Pro...
florianv/exchanger                    2.3.1              Currency exchange rates framework for PHP
florianv/swap                         4.0.1              Exchange rates library for PHP
flow/jsonpath                         0.4.0              JSONPath implementation for parsing, se...
gitonomy/gitlib                       v1.2.0             Library for accessing git
guzzlehttp/guzzle                     6.5.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                   v1.3.1             Guzzle promises library
guzzlehttp/psr7                       1.6.1              PSR-7 message implementation that also ...
henrikbjorn/lurker                    1.2.0              Resource Watcher.
http-interop/http-factory-guzzle      1.0.0              An HTTP Factory using Guzzle PSR7
intervention/image                    2.5.1              Image handling and manipulation library...
jakub-onderka/php-var-dump-check      v0.3               Find forgotten variables dump in PHP so...
jean85/pretty-package-versions        1.2                A wrapper for ocramius/package-versions...
jeremeamia/superclosure               2.4.0              Serialize Closure objects, including th...
kevinlebrun/colors.php                0.4.1              Colors for PHP CLI scripts
khanamiryan/qrcode-detector-decoder   1                  QR code decoder / reader
lavary/crunz                          v2.0.4             Schedule your tasks right from the code.
league/event                          2.2.0              Event package
league/flysystem                      1.0.61             Filesystem abstraction: Many filesystem...
league/fractal                        0.17.0             Handle the output of complex data struc...
league/glide                          1.5.0              Wonderfully easy on-demand image manipu...
league/iso3166                        2.1.4              ISO 3166-1 PHP Library
league/period                         4.9.0              Time range API for PHP
luracast/restler                      3.0.0-RC6          Restler is a simple and effective multi...
markbaker/complex                     1.4.7              PHP Class for working with complex numbers
markbaker/matrix                      1.2.0              PHP Class for working with matrices
michelf/php-markdown                  1.9.0              PHP Markdown
microsoft/tolerant-php-parser         v0.0.18            Tolerant PHP-to-AST parser designed for...
moneyphp/money                        v3.2.1             PHP implementation of Fowler's Money pa...
monolog/monolog                       1.25.3             Sends your logs to files, sockets, inbo...
mpdf/mpdf                             v8.0.4             PHP library generating PDF files from U...
mpdf/qrcode                           v1.0.0             QR code generator for mPDF
mremi/url-shortener                   v2.2.1             A PHP5 library using API to shorten/exp...
mtdowling/cron-expression             v1.2.1             CRON for PHP: Calculate the next or pre...
mustache/mustache                     v2.13.0            A Mustache implementation in PHP.
myclabs/deep-copy                     1.9.4              Create deep copies (clones) of your obj...
myclabs/php-enum                      1.7.2              PHP Enum implementation
nategood/commando                     0.4.0              PHP CLI Commando Style
nesbot/carbon                         2.28.0             An API extension for DateTime that supp...
netresearch/jsonmapper                v1.6.0             Map nested JSON structures onto PHP cla...
niels-de-blaauw/php-doc-check         v0.2.2             Command line tool that identifies code ...
nikic/php-parser                      v4.3.0             A PHP parser written in PHP
ocramius/package-versions             1.5.1              Composer plugin that provides efficient...
omise/omise-php                       v2.11.2            A PHP library designed specifically to ...
openlss/lib-array2xml                 1.0.0              Array2XML conversion library credit to ...
paragonie/constant_time_encoding      v2.3.0             Constant-time Implementations of RFC 46...
paragonie/csp-builder                 v2.4.0             Easily add and update Content-Security-...
paragonie/random_compat               v9.99.99           PHP 5.x polyfill for random_bytes() and...
phan/phan                             2.4.5              A static analyzer for PHP
phar-io/manifest                      1.0.3              Component for reading phar.io manifest ...
phar-io/version                       2.0.1              Library for handling version informatio...
php-http/client-common                1.10.0             Common HTTP Client implementations and ...
php-http/curl-client                  v1.7.1             cURL client for PHP-HTTP
php-http/discovery                    1.7.0              Finds installed HTTPlug implementations...
php-http/httplug                      v1.1.0             HTTPlug, the HTTP client abstraction fo...
php-http/message                      1.8.0              HTTP Message related tools
php-http/message-factory              v1.0.2             Factory interfaces for PSR-7 HTTP Message
php-http/promise                      v1.0.0             Promise used for asynchronous HTTP requ...
phpdocumentor/reflection-common       2.0.0              Common reflection classes used by phpdo...
phpdocumentor/reflection-docblock     4.3.3              With this component, a library can prov...
phpdocumentor/type-resolver           1.0.1              A PSR-5 based resolver of Class names, ...
phpoffice/phpspreadsheet              1.10.1             PHPSpreadsheet - Read, Create and Write...
phpspec/prophecy                      1.10.0             Highly opinionated mocking framework fo...
phpstan/extension-installer           1.0.3              Composer plugin for automatic installat...
phpstan/phpstan                       0.12.3             PHPStan - PHP Static Analysis Tool
phpstan/phpstan-deprecation-rules     0.12.0             PHPStan rules for detecting usage of de...
phpstan/phpstan-phpunit               0.12.3             PHPUnit extensions and rules for PHPStan
phpstan/phpstan-strict-rules          0.12.0             Extra strict and opinionated rules for ...
phpunit/php-code-coverage             7.0.10             Library that provides collection, proce...
phpunit/php-file-iterator             2.0.2              FilterIterator implementation that filt...
phpunit/php-text-template             1.2.1              Simple template engine.
phpunit/php-timer                     2.1.2              Utility class for timing
phpunit/php-token-stream              3.1.1              Wrapper around PHP's tokenizer extension.
phpunit/phpunit                       8.5.0              The PHP Unit Testing framework.
picqer/php-barcode-generator          v0.3               An easy to use, non-bloated, barcode ge...
psr/cache                             1.0.1              Common interface for caching libraries
psr/container                         1.0.0              Common Container Interface (PHP FIG PSR...
psr/http-factory                      1.0.1              Common interfaces for PSR-7 HTTP messag...
psr/http-message                      1.0.1              Common interface for HTTP messages
psr/log                               1.1.2              Common interface for logging libraries
psr/simple-cache                      1.0.1              Common interfaces for simple caching
ralouphie/getallheaders               3.0.3              A polyfill for getallheaders.
ramsey/uuid                           3.9.2              Formerly rhumsaa/uuid. A PHP 5.4+ libra...
roave/security-advisories             dev-master a115a27 Prevents installation of composer packa...
sabre/event                           5.0.3              sabre/event is a library for lightweigh...
sebastian/code-unit-reverse-lookup    1.0.1              Looks up which function or method a lin...
sebastian/comparator                  3.0.2              Provides the functionality to compare P...
sebastian/diff                        3.0.2              Diff implementation
sebastian/environment                 4.2.3              Provides functionality to handle HHVM/P...
sebastian/exporter                    3.1.2              Provides the functionality to export PH...
sebastian/global-state                3.0.0              Snapshotting of global state
sebastian/object-enumerator           3.0.3              Traverses array structures and object g...
sebastian/object-reflector            1.1.1              Allows reflection of object attributes,...
sebastian/recursion-context           3.0.0              Provides functionality to recursively p...
sebastian/resource-operations         2.0.1              Provides a list of PHP built-in functio...
sebastian/type                        1.1.3              Collection of value objects that repres...
sebastian/version                     2.0.1              Library that helps with managing the ve...
sendgrid/php-http-client              3.10.0             HTTP REST client, simplified for PHP
sendgrid/sendgrid                     7.2.1              This library allows you to quickly and ...
sensiolabs/security-checker           v5.0.3             A security checker for your composer.lock
sentry/sdk                            2.0.4              This is a metapackage shipping sentry/s...
sentry/sentry                         2.2.6              A PHP SDK for Sentry (http://sentry.io)
setasign/fpdi                         v2.2.0             FPDI is a collection of PHP classes fac...
smarty/smarty                         v3.1.34            Smarty - the compiling PHP template engine
swiftmailer/swiftmailer               v6.2.3             Swiftmailer, free feature-rich PHP mailer
symfony/browser-kit                   v5.0.2             Symfony BrowserKit Component
symfony/config                        v3.4.36            Symfony Config Component
symfony/console                       v4.2.12            Symfony Console Component
symfony/contracts                     v1.1.8             A set of abstractions extracted out of ...
symfony/css-selector                  v5.0.2             Symfony CssSelector Component
symfony/dependency-injection          v3.4.36            Symfony DependencyInjection Component
symfony/dom-crawler                   v5.0.2             Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.36            Symfony EventDispatcher Component
symfony/filesystem                    v4.4.2             Symfony Filesystem Component
symfony/finder                        v5.0.2             Symfony Finder Component
symfony/lock                          v4.4.2             Symfony Lock Component
symfony/options-resolver              v2.8.52            Symfony OptionsResolver Component
symfony/polyfill-ctype                v1.13.1            Symfony polyfill for ctype functions
symfony/polyfill-iconv                v1.13.1            Symfony polyfill for the Iconv extension
symfony/polyfill-intl-idn             v1.13.1            Symfony polyfill for intl's idn_to_asci...
symfony/polyfill-mbstring             v1.13.1            Symfony polyfill for the Mbstring exten...
symfony/polyfill-php56                v1.13.1            Symfony polyfill backporting some PHP 5...
symfony/polyfill-php72                v1.13.1            Symfony polyfill backporting some PHP 7...
symfony/polyfill-util                 v1.13.1            Symfony utilities for portability of PH...
symfony/process                       v4.4.2             Symfony Process Component
symfony/property-access               v2.8.52            Symfony PropertyAccess Component
symfony/translation                   v4.4.2             Symfony Translation Component
symfony/var-dumper                    v4.4.2             Symfony mechanism for exploring and dum...
symfony/yaml                          v4.4.2             Symfony Yaml Component
thecodingmachine/phpstan-strict-rules v0.12.0            A set of additional rules for PHPStan b...
thecodingmachine/safe                 v0.1.16            PHP core functions that throw exception...
theseer/tokenizer                     1.1.3              A small library for converting tokenize...
tightenco/collect                     v5.8.35            Collect - Illuminate Collections as a s...
ulrichsg/getopt-php                   v3.3.0             Command line arguments parser for PHP 5...
vimeo/psalm                           3.7.2              A static analysis tool for finding erro...
webmozart/assert                      1.6.0              Assertions to validate method input/out...
webmozart/glob                        4.1.0              A PHP implementation of Ant's glob.
webmozart/path-util                   2.3.0              A robust cross-platform utility for nor...
wp-cli/php-cli-tools                  v0.11.11           Console utilities for PHP
zendframework/zend-diactoros          2.2.1              PSR HTTP Message implementations
```

**Comment by Naktibalda** [comment]
A problem I see here is that you use different major versions of different Symfony components. Some are at v3, others - at v4 or v5.

The direct cause of the error you got is that you have Symfony/event-dispatcher 3.4, but also Symfony/contracts library which was introduced much later.

To fix it, upgrade event-dispatcher to v5 or uninstall Symfony/contracts.

**Comment by davidsneighbour** [comment]
I did not install these components "knowingly":

```json

  "require": {
    "php": "^7.3",
    "ext-curl": "*",
    "ext-fileinfo": "*",
    "ext-iconv": "*",
    "ext-imagick": "*",
    "ext-intl": "*",
    "ext-json": "*",
    "ext-openssl": "*",
    "ext-pdo": "*",
    "adodb/adodb-php": "^5.20.13",
    "bgalati/monolog-sentry-handler": "^1.0",
    "davidsneighbour/dropbox-php-sdk": "^0.2",
    "doctrine/orm": "^2.6",
    "egeniq/monolog-gdpr": "^1.0",
    "endroid/qr-code": "^2.5.0",
    "fabian-tomischka/php-avatar-generator": "dev-master",
    "florianv/swap": "^4.0",
    "guzzlehttp/guzzle": "^6.3.3",
    "henrikbjorn/lurker": "^1.2.0",
    "lavary/crunz": "^2.0",
    "league/event": "^2.1",
    "league/flysystem": "^1.0",
    "league/fractal": "^0.17.0",
    "league/glide": "^1.4",
    "league/iso3166": "^2.1",
    "league/period": "^4.0",
    "luracast/restler": "3.0.0-RC6",
    "michelf/php-markdown": "^1.8",
    "moneyphp/money": "^3.2",
    "monolog/monolog": "^1.24",
    "mpdf/mpdf": "^8",
    "mpdf/qrcode": "^1.0",
    "mremi/url-shortener": "^2.2",
    "myclabs/php-enum": "^1.6",
    "nesbot/carbon": "^2.19",
    "omise/omise-php": "^2.11",
    "paragonie/csp-builder": "^2.3",
    "php-http/async-client-implementation": "^1",
    "phpoffice/phpspreadsheet": "^1.4",
    "phpstan/phpstan-deprecation-rules": "^0.12.0",
    "phpstan/phpstan-phpunit": "^0.12.0",
    "phpstan/phpstan-strict-rules": "^0.12.0",
    "picqer/php-barcode-generator": "^0.3.0",
    "roave/security-advisories": "*",
    "sendgrid/sendgrid": "~7.2.1",
    "sensiolabs/security-checker": "^5.0",
    "sentry/sdk": "^2",
    "smarty/smarty": "^3.1.33",
    "thecodingmachine/phpstan-strict-rules": "^0.12.0",
    "thecodingmachine/safe": "^0.1.16"
  },
  "require-dev": {
    "codacy/coverage": "^1.4",
    "codeception/codeception": "^3.1",
    "edsonmedina/php_testability": "dev-master",
    "jakub-onderka/php-var-dump-check": "^0.3.0",
    "niels-de-blaauw/php-doc-check": "^0.2.1",
    "phan/phan": "^2",
    "phpstan/extension-installer": "^1.0",
    "phpstan/phpstan": "^0.12",
    "phpunit/php-code-coverage": "^7.0",
    "phpunit/phpunit": "^8.3",
    "vimeo/psalm": "^3.0"
  },

```

Is there a way to find out which package is requiring these versions? Or should I "just" require the symfony v5 versions of these libraries?

**Comment by Naktibalda** [comment]
This error is specific to Codeception 4 and it happens in Codeception 4 code, Codeception 3 does not support Symfony 5 components so you can't possibly get this error with it.

You could force composer to install the same minor version of Symfony components by adding this section to composer.json:
```js
    "extra": {
        "symfony": {
            "require": "4.4.*"
        }
    }
```

I will check if there is a way to detect version of symfony/event-dispatcher which does not depend on symfony/contracts.

**Comment by Naktibalda** [comment]
@davidsneighbour Please upgrade to codeception/codeception 4.0.1 and check if it works.

**Comment by davidsneighbour** [comment]
It works, thank you!
