### ISSUE TITLE
`init upgrade4` crashes when config has includes

### ISSUE THREAD

**Issue by mytskine** [Codeception/Codeception#5797]
#### What are you trying to achieve?
Upgrade to v4.

#### What do you get instead?
Crash.

As shown below, the root config has includes. Adding `-c somedir` to the command make it work, but it shouldn't crash in any case.

By the way, I run this upgrade command half a dozen times, and the 3 seconds delay about the survey was getting on my nerves. I have other projects to migrate with 2 or 3 envs each, but I'll patch Codeception or these waits will drive me mad. In my humble opinion, in its current state this mandatory "feature" slightly harm the project.

> Provide console output if related. Use `-vvv` mode for more details.

```bash
# php vendor/bin/codecept init upgrade4

==== Redirecting to Composer-installed version in vendor/codeception. You can skip this using --no-redirect ====
> Welcome to Codeception v4 Upgrade wizard!

Codeception is maintained since 2011, is free & open-source.
To make it better we need your feedback on it!

Please take a minute and fill in a brief survey:
http://bit.ly/codecept-survey

? Did you fill in the survey? (y/n) y
Thank you! 
PHP Fatal error:  Uncaught Error: Call to undefined method Codeception\Template\Upgrade4::sayError() in vendor/codeception/codeception/src/Codeception/Template/Upgrade4.php:37
Stack trace:
#0 vendor/codeception/base/src/Codeception/Command/Init.php(53): Codeception\Template\Upgrade4->setup()
#1 vendor/symfony/console/Command/Command.php(255): Codeception\Command\Init->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 vendor/symfony/console/Application.php(1011): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 vendor/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Init), Object(Symfony\Component\Console\Input\ArgvInput), Obj in vendor/codeception/codeception/src/Codeception/Template/Upgrade4.php on line 37
```

### Details

* Codeception version: 4.0.0
* PHP Version: 7.3.12
* Operating System: Debian stable
* Installation type: Composer
* List of installed packages: (a later update had no effect)
```
 # composer show | grep codecept        
codeception/codeception            4.0.0
codeception/lib-asserts            1.10.1
codeception/lib-innerbrowser       1.2.3
codeception/module-yii2            1.0.1
codeception/phpunit-wrapper        8.1.0
codeception/stub                   3.6.0
codeception/verify                 1.2.0
```
* Suite configuration:

```yml
include:
    - common
    - frontend
paths:
    log: console/runtime/logs
```

**Comment by Naktibalda** [comment]
Fixed in 4.0.1
