### ISSUE TITLE
PHP 8: Gherkin loader

### ISSUE THREAD

**Issue by samdark** [Codeception/Codeception#6032]
Trying to run Yii 2 module tests under PHP 8: https://github.com/Codeception/module-yii2/pull/18/checks?check_run_id=1406528240#step:8:61

- Codeception v4.1.12
- PHPUnit 9.4.3

Getting the following error:

```
PHP Fatal error:  Uncaught TypeError: get_class_methods(): Argument #1 ($object_or_class) must be an object or a valid class name, string given in /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/Test/Loader/Gherkin.php:104
Stack trace:
#0 /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/Test/Loader/Gherkin.php(104): get_class_methods()
#1 /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/Test/Loader/Gherkin.php(94): Codeception\Test\Loader\Gherkin->addSteps()
#2 /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/Test/Loader/Gherkin.php(55): Codeception\Test\Loader\Gherkin->fetchGherkinSteps()
#3 /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/Test/Loader.php(54): Codeception\Test\Loader\Gherkin->__construct()
#4 /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/SuiteManager.php(97): Codeception\Test\Loader->__construct()
#5 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/src/Codeception/Codecept.php(206): Codeception\SuiteManager->loadTests()
#6 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/src/Codeception/Codecept.php(162): Codeception\Codecept->runSuite()
#7 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/src/Codeception/Command/Run.php(511): Codeception\Codecept->run()
#8 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/src/Codeception/Command/Run.php(480): Codeception\Command\Run->runSuites()
#9 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/src/Codeception/Command/Run.php(410): Codeception\Command\Run->runIncludedSuites()
#10 /home/runner/work/module-yii2/module-yii2/vendor/symfony/console/Command/Command.php(255): Codeception\Command\Run->execute()
#11 /home/runner/work/module-yii2/module-yii2/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#12 /home/runner/work/module-yii2/module-yii2/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#13 /home/runner/work/module-yii2/module-yii2/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#14 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/src/Codeception/Application.php(117): Symfony\Component\Console\Application->run()
#15 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/app.php(46): Codeception\Application->run()
#16 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/app.php(47): {closure}()
#17 /home/runner/work/module-yii2/module-yii2/vendor/codeception/codeception/codecept(7): require('...')
#18 {main}
  thrown in /home/runner/work/module-yii2/module-yii2/framework-tests/vendor/codeception/codeception/src/Codeception/Test/Loader/Gherkin.php on line 104
```

**Comment by samdark** [comment]
Can't be properly solved until we have testing back: https://github.com/Codeception/Codeception/pull/6046

**Comment by Naktibalda** [comment]
Testing is back.

GherkinTest in unit suite passes, probably tests are too simple and the issue is Yii2 specific.

**Comment by Naktibalda** [comment]
The root cause is that Yii2 test suite uses namespaced FulctionalHelper and Gherkin Loader failed to load methods from it.

get_class_methods('NonExistentClass') fails silently in PHP7 and returns NULL, but it fails with fatal error in PHP8.
So this fix will make things better for PHP7 too.

**Comment by Naktibalda** [comment]
Invalid context PHP8 complained about was tests\\FunctionalTester , there must be only one backslash between namespaces.
