### ISSUE TITLE
Tests fail with symfony/browser-kit 5.2

### ISSUE THREAD

**Issue by omsi668** [Codeception/Codeception#6102]
Hello,

#### What are you trying to achieve?

I try to run my API tests after an update from Symfony 5.1 to 5.2. But symfony/browser-kit introduced a quite dumb BC break which is converting every parameter to string.

The solution from the brilliant fabpot is : "you should fix your tests as everything coming from a request is a string (that's what we fixed in 5.2)."

(see https://github.com/symfony/symfony/issues/38591#issuecomment-709785468)

However, when I send a Json object with booleans, it seems fair to me to check if the return is a boolean, because that's what the application is looking for, and that's how it works.

By the way, everything is working fine when forcing symfony-browser 5.1

#### What do you get instead?

```bash
8) CreateCest: Test create success
 Test  tests/api/Controller/Station/CreateCest.php:testCreateSuccess
 Step  See response code is 201
 Fail  Expected HTTP Status Code: 201 (Created). Actual Status Code: 500 (Internal Server Error)
Failed asserting that 500 matches expected 201.

Scenario Steps:

 7. $I->seeResponseCodeIs(201) at tests/api/Controller/Station/CreateCest.php:58
 6. $I->sendPost("/station",{"label":"Test station","branch":2,"isActive":true,"isFork":true,"lineId":1}) at tests/api/Controller/Station/CreateCest.php:56
 5. $I->grabEntityFromRepository("App\Entity\Line",{"label":"1"}) at tests/api/Controller/Station/CreateCest.php:48
 4. $I->amBearerAuthenticated("c171cac1c3a44e225b84072391e789f7c5230915737b045ddcb7a4c82c5213272d410bbc38dc8efb6d51e8401e80226517af9a1542548c9db95416724746b6be0ec21b2f632677b633e051e89e0a89af2ea2409e3...") at tests/_support/ApiTester.php:38
 3. $I->grabService("App\Service\UserService") at tests/_support/ApiTester.php:36
 2. $I->grabEntityFromRepository("App\Entity\User",{"email":"admin.1@positivethinking.tech"}) at tests/_support/ApiTester.php:33

Artifacts:

Html: /var/www/html/backend/tests/_output/App.Tests.api.Controller.Station.CreateCest.testCreateSuccess.fail.html
Response: /var/www/html/backend/tests/_output/App.Tests.api.Controller.Station.CreateCest.testCreateSuccess.fail.html
Body: {"code":500,"message":"The type of the \u0022branch\u0022 attribute for class \u0022App\\Entity\\Station\u0022 must be one of \u0022int\u0022 (\u0022string\u0022 given).","errors":[],"trace":[{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/serializer\/Normalizer\/AbstractObjectNormalizer.php","line":334,"function":"validateAndDenormalize","class":"Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/serializer\/Serializer.php","line":208,"function":"denormalize","class":"Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/src\/Service\/StationService.php","line":81,"function":"denormalize","class":"Symfony\\Component\\Serializer\\Serializer","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/src\/Controller\/Station\/Create.php","line":68,"function":"create","class":"App\\Service\\StationService","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":157,"function":"__invoke","class":"App\\Controller\\Station\\Create","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":79,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/Kernel.php","line":195,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/HttpKernelBrowser.php","line":63,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/module-symfony\/src\/Codeception\/Lib\/Connector\/Symfony.php","line":73,"function":"doRequest","class":"Symfony\\Component\\HttpKernel\\HttpKernelBrowser","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/browser-kit\/AbstractBrowser.php","line":384,"function":"doRequest","class":"Codeception\\Lib\\Connector\\Symfony","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/lib-innerbrowser\/src\/Codeception\/Lib\/InnerBrowser.php","line":233,"function":"request","class":"Symfony\\Component\\BrowserKit\\AbstractBrowser","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/lib-innerbrowser\/src\/Codeception\/Lib\/InnerBrowser.php","line":157,"function":"clientRequest","class":"Codeception\\Lib\\InnerBrowser","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/module-rest\/src\/Codeception\/Module\/REST.php","line":630,"function":"_request","class":"Codeception\\Lib\\InnerBrowser","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/module-rest\/src\/Codeception\/Module\/REST.php","line":454,"function":"execute","class":"Codeception\\Module\\REST","type":"-\u003E"},{"function":"sendPost","class":"Codeception\\Module\\REST","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Step.php","line":268,"function":"call_user_func_array"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Scenario.php","line":76,"function":"run","class":"Codeception\\Step","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/tests\/_support\/_generated\/ApiTesterActions.php","line":3847,"function":"runStep","class":"Codeception\\Scenario","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/tests\/api\/Controller\/Station\/CreateCest.php","line":56,"function":"sendPost","class":"App\\Tests\\ApiTester","type":"-\u003E"},{"function":"testCreateSuccess","class":"App\\Tests\\api\\Controller\\Station\\CreateCest","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Lib\/Di.php","line":128,"function":"invokeArgs","class":"ReflectionMethod","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Cest.php","line":138,"function":"injectDependencies","class":"Codeception\\Lib\\Di","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Cest.php","line":150,"function":"invoke","class":"Codeception\\Test\\Cest","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Cest.php","line":82,"function":"executeTestMethod","class":"Codeception\\Test\\Cest","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Test.php","line":98,"function":"test","class":"Codeception\\Test\\Cest","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/phpunit\/phpunit\/src\/Framework\/TestSuite.php","line":677,"function":"run","class":"Codeception\\Test\\Test","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/phpunit-wrapper\/src\/Runner.php","line":117,"function":"run","class":"PHPUnit\\Framework\\TestSuite","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/SuiteManager.php","line":161,"function":"doEnhancedRun","class":"Codeception\\PHPUnit\\Runner","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Codecept.php","line":208,"function":"run","class":"Codeception\\SuiteManager","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Codecept.php","line":162,"function":"runSuite","class":"Codeception\\Codecept","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Command\/Run.php","line":531,"function":"run","class":"Codeception\\Codecept","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Command\/Run.php","line":407,"function":"runSuites","class":"Codeception\\Command\\Run","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/console\/Command\/Command.php","line":256,"function":"execute","class":"Codeception\\Command\\Run","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/console\/Application.php","line":971,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/console\/Application.php","line":290,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/symfony\/console\/Application.php","line":166,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Application.php","line":117,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/app.php","line":46,"function":"run","class":"Codeception\\Application","type":"-\u003E"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/app.php","line":47,"function":"{closure}"},{"file":"\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/codecept","line":7,"args":["\/var\/www\/html\/backend\/vendor\/codeception\/codeception\/app.php"],"function":"require"}],"traceAsString":"#0 \/var\/www\/html\/backend\/vendor\/symfony\/serializer\/Normalizer\/AbstractObjectNormalizer.php(334): Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer-\u003EvalidateAndDenormalize()\n#1 \/var\/www\/html\/backend\/vendor\/symfony\/serializer\/Serializer.php(208): Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer-\u003Edenormalize()\n#2 \/var\/www\/html\/backend\/src\/Service\/StationService.php(81): Symfony\\Component\\Serializer\\Serializer-\u003Edenormalize()\n#3 \/var\/www\/html\/backend\/src\/Controller\/Station\/Create.php(68): App\\Service\\StationService-\u003Ecreate()\n#4 \/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/HttpKernel.php(157): App\\Controller\\Station\\Create-\u003E__invoke()\n#5 \/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/HttpKernel.php(79): Symfony\\Component\\HttpKernel\\HttpKernel-\u003EhandleRaw()\n#6 \/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/Kernel.php(195): Symfony\\Component\\HttpKernel\\HttpKernel-\u003Ehandle()\n#7 \/var\/www\/html\/backend\/vendor\/symfony\/http-kernel\/HttpKernelBrowser.php(63): Symfony\\Component\\HttpKernel\\Kernel-\u003Ehandle()\n#8 \/var\/www\/html\/backend\/vendor\/codeception\/module-symfony\/src\/Codeception\/Lib\/Connector\/Symfony.php(73): Symfony\\Component\\HttpKernel\\HttpKernelBrowser-\u003EdoRequest()\n#9 \/var\/www\/html\/backend\/vendor\/symfony\/browser-kit\/AbstractBrowser.php(384): Codeception\\Lib\\Connector\\Symfony-\u003EdoRequest()\n#10 \/var\/www\/html\/backend\/vendor\/codeception\/lib-innerbrowser\/src\/Codeception\/Lib\/InnerBrowser.php(233): Symfony\\Component\\BrowserKit\\AbstractBrowser-\u003Erequest()\n#11 \/var\/www\/html\/backend\/vendor\/codeception\/lib-innerbrowser\/src\/Codeception\/Lib\/InnerBrowser.php(157): Codeception\\Lib\\InnerBrowser-\u003EclientRequest()\n#12 \/var\/www\/html\/backend\/vendor\/codeception\/module-rest\/src\/Codeception\/Module\/REST.php(630): Codeception\\Lib\\InnerBrowser-\u003E_request()\n#13 \/var\/www\/html\/backend\/vendor\/codeception\/module-rest\/src\/Codeception\/Module\/REST.php(454): Codeception\\Module\\REST-\u003Eexecute()\n#14 [internal function]: Codeception\\Module\\REST-\u003EsendPost()\n#15 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Step.php(268): call_user_func_array()\n#16 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Scenario.php(76): Codeception\\Step-\u003Erun()\n#17 \/var\/www\/html\/backend\/tests\/_support\/_generated\/ApiTesterActions.php(3847): Codeception\\Scenario-\u003ErunStep()\n#18 \/var\/www\/html\/backend\/tests\/api\/Controller\/Station\/CreateCest.php(56): App\\Tests\\ApiTester-\u003EsendPost()\n#19 [internal function]: App\\Tests\\api\\Controller\\Station\\CreateCest-\u003EtestCreateSuccess()\n#20 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Lib\/Di.php(128): ReflectionMethod-\u003EinvokeArgs()\n#21 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Cest.php(138): Codeception\\Lib\\Di-\u003EinjectDependencies()\n#22 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Cest.php(150): Codeception\\Test\\Cest-\u003Einvoke()\n#23 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Cest.php(82): Codeception\\Test\\Cest-\u003EexecuteTestMethod()\n#24 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Test\/Test.php(98): Codeception\\Test\\Cest-\u003Etest()\n#25 \/var\/www\/html\/backend\/vendor\/phpunit\/phpunit\/src\/Framework\/TestSuite.php(677): Codeception\\Test\\Test-\u003Erun()\n#26 \/var\/www\/html\/backend\/vendor\/codeception\/phpunit-wrapper\/src\/Runner.php(117): PHPUnit\\Framework\\TestSuite-\u003Erun()\n#27 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/SuiteManager.php(161): Codeception\\PHPUnit\\Runner-\u003EdoEnhancedRun()\n#28 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Codecept.php(208): Codeception\\SuiteManager-\u003Erun()\n#29 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Codecept.php(162): Codeception\\Codecept-\u003ErunSuite()\n#30 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Command\/Run.php(531): Codeception\\Codecept-\u003Erun()\n#31 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Command\/Run.php(407): Codeception\\Command\\Run-\u003ErunSuites()\n#32 \/var\/www\/html\/backend\/vendor\/symfony\/console\/Command\/Command.php(256): Codeception\\Command\\Run-\u003Eexecute()\n#33 \/var\/www\/html\/backend\/vendor\/symfony\/console\/Application.php(971): Symfony\\Component\\Console\\Command\\Command-\u003Erun()\n#34 \/var\/www\/html\/backend\/vendor\/symfony\/console\/Application.php(290): Symfony\\Component\\Console\\Application-\u003EdoRunCommand()\n#35 \/var\/www\/html\/backend\/vendor\/symfony\/console\/Application.php(166): Symfony\\Component\\Console\\Application-\u003EdoRun()\n#36 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/src\/Codeception\/Application.php(117): Symfony\\Component\\Console\\Application-\u003Erun()\n#37 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/app.php(46): Codeception\\Application-\u003Erun()\n#38 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/app.php(47): {closure}()\n#39 \/var\/www\/html\/backend\/vendor\/codeception\/codeception\/codecept(7): require(\u0027\/var\/www\/html\/b...\u0027)\n#40 {main}"}

```
> Provide test source code if related

Here is the involved part of the test
```php
        $I->sendPost('/station', [
            'label' => 'Test station',
            'branch' => 2,
            'isActive' => true,
            'isFork' => true,
            'lineId' => $lineId,
        ]);
        $I->seeResponseCodeIs(HttpCode::CREATED); // 201
        $I->seeResponseIsJson();
        // assert response structure
        $I->seeResponseMatchesJsonType([
            'id' => 'integer',
            'label' => 'string',
            'branch' => 'integer',
            'sortOrder' => 'integer',
            'isActive' => 'boolean',
            'isMutable' => 'boolean',
            'isFork' => 'boolean',
            'lineId' => 'integer',
        ]);
```

### Details

* Codeception version: 4.1.16
* PHP Version: 7.4.9
* Operating System: Ubuntu
* Installation type: Composer
* List of installed packages (`composer show`)
* Suite configuration:

```yml
actor: ApiTester
modules:
    enabled:
        - Symfony:
              app_path: 'src'
              environment: 'test'
              kernel_class: 'App\Kernel'
        - REST:
              url: /
              depends: Symfony
        - Doctrine2:
              depends: Symfony
              cleanup: true
              # All doctrine queries will be wrapped in a transaction, which will be rolled back at the end of each test
              # By doing this, tests will run much faster and will be isolated from each other.
```

I'm not sure this is a codeception issue and not a Symfony one but as the problem occurs only on my API tests, I guess so. 

Thank you for your help

**Comment by Naktibalda** [comment]
To send JSON you have to call `$I->haveHttpHeader('Content-Type', 'application/json');` before `sendPost`

**Comment by omsi668** [comment]
Allright.

Thank you
