### ISSUE TITLE
Argument #2 ($arguments) must be of type array, string given, Cest.php 

### ISSUE THREAD

**Issue by Pi-George** [Codeception/Codeception#6168]
```
Codeception PHP Testing Framework v4.1.18
Powered by PHPUnit 9.4.0 by Sebastian Bergmann and contributors.
Fatal error: Uncaught TypeError: Codeception\Step::__construct(): Argument #2 ($arguments) must be of type array, string given, called in /srv/www/vendor/codeception/codeception/src/Codeception/Test/Cest.php on line 52 and defined in /srv/www/vendor/codeception/codeception/src/Codeception/Step.php:41
Stack trace:
#0 /srv/www/vendor/codeception/codeception/src/Codeception/Test/Cest.php(52): Codeception\Step->__construct()
#1 /srv/www/vendor/codeception/codeception/src/Codeception/SuiteManager.php(248): Codeception\Test\Cest->preload()
#2 /srv/www/vendor/codeception/codeception/src/Codeception/SuiteManager.php(112): Codeception\SuiteManager->configureTest()
#3 /srv/www/vendor/codeception/codeception/src/Codeception/SuiteManager.php(116): Codeception\SuiteManager->addToSuite()
#4 /srv/www/vendor/codeception/codeception/src/Codeception/SuiteManager.php(105): Codeception\SuiteManager->addToSuite()
#5 /srv/www/vendor/codeception/codeception/src/Codeception/Codecept.php(206): Codeception\SuiteManager->loadTests()
#6 /srv/www/vendor/codeception/codeception/src/Codeception/Codecept.php(162): Codeception\Codecept->runSuite()
#7 /srv/www/vendor/codeception/codeception/src/Codeception/Command/Run.php(532): Codeception\Codecept->run()
#8 /srv/www/vendor/codeception/codeception/src/Codeception/Command/Run.php(407): Codeception\Command\Run->runSuites()
#9 /srv/www/vendor/symfony/console/Command/Command.php(256): Codeception\Command\Run->execute()
#10 /srv/www/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#11 /srv/www/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#12 /srv/www/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#13 /srv/www/vendor/codeception/codeception/src/Codeception/Application.php(117): Symfony\Component\Console\Application->run()
#14 /srv/www/vendor/codeception/codeception/app.php(46): Codeception\Application->run()
#15 /srv/www/vendor/codeception/codeception/app.php(47): {closure}()
#16 /srv/www/vendor/codeception/codeception/codecept(7): require('...')
#17 {main}
  thrown in /srv/www/vendor/codeception/codeception/src/Codeception/Step.php on line 41
```

I frankly have no idea how I've caused this, I'm just trying to add a new suite to the tests and I can't even see how my new suite is different to the others (which work fine). I'm guessing I've missed something stupid but I'm just trying to figure out what.

**Comment by Pi-George** [comment]
Nevermind, I figured it out, the data provider has to be a 2d array not a 1d array
